### PR TITLE
[core, lua] SPAWN listener after onMobSpawn

### LINKED ISSUE #7796: 🐛 updateClaim in a SPAWN listener only half works
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

giving claim on spawn via a `SPAWN` listener doesn't fully work. There's quite a few out-of-order enmity/claim cleanups going on in the mob spawn flow:

Image

Image

But even with adjusting that, the mob goes red for a second, then blips back to unclaimed in [this section of the first combat tick](https://github.com/LandSandBoat/server/blob/e9c2072ff956ee40742189d83ff02db09ca109e1/src/map/ai/controllers/mob_controller.cpp#L578)

I traced it down to `battleutils::ClaimMob` having checks for `isAlive()`. So I believe this is an unsolvable problem without moving where the `SPAWN` listener is triggered, which fundamentally has a lot of considerations, I would think

## Branch affected by issue 

`base`

## Steps to reproduce

- create a spawn listener on a mob with the following code
```
entity.onMobInitialize = function(mob)
    mob:addListener('SPAWN', 'SPAWNLISTENER', function(mobArg)
        local player = GetPlayerByID(1)
        mob:updateClaim(player)
        print(mob:isAlive())
    end)
end
```
- `!gotoname` the mob
- spawn it
- see that it aggros you from the updateClaim call, name goes red, then immediately goes un-red
- check map server log to see that the mob is indeed considered dead during the spawn listener

Edit: the above steps only happen as described with the enmity rearranging in `mobentity.cpp`. In base LSB, the listener is completely ignored in the `SPAWN` listener

## Expected behavior

mob is alive in the `SPAWN` listener like it is during `onMobSpawn()` lua functions

### PR DESCRIPTION
**Pull request by sruon**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
This is a change I've been meaning to make since #7246 

Currently the SPAWN listeners are executed very early in the entity lifecycle - before mods are applied/force reset, claim cleaned up etc.

This leads to the SPAWN listener being generally useless when you need to change anything of value. Furthermore, unlike other listeners it runs before the sister lua method (onMobSpawn) which is incredibly confusing.

- This PR executes the listeners _after_ onMobSpawn has been completed.
  - Any change performed within the listener will now correctly persist as expected
- Reverts the claim shield to how it was before #7246 
- Also fixes the packetName not being obtained from DB for regular mobs, which has led to the claim shield reporting empty names.

I believe this closes #7796 - I also believe this now allows performing the function of #7791 in a SPAWN listener instead of customizing the C++ side.

## Steps to test these changes

I have retested the claim shield - unfortunately this is the only piece in the codebase making use of this listener so I might have missed other use cases.

- Enable claim shield lua module
- !zone Mount Zhayolm
- !gotoid 17027458
- !spawnmob 17027458

### CODE REVIEW

File: modules/custom/lua/claim_shield.lua [hunk 1]
```diff
@@ -158,16 +158,16 @@ end
 
 -- Main entrypoint of each override
 local overrideFunc = function(mob)
-    spawnFunc(mob)
+    mob:addListener('SPAWN', mob:getPacketName() .. '_CS_SPAWN', listenerFunc)
```
Comment (zach2good) [inline modules/custom/lua/claim_shield.lua]: Please use `string.format` or `fmt` for building strings, `..` is harder to follow

**Review by zach2good — APPROVED** [review]

File: modules/custom/lua/claim_shield.lua (hunk 1 above)
Comment (sruon) [reply modules/custom/lua/claim_shield.lua]: updated

**Review by WinterSolstice8 — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]
