### PR TITLE
fix port bastok tenshodo vendors

### LINKED ISSUE #8165: 🐛 Port Bastok Tenshodo shop does not work properly
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

When in possession of a Tenshodo Member's Card(Keyitem 118), speak to Jabbar or Silver Owl in the warehouse in Port Bastok (F-6).

When speaking to either, you will get some overlapping dialog from both NPCs, the Buy/Sell menu will open for a fraction of a second and then close.

## Expected behavior

You should be able to buy from these two NPC's respective guild shops.

### PR DESCRIPTION
**Pull request by andymo**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Fixes https://github.com/LandSandBoat/server/issues/8165

The Port Bastok Tenshodo vendors are involved in the Tenshodo Membership quest, and had a default event associated with them. Moving the default event to the onTrigger for each NPC stopped it from firing when in possession of the membership card.

Note the other Tenshodo vendors did not have a default event associated with them (and do not respond at all if you don't have the KI, but I don't have a capture for that event id).

## Steps to test these changes

`!delkeyitem 118`
Talk to Silver Owl and Jabbar, make sure they have nothing to sell you
`!addkeyitem 118`
Talk to both, be able to browse shop.

Also checked this didn't interfere with regular quest completion events.

### CODE REVIEW

**Comment by slashtangent** [comment]
So I was initially against this fix. But after some research and some testing, I think this is the best way to handle this.

Normally, vendors don't have dialogue outside of their normal shop dialogue; however, these two vendors do. After checking my recent capture of Norg (pre-tenshodo). I do think that these are the only tenshodo vendors that have checks to see if you are a member. All of the other Tenshodo vendors (that are accessible) would sell to me prior to having a membership. The only other vendor who might not is the one in Nashmau (I didn't check that one). Since the Jeuno vendors should be inaccessible until you are a member.

I did some testing by modifying another vendor and giving them a default action, and I am seeing the same issue there as well.

Due to the lack of a need case, I think this is the best fix unless someone wants to rework default actions for this niche case.

File: scripts/zones/Port_Bastok/npcs/Jabbar.lua [hunk 1]
```diff
@@ -5,14 +5,18 @@
...
+local ID = zones[xi.zone.PORT_BASTOK]
+-----------------------------------
 ---@type TNpcEntity
 local entity = {}
 
 entity.onTrigger = function(player, npc)
     if player:hasKeyItem(xi.ki.TENSHODO_MEMBERS_CARD) then
         if player:sendGuild(60419, 1, 23, 4) then
-            player:showText(npc, zones[xi.zone.PORT_BASTOK].text.TENSHODO_SHOP_OPEN_DIALOG)
+            player:showText(npc, ID.text.TENSHODO_SHOP_OPEN_DIALOG)
```
Comment (slashtangent) [inline scripts/zones/Port_Bastok/npcs/Jabbar.lua]: This change is unneeded. But I'll let the LSB curators decide if they feel it's worth changing.

Comment (Xaver-DaRed) [reply scripts/zones/Port_Bastok/npcs/Jabbar.lua]: This change is unneeded. ID is only used once.

File: scripts/zones/Port_Bastok/npcs/Silver_Owl.lua [hunk 2]
```diff
@@ -4,14 +4,18 @@
...
+local ID = zones[xi.zone.PORT_BASTOK]
+-----------------------------------
 ---@type TNpcEntity
 local entity = {}
 
 entity.onTrigger = function(player, npc)
     if player:hasKeyItem(xi.ki.TENSHODO_MEMBERS_CARD) then
         if player:sendGuild(60420, 1, 23, 4) then
-            player:showText(npc, zones[xi.zone.PORT_BASTOK].text.TENSHODO_SHOP_OPEN_DIALOG)
+            player:showText(npc, ID.text.TENSHODO_SHOP_OPEN_DIALOG)
```
Comment (Xaver-DaRed) [inline scripts/zones/Port_Bastok/npcs/Silver_Owl.lua]: Same here.

**Comment by andymo** [comment]
> So I was initially against this fix. But after some research and some testing, I think this is the best way to handle this.
> 
> Normally, vendors don't have dialogue outside of their normal shop dialogue; however, these two vendors do. After checking my recent capture of Norg (pre-tenshodo). I do think that these are the only tenshodo vendors that have checks to see if you are a member. All of the other Tenshodo vendors (that are accessible) would sell to me prior to having a membership. The only other vendor who might not is the one in Nashmau (I didn't check that one). Since the Jeuno vendors should be inaccessible until you are a member.
> 
> I did some testing by modifying another vendor and giving them a default action, and I am seeing the same issue there as well.
> 
> Due to the lack of a need case, I think this is the best fix unless someone wants to rework default actions for this niche case.

Current LSB implementation is that all Tenshodo vendors check for membership; would love to see the relevant parts of the capture where the vendors are open to all.

The Nashmau vendor requires Tenshodo access to get to in the first place, so I can probably just remove that check altogether.

**Comment by slashtangent** [comment]
From my capture below. It's on my shortlist to audit the default actions of the npcs in Norg. My capture is complete, I just need to do the work now.

This was pre-joining the Tenshodo. Since this was just a default action audit, I didn't pay too much attention to their shop inventory.

Capture parameters:
`
[22:56:45] (Slashtangent) Norg NPC capture. Not a member of the tenshodo
[22:56:46] [NPCL] New: 17809439 (Oruga)
[22:56:52] (Slashtangent) 7RoE 0 quests/missions completed
[22:56:54] (Slashtangent) level 10
[22:56:57] (Slashtangent) 0 fame
`

Captured events from Achika and Jirokichi.
`[23:01:44] [ID View] INCOMING < NPC Chat (0x036): NPC: 17809447 (Achika), Message: 10366
[23:01:44] Achika : Can I interest you in some armor forged in the surrounding regions?`

`[23:01:52] [ID View] INCOMING < NPC Chat (0x036): NPC: 17809446 (Jirokichi), Message: 10364
[23:01:52] Jirokichi : Heh-heh-heh. Feast your eyes on these beauties. You won't find stuff like this anywhere!`

**Comment by slashtangent** [comment]
Give me a few hours and I can smuggle another new lvl 3 (RoV 1-1-4) into Norg to triple check.

The check on the other NPCs I think is fine as an anti-cheat measure. They just stand there because by design they don't have a default action.

**Comment by andymo** [comment]
Sweet, thanks! My hunch is that `Vuliaie` would not sell to you without a membership as they are a Tenshodo guild member. I'll double-check that the others make their stock available.

**Comment by slashtangent** [comment]
Just finished checking. All 4 of the Norg Tenshodo vendors have their shop wide open to non members.

https://youtu.be/E2M170-dtPw?si=3mmjIxd5SBTE8aCw&t=447

**Comment by andymo** [comment]
Sounds good, I saw you fixed Norg vendors in another PR so I just made the ID modification here and this should be ready for review again

**Review by Xaver-DaRed — APPROVED** [review]
