### PR TITLE
[lua] Correct isValidEntry logic to trade for registration

### LINKED ISSUE #5613: 🐛 Central Apollyon entry
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

I don't see what would be causing it, but trading to get entry into central apollyon just spits out the default onTrigger message:

image

I'm not very well-versed in troubleshooting these new battlefield files if the error isn't obvious in the code, sorry. Any help would be appreciated.

Best i can tell the requirements are correct, battlefield index, etc

### PR DESCRIPTION
**Pull request by MowFord**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Closes https://github.com/LandSandBoat/server/issues/5613 .

The `isValidEntry` logic was referencing the battlefield `entryNpc` value (which never explicitly gets set, it gets passed and used to build a table of one entry for `entryNpcs`) instead of the traded npc's name

## Steps to test these changes

Give yourself all the key items and items and trade the 4 chips to the swirling vortex

### CODE REVIEW

**Review by Xaver-DaRed — DISMISSED** [review]

**Review by WinterSolstice8 — APPROVED** [review]
Makes sense, apollyon has multiple entrances for this

File: scripts/battlefields/Apollyon/central_apollyon.lua [hunk 1]
```diff
@@ -26,7 +26,7 @@ local content = Limbus:new({
 })
 
 function content:isValidEntry(player, npc)
-    return self.entryNpc == '_12i' or self.entryNpc == '_127'
+    return npc and (npc:getName() == '_12i' or npc:getName() == '_127')
```
Comment (claywar) [inline scripts/battlefields/Apollyon/central_apollyon.lua]:
```
for _, npcName in self.entryNpcs do
    if npc:getName == npcName then
        return true
    end

    return false
end
```

Comment (claywar) [reply scripts/battlefields/Apollyon/central_apollyon.lua]: entryNpcs is a table, entryNpc on construct is now converted to a table, so this was a miss on my part

Comment (claywar) [reply scripts/battlefields/Apollyon/central_apollyon.lua]: Also set entryNpcs in the constructor to { '_12i, '_127' }

Comment (claywar) [reply scripts/battlefields/Apollyon/central_apollyon.lua]: Most likely now that I think of it, you won't even need the entry function in this BCNM

Comment (MowFord) [reply scripts/battlefields/Apollyon/central_apollyon.lua]: Got it, so for both we just need to remove the isvalidentry override and defined entryNpcs in their constructors?

Comment (claywar) [reply scripts/battlefields/Apollyon/central_apollyon.lua]: I believe so.  Sorry for the mixed info as I was thinking through things, but yeah, that should work on its own.  Added support for multiple entrances with Divine Might, so the same logic should work here I think

Comment (MowFord) [reply scripts/battlefields/Apollyon/central_apollyon.lua]: Yep, simpler logic and it works.

Really love the new battlefield content structure. Easy to module changes, cleaner format, more things in one place

**Review by WinterSolstice8 — APPROVED** [review]
A lot more elegant
