### PR TITLE
[Fix] And rewrite CoP 6-4 battlefield

### LINKED ISSUE #1262: CoP 6-4 Airship fight is buggy
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**On my private server, solo:**
- Killing Ultima during the Airship fight doesn't trigger CS, could not complete mission.

**On Supernova server, in a party:**
- At most 1 player gets teleported to the next ship. The others remain behind on the mammets/omega ship.
- Did a !bring players w/o zoning them to get them to the right spot for the next fight (Omega/Ultima).
- Omega/Ultima don't spawn. I spawned them. Killing Omega triggered the next CS. Still only one player got teleported to the next ship.
- Spawned Ultima, but killing him doesn't trigger CS, could not complete mission.

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

Fixes:
- Battlefield not triggering final cutscenes, making the mission impossible to complete.
- Battlefield not properly clearing itself when leaving.
- Incorrect event being played after first battle.
- Post mammet batle event being played multiple times when killing several mammets at the same time.
- Airship door giving incorrect options after mammets battle.
- Player Position and rotation when returning to the airship after each fight.
- Removed some unused logic and simplified quest logic (a little).

Closes #1262

### CODE REVIEW

File: scripts/zones/Sealions_Den/bcnms/one_to_be_feared.lua [hunk 1]
```diff
@@ -36,17 +37,17 @@ end
...
     if csid == 32001 then
         if player:getCurrentMission(COP) == xi.mission.id.cop.ONE_TO_BE_FEARED and player:getCharVar("PromathiaStatus") == 3 then
-            player:setCharVar("PromathiaStatus", 4)
+            player:completeMission(xi.mission.log_id.COP, xi.mission.id.cop.ONE_TO_BE_FEARED)
+            player:addMission(xi.mission.log_id.COP, xi.mission.id.cop.CHAINS_AND_BONDS)
+            player:setCharVar("PromathiaStatus", 0)
+            player:startEvent(33)
+            player:addExp(1500)
         end
-        player:addExp(1500)
```
Comment (claywar) [inline scripts/zones/Sealions_Den/bcnms/one_to_be_feared.lua:48]: Are we certain that those helping don't get xp?

File: scripts/zones/Sealions_Den/helpers/One_to_be_Feared.lua [hunk 2]
```diff
@@ -0,0 +1,141 @@
+-----------------------------------
+-- Global file for "One to be Feared" Battlefield
+-----------------------------------
+local ID = require("scripts/zones/Sealions_Den/IDs")
+require("scripts/globals/titles")
+-----------------------------------
+xi = xi or {}
```
Comment (claywar) [inline scripts/zones/Sealions_Den/helpers/One_to_be_Feared.lua]: This file should probably return an object and not be attached to the xi global, for as specific as it is

File: scripts/zones/Sealions_Den/helpers/One_to_be_Feared.lua [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+        local ultimaId = ID.mob.ONE_TO_BE_FEARED_OFFSET + (7 * (battlefield:getArea() - 1)) + 6
+        if not GetMobByID(ultimaId):isSpawned() then
+            SpawnMob(ultimaId)
+            battlefield:setLocalVar("phaseChange", 0)
+        end
+
+    -- Leave battlefield.
+    elseif csid == 32003 and option == 2 then
+        player:updateEvent(3)
+        return true
```
Comment (claywar) [inline scripts/zones/Sealions_Den/helpers/One_to_be_Feared.lua]: Doesn't look like we're using this and the below return value anywhere, probably not needed

**Review by claywar — APPROVED** [review]
