### PR TITLE
[core, lua] Add missing Mob logic to HandleAura & cleanup aura API

### LINKED ISSUE #299: GEO Aura logic for Mobs is missing
**REMINDER:** Caps discord is for caps, not support. If you have problems or find bugs, please raise GitHub issues so we can look up details after-the-fact.

I mis-remembered the state of GEO auras when Shiyo asked in caps discord: Only players have access to auras in `base`. The block that allows mobs to use/have auras is missing - probably existing in one of the inactive `geo` branches in TPZ/TPZ-N.

I've quickly thrown together a block that adds supportive/antagonistic aura support for mobs:
(add to the end of `void CStatusEffectContainer::HandleAura(CStatusEffect* PStatusEffect)`:

```cpp
    else if (PEntity->objtype == TYPE_MOB)
    {
        if (auraTarget == AURA_TARGET::ALLIES)
        {
            PEntity->ForParty([&](CBattleEntity* PMember) {
                if (PMember != nullptr && PEntity->loc.zone->GetID() == PMember->loc.zone->GetID() && distance(m_POwner->loc.p, PMember->loc.p) <= aura_range &&
                    !PMember->isDead())
                {
                    CStatusEffect* PEffect = new CStatusEffect((EFFECT)PStatusEffect->GetSubID(),    // Effect ID
                                                               (uint16)PStatusEffect->GetSubID(),    // Effect Icon (Associated with ID)
                                                               (uint16)PStatusEffect->GetSubPower(), // Power
                                                               3,                                    // Tick
                                                               4);                                   // Duration
                    PEffect->SetFlag(EFFECTFLAG_NO_LOSS_MESSAGE);
                    PMember->StatusEffectContainer->AddStatusEffect(PEffect, true);
                }
            });
        }
        else if (auraTarget == AURA_TARGET::ENEMIES)
        {
            auto* PMob = static_cast<CMobEntity*>(PEntity);
            auto* enmityList = PMob->PEnmityContainer->GetEnmityList();
            for (auto& enmityPair : *enmityList)
            {
                auto* PTarget = enmityPair.second.PEnmityOwner;
                if (PTarget != nullptr && PEntity->loc.zone->GetID() == PTarget->loc.zone->GetID() && distance(m_POwner->loc.p, PTarget->loc.p) <= aura_range &&
                    !PTarget->isDead())
                {
                    CStatusEffect* PEffect = new CStatusEffect((EFFECT)PStatusEffect->GetSubID(),    // Effect ID
                                                               (uint16)PStatusEffect->GetSubID(),    // Effect Icon (Associated with ID)
                                                               (uint16)PStatusEffect->GetSubPower(), // Power
                                                               3,                                    // Tick
                                                               4);                                   // Duration
                    PEffect->SetFlag(EFFECTFLAG_NO_LOSS_MESSAGE);
                    PTarget->StatusEffectContainer->AddStatusEffect(PEffect, true);
                }
            }
        }
    }
```

Tested with this gm command:
```lua
require("scripts/globals/geo")
require("scripts/globals/status")

cmdprops =
{
    permission = 1,
    parameters = ""
}

function onTrigger(player)
    player:PrintToPlayer("Adding effect to target")
    player:getCursorTarget():addStatusEffectEx(xi.effect.COLURE_ACTIVE, xi.effect.COLURE_ACTIVE, 0, 3, 0, xi.effect.GEO_POISON, 10, xi.auraTarget.ENEMIES, xi.effectFlag.AURA)
end
```

Poison appears as a status effect when you go onto the mobs enmity list

- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**

### PR DESCRIPTION
**Pull request by zach2good**
Closes https://github.com/LandSandBoat/server/issues/299

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

File: scripts/globals/geo.lua [hunk 1]
```diff
@@ -8,15 +8,27 @@ require("scripts/globals/status")
...
 
+-----------------------------------
+-- tickEffect: The effect being granted/imposed by the aura
+--             Use xi.effect table: xi.effect.GEO_POISON for example,
+--               but doesn't _need_ to be a GEO_ effect)
+-- tickPower:  The power of the tick (healing amount, damage amount, etc.)
+-- targetType: Target allies or enemies with:
+--             xi.auraTarget.ALLIES or xi.auraTarget.ENEMIES
+-----------------------------------
+xi.geo.addAura = function(target, tickEffect, tickPower, targetType)
```
Comment (zach2good) [inline scripts/globals/geo.lua]: TODO: Maybe pass in duration here?

**Review by claywar — APPROVED** [review]
