### PR TITLE
Update Steal and THF AF Fix

### LINKED ISSUE #1039: Quadav Stew can only be stolen from Garnet Quadavs ATM
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
It should be able to be stolen from Bronze, Silver and Zircon Quadavs. Only in Beadeaux Zone.

### PR DESCRIPTION
**Pull request by ari-osm**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Steal will randomly select an item from a mobs steal table.
Updates THF AF 1 quest to allow Quadav Stew to be stolen before the quest is flagged.

Closes #1039 

## Steps to test these changes

Use steal on low level quadavs in Beadeaux.  Will now randomly steal either Quadav Stew or Silver Beastcoin.
Use steal on low level quadavs in Beadeaux with the quest "The Tenshodo Showdown" active will always steal Quadav Stew.

### CODE REVIEW

File: scripts/globals/abilities/steal.lua [hunk 1]
```diff
@@ -71,9 +73,10 @@ ability_object.onUseAbility = function(player, target, ability, action)
     local stealChance = 50 + stealMod * 2 + thfLevel - target:getMainLvl()
 
     stolen = target:getStealItem()
-    if (target:isMob() and math.random(100) < stealChance and stolen ~= 0) then
-        if (checkThfAfQuest(player, target) == true) then
-            stolen = 4569
+    if target:isMob() and math.random(100) < stealChance and stolen ~= 0 then
+        -- This guarantees item if quest is flagged
+        if checkThfAfQuest(player, target) == true then
```
Comment (WinterSolstice8) [inline scripts/globals/abilities/steal.lua:78]: I just checked on 3 different characters, one that just flagged the quest, one that finished it ages ago, and one that's never flagged it, all of them _only_ stole Quadav Stew from Zircon and Silver quadavs in Beadeaux (others untested, they didn't have any other stealable items listed other than the stew). Either they only have Quadav Stew, or the silver beastcoin is not stealable from them at a decent rate.

Is this check because the steal pool is wrong/missing, or just that one line in ffxiclopedia that _claims_ that "if you are on THF quest, you will always get a stew"?

Comment (ari-osm) [reply scripts/globals/abilities/steal.lua:78]: Was the stealing of stew on retail?  I always assumed they could drop both like the wikis say.

Yes that's what this check does.  It was already there, I just cleaned it up a little.

Comment (WinterSolstice8) [reply scripts/globals/abilities/steal.lua:78]: Yes, it was retail. As far as I can tell (without doing hundreds of samples) silver beastcoin is probably not a steal drop on the mobs that you can steal the Stew from in Beadeaux

Comment (ari-osm) [reply scripts/globals/abilities/steal.lua:78]: If that's the case we could rip out this whole section and remove the drops in the SQL.  I'm trying it on retail now and I'm 5/5 on stew as well.

Comment (WinterSolstice8) [reply scripts/globals/abilities/steal.lua:78]: If you want to rip out the drops I'd be fine with that, but we could punt it for a different PR as well. As you said this isn't something this PR introduced. Let me know what you want to do!

Comment (ari-osm) [reply scripts/globals/abilities/steal.lua:78]: If I end up doing it, I'd rather do it in a different PR.

I wonder if they changed it at some point.  The horror stories about the drop rate seem to stop about 2010.

**Review by WinterSolstice8 — APPROVED** [review]
That works for me, it's beyond the scope of this PR to change that anyway.

**Comment by WinterSolstice8** [comment]
Can we get this PR with a clean branch, without this commit? You should be able to just cherry-pick your two commits on top.
image

File: src/map/lua/lua_baseentity.cpp [hunk 2]
```diff
@@ -13475,13 +13475,21 @@ uint16 CLuaBaseEntity::getStealItem()
...
                 if (drop.DropType == DROP_STEAL)
                 {
-                    return drop.ItemID;
+                    Items.emplace_back(drop.ItemID);
                 }
             }
+
+            if (!Items.empty())
+            {
+                return Items[xirand::GetRandomNumber(Items.size())];
```
Comment (zach2good) [inline src/map/lua/lua_baseentity.cpp]: For passers-by: get random number doesn't include the max for integer types:
https://github.com/LandSandBoat/server/blob/7525508ad051b7ba40e46576d4a37ba5ee508501/src/common/xirand.h#L56

But it does for floating types, so be careful.

This usage is fine though.

File: src/map/lua/lua_baseentity.cpp [hunk 3]
```diff
@@ -13475,13 +13475,21 @@ uint16 CLuaBaseEntity::getStealItem()
 
         if (PDropList && !PMob->m_ItemStolen)
         {
+            // Steal item randomly selected from steal drop table
+            std::vector<uint16> Items;
```
Comment (zach2good) [inline src/map/lua/lua_baseentity.cpp]: Please make this var lowercase

File: src/map/lua/lua_baseentity.cpp (hunk 2 above)
Comment (zach2good) [reply src/map/lua/lua_baseentity.cpp]: Oh, we have a helper for this, use this instead:
https://github.com/LandSandBoat/server/blob/7525508ad051b7ba40e46576d4a37ba5ee508501/src/common/xirand.h#L95

**Comment by ari-osm** [comment]
Rogue commit removed and requested changes made.

**Review by zach2good — APPROVED** [review]

**Review by claywar — APPROVED** [review]
