### PR TITLE
Fix pets lost when warping

### LINKED ISSUE #3220: 🐛 Pets Lost when Warping
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

1. Be on Dragoon in a zone you can summon pets.
2. Call Wyvern.
3. Teleport through some method (e.g. Scroll of Instant Warp).
4. Move to a zone where pets are allowed.
5. Observe the wyvern did not return.

## Expected behavior

5. Wyvern should return.

### PR DESCRIPTION
**Pull request by DiscipleOfEris**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Make pets persist through warping in addition to other types of zoning.

Also fix console [critical] messages in debug mode related to jug pet code.

Note: I moved the `shouldPersistThroughZone()` pet helper function to `CCharEntity` rather than `CPetEntity`.

Fixes #3220

## Steps to test these changes

See #3220

Note: I am noticing an issue where the pet's stats are not preserved across zoning. I imagine this happens when `SaveCharStats()` is called *before* `setPetZoningInfo()`.

EDIT: Actually, I'm not able to reproduce the "pet's stats are not preserved across zoning". Maybe the stat update was delayed in one of my tests and that's why I thought it wasn't updating.

### CODE REVIEW

File: src/map/entities/charentity.cpp [hunk 1]
```diff
@@ -462,6 +462,32 @@ void CCharEntity::resetPetZoningInfo()
     petZoningInfo.jugSpawnTime = 0;
     petZoningInfo.jugDuration  = 0;
 }
+
+bool CCharEntity::shouldPetPersistThroughZoning()
+{
+    PET_TYPE petType;
+    auto     PPetEntity = dynamic_cast<CPetEntity*>(PPet);
+
+    if (PPetEntity == nullptr && !petZoningInfo.respawnPet)
```
Comment (WinterSolstice8) [inline src/map/entities/charentity.cpp:471]: Should this be an `||`?

File: src/map/entities/petentity.cpp [hunk 2]
```diff
@@ -286,8 +278,12 @@ void CPetEntity::loadPetZoningInfo()
         health.tp = static_cast<uint16>(master->petZoningInfo.petTP);
         health.hp = master->petZoningInfo.petHP;
         health.mp = master->petZoningInfo.petMP;
-        setJugDuration(master->petZoningInfo.jugDuration);
-        setJugSpawnTime(master->petZoningInfo.jugSpawnTime);
+
+        if (m_PetType == PET_TYPE::JUG_PET)
```
Comment (xkoredev) [inline src/map/entities/petentity.cpp:282]: nit: this check is not necessary as `petZoningInfo.jugDuration` will just contain default values for non jug pets

File: src/map/entities/charentity.cpp [hunk 3]
```diff
@@ -462,6 +462,32 @@ void CCharEntity::resetPetZoningInfo()
...
+    }
+    else // petZoningInfo.respawnPet == true
+    {
+        petType = petZoningInfo.petType;
+    }
+
+    return petType == PET_TYPE::WYVERN ||
+           petType == PET_TYPE::AVATAR ||
+           petType == PET_TYPE::AUTOMATON ||
+           (petType == PET_TYPE::JUG_PET && settings::get<bool>("map.KEEP_JUGPET_THROUGH_ZONING"));
```
Comment (xkoredev) [inline src/map/entities/charentity.cpp:488]: Thanks for adding the check. Should we add the `KEEP_JUGPET_THROUGH_ZONING` default value to settings/default/map.lua?

File: src/map/entities/charentity.cpp [hunk 4]
```diff
@@ -431,17 +431,17 @@ void CCharEntity::setPetZoningInfo()
             {
                 break;
             }
+            petZoningInfo.jugSpawnTime = PPetEntity->getJugSpawnTime();
```
Comment (xkoredev) [inline src/map/entities/charentity.cpp:434]: good catch. In theory this should be harmless for all pets, but I did add some xi_debug breaks so that was probably triggering it.

Comment (DiscipleOfEris) [reply src/map/entities/charentity.cpp:434]: Yes it was those debug breaks that I moved the jugpet code around for.

File: src/map/entities/charentity.cpp (hunk 1 above)
Comment (DiscipleOfEris) [reply src/map/entities/charentity.cpp:471]: This check will exit with `false` early if we have no pet *and* there's no stored pet (`respawnPet == true`).

If we have a pet, then we want to check it. If we have a stored pet, then again we want to check it. It's only when we have neither that we assume there's nothing to persist.

Hypothetically, if `respawnPet` is set then we already did `setPetZoningInf()` which should always be after `shouldPetPersistThroughZoning()` returned true, but I didn't want to assume that was always the case.

File: src/map/entities/charentity.cpp (hunk 3 above)
Comment (DiscipleOfEris) [reply src/map/entities/charentity.cpp:488]: I already added one a while ago. [settings/default/map.lua#L254](https://github.com/LandSandBoat/server/blob/base/settings/default/map.lua#L254)

File: src/map/entities/charentity.cpp (hunk 1 above)
Comment (WinterSolstice8) [reply src/map/entities/charentity.cpp:471]: Gotcha, thanks.

**Review by WinterSolstice8 — APPROVED** [review]

File: src/map/entities/petentity.cpp (hunk 2 above)
Comment (DiscipleOfEris) [reply src/map/entities/petentity.cpp:282]: I put that check there because of debug breaks throwing `[critical]` errors to console if the pet wasn't a jug pet. I agree the functions are harmless, but so long as we have the debug check inside those functions, we should keep the check here.

File: src/map/entities/charentity.cpp (hunk 3 above)
Comment (xkoredev) [reply src/map/entities/charentity.cpp:488]: Ah nice. I didn't know this or I would have used it. Thanks.

**Review by claywar — APPROVED** [review]
