### PR TITLE
Southern San d'Oria [S] NPC Audit

### LINKED ISSUE #423: everything branch, Mieuseloir_B_Enchelles.lua calling one of WotG 27 CS events instead of normal dialogue
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: everything branch

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Discovered on Canaria, running everything branch

Mieuseloir_B_Enchelles.lua (S. Sandoria (S), just outside of Lion Springs Tavern) is calling one of the CS from WotG 27 (The Scent of Battle) when you click on him.  When it gets to the black screen at the end, it just kinda hangs.

Had to call /shutdown to get out of it.

Client has not been updated to retail since the last time we synched up, so it does not appear to be a client versioning issue against the server or anything like that (yet).

### PR DESCRIPTION
**Pull request by Era-Lusiphur**
A rather heavy audit of Southern San d'Oria [S] NPCs. Many of these NPCs had hard-coded text IDs, some were firing cutscenes much later in WotG, and all sorts of other issues.

The various Freelance NPCs that we have spawned were left spawned. I added dialogue for some NPCs that were out in addition on Odin.

Added Exoroche from retail capture so that someone may later implement his quest.

Added some notations for most of them regarding which quests/missions they were in and deleted the NPC scripts that had no possible use beyond a DefaultAction.

While this doesn't bring the city to 100%, this definitely improves the situation a great deal.

Fixes #423

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

File: scripts/zones/Southern_San_dOria_[S]/DefaultActions.lua [hunk 1]
```diff
@@ -1,6 +1,70 @@
 local ID = require("scripts/zones/Southern_San_dOria_[S]/IDs")
 
 return {
+    ['_6eo'] = { text = ID.text.GATE_IS_LOCKED }, -- Yes, even though it's a door.
+    ['Achtelle'] = { text = ID.text.ACHTELLE_FROM_ADOULIN },
+    ['Adjutant'] = { text = ID.text.TOO_BUSY },
+    ['Aissaville'] = { event = 605 },
+    ['Andagge'] = { event = 53 },
```
Comment (claywar) [inline scripts/zones/Southern_San_dOria_[S]/DefaultActions.lua:8]: Would it be possible to format this list?  Probably something that can wait until we have all necessary mobs in it, but it looks like that may be close as well.

Comment (Era-Lusiphur) [reply scripts/zones/Southern_San_dOria_[S]/DefaultActions.lua:8]: There are still more conditional Freelance NPCs that either don't exist in the DB correctly yet or I didn't see up on retail to add.

**Review by claywar — APPROVED** [review]

File: scripts/zones/Southern_San_dOria_[S]/npcs/Saphiriance_TK.lua [hunk 2]
```diff
@@ -2,20 +2,34 @@
...
 -----------------------------------
 local entity = {}
 
 entity.onTrade = function(player, npc, trade)
 end
 
 entity.onTrigger = function(player, npc)
-    player:startEvent(450)
+    local allegiance =  player:getCampaignAllegiance()
+    local rank = getMedalRank(player)
```
Comment (claywar) [inline scripts/zones/Southern_San_dOria_[S]/npcs/Saphiriance_TK.lua]: Just noticed one more thing, could you comment out rank since its unused at this time?

Comment (Era-Lusiphur) [reply scripts/zones/Southern_San_dOria_[S]/npcs/Saphiriance_TK.lua]: Just nuked it for now.
