### PR TITLE
Fixing some battlefield interactions

### LINKED ISSUE #3332: 🐛 Entering a Battlefield After Party Engages Teleports Player to Empty Battlefield
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

Have two players, have the first player start a battlefield and the other player waits outside. Begin the battlefield with the first player. The second player then interacts with the entrance NPC and is teleported inside. The player will receive this message:

image

The second player will be unable to use the exit NPC to leave.

## Expected behavior

Print the message but leave the player outside of the battlefield.

### PR DESCRIPTION
**Pull request by jmcmorris**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

This fixes a few issues:

**If the player's party enters a battlefield with area 1 but never goes inside but logs out with the effect then when they log in they'll be incorrectly kicked out of the battlefield.**

Fix #3332 
The fix is to better track the player's battlefield entered status with effect's subpower. The first bit of the subpower is the entered status and everything after that is used for which battlefield area the player is in. This is done in order to know if the player needs to be ejected when logging in with a battlefield status effect.

I was partially doing this before but I failed to realize that the subpower was being set to the battlefield area when the status effect is created. This stored area value it not used from what I can see but I figured I'd preserve it just in case we do ever need it. 

**Character is able to reenter a locked battlefield if they leave after it has been locked**

This is easily fixed by removing the battlefield status effect when they leave a locked battlefield. This is how the character is prevented from entering a locked battlefield normally or at least should have...

**Character's battlefield status effect is not removed when a battlefield is locked**

This was simply an issue with `Battlefield:onBattlefieldStatusChange` trying to take an extra parameter. I had forgotten I had even fixed this otherwise I would have put it into its own commit. Whoops!

## Steps to test these changes

Go to a battlefield with two characters and try the scenarios described above.

### CODE REVIEW

File: src/map/battlefield_handler.cpp [hunk 1]
```diff
@@ -223,8 +225,10 @@ uint8 CBattlefieldHandler::LoadBattlefield(CCharEntity* PChar, const Battlefield
 
     if (!PChar->StatusEffectContainer->GetStatusEffect(EFFECT_BATTLEFIELD))
     {
+        // The first bit of the subpower is reserved for if the player has entered the battlefield or not
+        uint16 subpower = PBattlefield->GetArea() << 1;
```
Comment (TeoTwawki) [inline src/map/battlefield_handler.cpp]: I seriously dislike setting this precedent, or using this pattern at all especially for this. Bitpacking/shifting to handle things in an effect field don't sit well with me.

I'd rather do something far messier tbh. 3 (4?) rewrites ago, players would get "registered" in the core to a battlefield copy on entry for its duration. I forget the exact code involved in that version of things.

Comment (TeoTwawki) [reply src/map/battlefield_handler.cpp]: I'm genuinely curious: How terribad would it be to add new things to the battlefield object to toggle per copy+person?

Comment (jmcmorris) [reply src/map/battlefield_handler.cpp]: What we need this for is when the battlefield doesn't exist anymore and we need to kick the player out. Some alternatives include:
- Scrap the area since we aren't actively using it and allow the subpower to simply be entered or not (1 or 0).
- Use a charvar that we set when they enter and clear when they leave. This honestly wouldn't be too bad since it'll be cleared out when they log back in.

Comment (claywar) [reply src/map/battlefield_handler.cpp]: Instead of storing this on the player in the effect, I wonder if it might be better to track this in the battlefield object itself, since _I think_ we already know they're registered?

Comment (claywar) [reply src/map/battlefield_handler.cpp]: The other option is that we could potentially use status effect Tier as well

Comment (TeoTwawki) [reply src/map/battlefield_handler.cpp]: > What we need this for is when the battlefield doesn't exist anymore and we need to kick the player out. Some alternatives include:
> 
> * Scrap the area since we aren't actively using it and allow the subpower to simply be entered or not (1 or 0).
> * Use a charvar that we set when they enter and clear when they leave. This honestly wouldn't be too bad since it'll be cleared out when they log back in.

one or more of the previous incarnations of bcnm systems used to do the charvar. to me it'd be better than bitpacking this into the effect. as for the battlefield not existing anymore, couldn't we use that in itself as a stand in - use the value in the object when the object does exist, use the fact it doesn't exist when it doesn't to mean "false" as well?

using tier as an in/out  (0 or 1) also is more appealing than using subpower here, if we go a 1 or 0 route

Comment (jmcmorris) [reply src/map/battlefield_handler.cpp]: The reason we cant store this on the battlefield object itself is because the character is logging out for an unknown amount of time. We wouldn't want to keep the battlefield instance around and even if we tried doing that there is always the scenario that the server goes down.

Using the tier looks easy enough and is a great idea! That's what I'm going to roll with.

Comment (TeoTwawki) [reply src/map/battlefield_handler.cpp]: > The reason we cant store this on the battlefield object itself is because the character is logging out for an unknown amount of time. We wouldn't want to keep the battlefield instance around and even if we tried doing that there is always the scenario that the server goes down.

Yes but if the battlefield ceased to exist, we wouldn't need to know if a player can enter it anymore - we can treat that as the same as "no you can't" if we check for that condition (nil/null) see what i am saying?

Comment (TeoTwawki) [reply src/map/battlefield_handler.cpp]: Tier is fine, as long as we ain't bitpacking I'm content

Comment (jmcmorris) [reply src/map/battlefield_handler.cpp]: > 
> Yes but if the battlefield ceased to exist, we wouldn't need to know if a player can enter it anymore - we can treat that as the same as "no you can't" if we check for that condition (nil/null) see what i am saying?

This is for the scenario that the player has logged out/disconnected while **inside** the battlefield. In this case we need to kick the player out. However, if they didn't enter but have the battlefield effect then we don't want to kick them out.

**Comment by jmcmorris** [comment]
I reworked the entered state tracking to be on the battlefield status effect tier.

File: src/map/battlefield_handler.cpp (hunk 1 above)
Comment (TeoTwawki) [reply src/map/battlefield_handler.cpp]: > This is for the scenario that the player has logged out/disconnected while inside the battlefield. In this case we need to kick the player out. 

this is still "battlefield ceased to exist, you don't belong here /kick"

> However, if they didn't enter but have the battlefield effect then we don't want to kick them out.

????

how exactly do you have the effect and be inside a battlefield that ceased to exist

Comment (jmcmorris) [reply src/map/battlefield_handler.cpp]: Log out inside a battlefield and when you log back in you'll still have the effect

Comment (TeoTwawki) [reply src/map/battlefield_handler.cpp]: > Log out inside a battlefield and when you log back in you'll still have the effect

which would be an invalid one (because empty = ends) and kick them if solo. if they weren't solo, it'd still exist with someone inside it.

**Comment by panicstevenson** [comment]
Tested this out and it works great! I have two things and both are extremely minor.

1. Is there any way to retrofit this to battlefields not currently on the framework as a stopgap? I think it's fine if the answer is "convert it to the new framework".
2. If a player in a party is outside of the battlefield but still in the selection window when the rest of the party engages and the player loses the battlefield buff the player can still get teleported into the zone but will receive the message that they were unable to zone in, leaving the player stranded. The player in this scenario is obviously playing with fire, but I wonder if some of https://github.com/AirSkyBoat/AirSkyBoat/pull/2061 can land to add an Event Skipped when a player loses their confrontation flag while in a menu in the future for a GM-free experience.

**Review by panicstevenson — APPROVED** [review]

**Comment by jmcmorris** [comment]
> Tested this out and it works great! I have two things and both are extremely minor.
> 
> 1. Is there any way to retrofit this to battlefields not currently on the framework as a stopgap? I think it's fine if the answer is "convert it to the new framework".
> 2. If a player in a party is outside of the battlefield but still in the selection window when the rest of the party engages and the player loses the battlefield buff the player can still get teleported into the zone but will receive the message that they were unable to zone in, leaving the player stranded. The player in this scenario is obviously playing with fire, but I wonder if some of [Stop Players from Interacting with Event Menus and Teleporters when Damaged AirSkyBoat/AirSkyBoat#2061](https://github.com/AirSkyBoat/AirSkyBoat/pull/2061) can land to add an Event Skipped when a player loses their confrontation flag while in a menu in the future for a GM-free experience.

1. Should be possible to go through the entry npcs such as Burning Circles and add to the event finished `player:setEnteredBattlefield(true)` for the right event, `32000`.
2. Thanks! I'm fully aware of this. I made #3334 yesterday to track this as I'm hoping to get a capture to see exactly how retail handles it.

**Review by claywar — APPROVED** [review]
