### PR TITLE
Fix Foreseer Oramix placeholders

### LINKED ISSUE #3634: 🐛 NM Foreseer Oramix cannot spawn
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows10

## Branch affected by issue

`base`

## Steps to reproduce

1. Kill Goblin Alchemist PHs in Ifrit's Cauldron. (Or better yet just check their code)
2. Observe Foreseer Oramix never spawns

## Expected behavior

2. Foreseer Oramix should spawn off the Goblin Alchemist placeholders

The Goblin Alchemists never had their PH code added to allow them to spawn Foreseer Oramix.

### PR DESCRIPTION
**Pull request by DiscipleOfEris**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

The rest of the placeholder scaffolding is there, but the last step was never added in.

Choice of 5% and 1hr cooldown are arbitrary, based on the other lottery NMs in the zone.

Fixes #3634 

## Steps to test these changes

1. Kill the 3 Goblin Alchemists PHs until Foreseer Oramix appears (or `!despawnmob` and `!spawnmob` repeatedly).

### CODE REVIEW

**Review by TeoTwawki — APPROVED** [review]
Well, I suppose I should go code his drop's additional effect soon.

**Review by Xaver-DaRed — APPROVED** [review]

File: scripts/zones/Ifrits_Cauldron/mobs/Goblin_Alchemist.lua [hunk 1]
```diff
@@ -2,12 +2,18 @@
 -- Area: Ifrit's Cauldron
 --  Mob: Goblin Alchemist
 -----------------------------------
+local ID = require("scripts/zones/Ifrits_Cauldron/IDs")
 require("scripts/globals/regimes")
+require("scripts/globals/mobs")
```
Comment (Xaver-DaRed) [inline scripts/zones/Ifrits_Cauldron/mobs/Goblin_Alchemist.lua:7]: Not game breaking, but, I dont think this concrete require is needed.

Comment (TeoTwawki) [reply scripts/zones/Ifrits_Cauldron/mobs/Goblin_Alchemist.lua:7]: the lotto pop mechanics are in there, so its better to have it for clarity
