### PR TITLE
[core] Adds "too far" for player and trust WS, fix 0 delay TP moves generating an empty action packet, add some more safety

### LINKED ISSUE #1877: Value Missing in Action Packet
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

Steps to reproduce: (Omicron server)

METHOD 1
1. Load game in Windower with the Battlemod addon loaded
2. Summon trusts (I used Halver/Ayame/Valaineral/Excenmille, though this has happened when I had no trusts out)
3. Fight enemies and this error should trigger roughly once every 3-5 minutes, often within 1~3 seconds of engaging.

METHOD 2
1. Load game in Windower with the Battlemod addon loaded
2. Accumulate 1000 TP
3. Engage an enemy from 6~25 yalms
4. Attempt a WS from out of range
5. This triggers two chat messages. 1) WS attempt. 2) Mob out of range. Either one could be the trigger
6. That should trigger the error in the console

NOTE: The error printed in the console is "_Lua runtime error: battlemod/parse_action_packet.lua:709: attempt to index field '?' (a nil value)_"
Line 709: _local msg_ID = act.targets[1].actions[1].message_

## Expected behavior

Apparently a portion of the action packet is expected to be defined that is undefined in LSB.

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Add "too far" messages for players/trusts that become out of range after readying a WS.
Fix 0 delay mob TP move such as Shantotto II generating an empty action packet.
Add some safety to mobentity

Fixes #1877
## Steps to test these changes

Too far:

- !tp 1000
- use WS when out of range
- receive "too far" message

repeat the same except for a trust like Ayame, and give yourself and her 1k tp, engage a raptor/tiger and run backwards to try to force her to use a WS, she should trigger out of range if you're lucky.

empty action packet fix:

- load battlemod on windower
- summon Shantotto II, have her melee something
- don't get "nil" warnings in log

### CODE REVIEW

File: src/map/ai/states/attack_state.cpp [hunk 1]
```diff
@@ -65,7 +65,10 @@ bool CAttackState::Update(time_point tick)
             action_t action;
             if (m_PEntity->OnAttack(*this, action))
             {
-                m_PEntity->loc.zone->PushPacket(m_PEntity, CHAR_INRANGE_SELF, new CActionPacket(action));
+                if (action.actiontype != ACTION_NONE) // CMobEntity::OnAttack(...) generates it's own action and sends it there, and that leaves this action.actionType = 0, which is never valid. Skip sending the packet.
```
Comment (TeoTwawki) [inline src/map/ai/states/attack_state.cpp]: Mind putting the comment on its own line above the `if` ? it became a wide line

Comment (TeoTwawki) [reply src/map/ai/states/attack_state.cpp]: the other lines were ok, just this one tripped the right/left scrollbar

**Review by TeoTwawki — APPROVED** [review]

File: src/map/entities/trustentity.cpp [hunk 2]
```diff
@@ -58,7 +58,7 @@ CTrustEntity::CTrustEntity(CCharEntity* PChar)
 void CTrustEntity::PostTick()
 {
     // NOTE: This is purposefully calling CBattleEntity's impl.
-    // TODO: Calling a grand-parent's impl. of an overrideden function is bad
+    // TODO: Calling a grand-parent's impl. of an overidden function is bad
     CBattleEntity::PostTick();
```
Comment (zach2good) [inline src/map/entities/trustentity.cpp:62]: https://dictionary.cambridge.org/dictionary/english/overridden

File: src/map/entities/mobentity.cpp [hunk 3]
```diff
@@ -286,6 +286,17 @@ bool CMobEntity::CanRoam()
...
+{
+    CMobController* mobController = dynamic_cast<CMobController*>(PAI->GetController());
+
+    if (mobController)
+    {
+        mobController->TapDeaggroTime();
+    }
+}
+
+
```
Comment (zach2good) [inline src/map/entities/mobentity.cpp]: Double line break

**Review by zach2good — APPROVED** [review]
Nice work 👍

File: src/map/entities/trustentity.cpp (hunk 2 above)
Comment (WinterSolstice8) [reply src/map/entities/trustentity.cpp:62]: curses...

**Review by claywar — APPROVED** [review]
