### PR TITLE
Retail accurate AH listings

### LINKED ISSUE #3856: 🐛 AH sorting broken
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Windows Server 2019

## Branch affected by issue 
`base`

## Steps to reproduce
Browse rings at AH, notice items aren't sorted. Choose to sort by level. notice rings STILL aren't sorted, be confused try to reset then re-sort, exit and re-enter AH, give up after a few minutes. Note that the order DOES change, just not correctly.

## Expected behavior
See highest level rings at the top, lower level rings below.

### PR DESCRIPTION
**Pull request by cocosolos**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Track which items have been listed on the AH using a new protected table
and trigger. Only show these items in the AH by default. This is controlled
by the `search.OMIT_NO_HISTORY` setting and is now on by default.

Run the following query to populate the new table using your existing
auction house history:
```
INSERT IGNORE INTO auction_house_items(itemid)
SELECT itemid FROM auction_house
GROUP BY itemid;
```

Fixes #3856

## Steps to test these changes

With empty auction_house and auction_house_items tables:
Make sure OMIT_NO_HISTORY is true in your search.lua settings file.
Search any category on AH, should all be empty.
List something on AH, it now appears in searches.
Remove listing, item still shows in searches.
Change OMIT_NO_HISTORY to false.
Search any category on AH, should all be fully populated.

### CODE REVIEW

File: settings/default/search.lua [hunk 1]
```diff
@@ -11,8 +11,8 @@ xi.settings = xi.settings or {}
 
 xi.settings.search =
 {
-    -- Omit items with no buy history from auction house results
-    OMIT_NO_HISTORY = false,
+    -- Omit items with no listing history from auction house results
+    OMIT_NO_HISTORY = true,
```
Comment (TeoTwawki) [inline settings/default/search.lua]: despite being technically retail, we probably want to default it off anyway if only because ppl who didn't read/notice it will then think its bugged

Comment (cocosolos) [reply settings/default/search.lua]: I agree people probably expect the false behavior but I'm conflicted because I think settings should default to retail-like. Existing servers won't notice the difference if they have this set already in their copy of the settings file and it's one of only a few settings for the search server so would be hard to miss.

Comment (TeoTwawki) [reply settings/default/search.lua]: Normally we want all default retail. I think this and thinking show all was better than retail was the main reasoning behind defaulting off in the PR it came in on. I'm ok with whatever other devs prefer here, but thought it worth mentioning since we had it off in here already.

Comment (TeoTwawki) [reply settings/default/search.lua]: > one of only a few settings for the search server so would be hard to miss.

You would think, but people often don't notice when new settings land in the default files to add them to their edited files and wind up with whatever the default setting behavior is (or an error). Even catches me now and then after I pull on my testbed not realizing how long its been. One of the few drawbacks of making it so nobody is accidently committing their settings anymore :)

Comment (cocosolos) [reply settings/default/search.lua]: I wanted to squash that style commit so I changed the default setting back to false since I was already rebasing. If you guys decide you want it the other way just let me know and I'll change it back np.

**Review by Xaver-DaRed — APPROVED** [review]
