### PR TITLE
Fixing various issues with Sagheera

### LINKED ISSUE #2648: 🐛 [NPC] Sagheera Port Jeuno, incorrect behavior and missing options
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce
The NPC Sagheera in Port Jeuno will sell the key item Cosmo-Cleanse to players with zero COP mission progression. 
The NPC Sagheera will accept ancient beastcoins and exchange them for items to the player with zero COP mission progress. 
The NPC Sagheera will accept ancient beastcoins but, there is no options to return the coins to the player.
The NPC Sagheera will not accept unused limbus chips in exchange for ancient beastcoins.

## Expected behavior
Buying the key item Cosmo-Cleanse and exchanging ancient beastcoins should be locked behind completing COP mission 7-5.
The NPC Sagheera should have an option to return stored ancient beastcoins to the player.
The NPC Sagheera should exchange unused limbus chips for ancient beastcoins.

## Sources of fact
https://www.bg-wiki.com/ffxi/Sagheera
https://ffxiclopedia.fandom.com/wiki/Sagheera
http://wiki.ffo.jp/html/3758.html
http://wiki.ffo.jp/html/27098.html
https://forum.square-enix.com/ffxi/threads/24154

ffxi_2022 09 03_23 18 52

### PR DESCRIPTION
**Pull request by jmcmorris**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Fixes #2648
Adds CoP check, proper menu display, ability to retrieve stored ABCs and ability to trade chips for ABCs
In order to implement trading chips properly I added in the ability to get a player's trade container outside of `onTrade`. The client does send the quantity of ABCs back to the server so we could technically just use that but then we open ourselves up to an exploit so instead I verify the trade.

## Steps to test these changes

```
!pos -3 0.1 -9 246
!additem 1875 10
!additem 1904
!additem 1988
```

Interact with Sagheera in all the various ways

### CODE REVIEW

File: scripts/zones/Port_Jeuno/npcs/Sagheera.lua [hunk 1]
```diff
@@ -332,15 +362,53 @@ entity.onTrigger = function(player, npc)
     then
         player:startEvent(313)
 
-    -- DEFAULT DIALOG (menu)
+    -- Prevent interaction until player has progressed through COP enough
+    elseif player:getCurrentMission(xi.mission.log_id.COP) < xi.mission.id.cop.GARDEN_OF_ANTIQUITY then
+        player:showText(npc, ID.text.SAGHEERA_NO_LIMBUS_ACESS)
```
Comment (WinterSolstice8) [inline scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: `ACESS` -> `ACCESS`

File: scripts/zones/Port_Jeuno/IDs.lua [hunk 2]
```diff
@@ -43,6 +43,7 @@ zones[xi.zone.PORT_JEUNO] =
         CONQUEST                      = 7404, -- You've earned conquest points!
         SAGHEERA_MAX_ABCS             = 8045, -- I apologize, but I cannot take any more <item> from you.
         SAGHEERA_LACK_ABCS            = 8046, -- You have collected the proper materials, but unfortunately you lack the required amount of <item> for payment.
+        SAGHEERA_NO_LIMBUS_ACESS      = 8054, -- I came from the Near East to peddle my wares. I heard that there are simply hordes of gullib--err, that is, I have heard of the great adventurers that roam this land, and wish to be of service to them...
```
Comment (WinterSolstice8) [inline scripts/zones/Port_Jeuno/IDs.lua]: `ACESS` -> `ACCESS`

File: scripts/zones/Port_Jeuno/npcs/Sagheera.lua [hunk 3]
```diff
@@ -332,15 +362,53 @@ entity.onTrigger = function(player, npc)
...
+
+        -- DEFAULT DIALOG (menu)
     else
         -- event parameters
+
+        local storedABCs = player:getCurrency("ancient_beastcoin")
+        local playerSagheera = player:getCharVar("Sagheera")
```
Comment (TeoTwawki) [inline scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: is it essential this be a charvar and not a localvar, are we needing this to persist beyond the event? sort of skimming atm from my dayjob

**Review by WinterSolstice8 — CHANGES_REQUESTED** [review]

File: scripts/zones/Port_Jeuno/npcs/Sagheera.lua (hunk 3 above)
Comment (jmcmorris) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: I do believe it needs to be a charvar as it handles the first time you talk to her she has special dialog to sell you a cosmo cleanse and then she gives you a long explanation in other places that I'm fairly certain only happen once ever and not every time you zone.

Comment (claywar) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: To avoid a forever charvar, we could set a value when completing the requisite mission, and then reset to 0

Comment (TeoTwawki) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: normally what we do for "1st time dialog" vars if have chars born with a var set to 1 on create, then delete it on talking (see moghouse explanation event). server ops would then have to back fill it if they care to fort old players.

we've had some internal discussion about moving all those things to their own sperate storage mask (and the pain of then having an enum for them).

is that the only reason tho?

Comment (jmcmorris) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: Ok, so I'll set this value with all important bits when the player finishes the requisite mission and then remove the bits as the player performs the necessary interactions. Sound right?

File: scripts/zones/Port_Jeuno/npcs/Sagheera.lua [hunk 4]
```diff
@@ -414,4 +497,30 @@ entity.onEventFinish = function(player, csid, option)
     end
 end
 
+local handleTradeChipEvent = function(player, option)
+    local trade = player:getTrade()
+    if (npcUtil.tradeSetInList(trade, tier1Chips) and npcUtil.giveItem(player, { { xi.items.ANCIENT_BEASTCOIN, tier1ChipValue } })) then
```
Comment (claywar) [inline scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: No need for outer parens here

File: scripts/zones/Port_Jeuno/npcs/Sagheera.lua (hunk 3 above)
Comment (claywar) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: Yep, sounds good, that way we don't clutter the db after the player has progressed far enough

Comment (TeoTwawki) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: does she do multiple of those one offs? it may be justified as a forever var if so

File: scripts/zones/Port_Jeuno/npcs/Sagheera.lua [hunk 5]
```diff
@@ -251,9 +251,33 @@ local abcShop =
     [20] = { item =  2127, abc =  75 }, -- metal_chip
 }
 
+-----------------------------------
+-- trades chips for ancient beastcoins
+-----------------------------------
+local tier1Chips =
```
Comment (claywar) [inline scripts/zones/Port_Jeuno/npcs/Sagheera.lua:257]: Since the same logic seems to happen twice for both of these tables, could combine into one with the item as key, with its chipValue as value

File: scripts/zones/Port_Jeuno/npcs/Sagheera.lua (hunk 3 above)
Comment (TeoTwawki) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: > Ok, so I'll set this value with all important bits when the player finishes the requisite mission and then remove the bits as the player performs the necessary interactions. Sound right?

yeah :+1:

File: scripts/zones/Port_Jeuno/npcs/Sagheera.lua (hunk 5 above)
Comment (jmcmorris) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua:257]: That's what I initially did but I use these tables for checking the trade.
https://github.com/LandSandBoat/server/pull/2765/files#diff-0bab3dbe20460986828316156b5e730a1831f9237a333abc455b87e8a97101e5R316

File: scripts/zones/Port_Jeuno/npcs/Sagheera.lua (hunk 4 above)
Comment (jmcmorris) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: Whoops, I was starting to merge these two conditions with an or but they're so lengthy ; ;

Comment (claywar) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua]: For length, might want to consider our multi-line style as well:
```
if
    condition1 and
    not condition2
then

end
```

**Review by WinterSolstice8 — APPROVED** [review]

**Comment by WinterSolstice8** [comment]
LGTM, but pending approval from others for quest/db stuff I don't know much about

**Review by claywar — APPROVED** [review]

File: scripts/zones/Port_Jeuno/npcs/Sagheera.lua [hunk 6]
```diff
@@ -332,15 +366,52 @@ entity.onTrigger = function(player, npc)
...
+        player:showText(npc, ID.text.SAGHEERA_NO_LIMBUS_ACCESS)
+
+        -- DEFAULT DIALOG (menu)
     else
         -- event parameters
+
+        local storedABCs = player:getCurrency("ancient_beastcoin")
+        local playerSagheera = player:getCharVar("SagheeraInteractions")
+        -- bitfield of menu options
+        local menu = 0
```
Comment (claywar) [inline scripts/zones/Port_Jeuno/npcs/Sagheera.lua:380]: Mulling over a way to simplify this logic for menu param, but works for now.  Could possible reduce this by setting the initial value of the charvar to the correct bit positions for those 3 bits, and then apply some and-logic for the rest

Comment (jmcmorris) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua:380]: That's clever. Before inverting it we could have just done a bit.band but I don't think we can anymore.

Comment (TeoTwawki) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua:380]: from previous convo, I had assumed you were going to split the 1 time use flags off from your main mask in this pr. they don't have to be together really, and I thought that would allow you to use charvars for the one time use and get/setLocalVar on the rest

Comment (jmcmorris) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua:380]: There are 3 one time uses for the `SagheeraInteractions` charvar.

1. First time buying a cosmo cleanse (bit 0)
2. First time the player selects "Just wanted to Chat" (bit 1)
3. First time the player selects the Relic Restoration option (bit 2)

I don't think any of these can be made into a localvar as it'd make the player repeat the action that usually involves a lengthy explanation.

Comment (TeoTwawki) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua:380]: wasn't suggesting those become localvar, was suggesting the parts that are not those, not be charvar and not be in the same mask with them

unless I am misreading everything is all in one charvar atm

Comment (TeoTwawki) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua:380]: talked to JMC in discord, I misread something and my comments can be disregarded here

Comment (claywar) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua:380]: If I read correctly, the least significant nibble is the one you're using for those 3 bits (0b1011), where bit 2 is always set to true in the script.

Therefore, I think you could xor that nibble, and then tack on the other items in the upper nibble

Comment (jmcmorris) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua:380]: How does the latest 2* commits look? Is that what you're thinking?

Comment (claywar) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua:380]: Using a web version right now to test out ideas, is bit 2 inverted with an 11 param?  Might need to provide it 0xF

Comment (jmcmorris) [reply scripts/zones/Port_Jeuno/npcs/Sagheera.lua:380]: bit 2 is now conditionally set if you have stored abcs and will be set after use do the xor to set the initial menu state.
