### PR TITLE
[Nation Missions] Convert San d'Oria Rank 3, and all nations Rank 4 and 5

### LINKED ISSUE #377: getMissionMask does not account for not needing rank points for missions in previous ranks
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Currently, getMissionMask does not account for previously completed ranks not requiring rank points.  Fixed in #373 with the following logic:
```
            missionId >= lastRequiredMission and
            (
                rank > getRequiredRank(missionId) or
                (
                    rank == getRequiredRank(missionId) and
                    getMissionRankPoints(player, missionId)
                )
            )
            and
            (
                lastRequiredMission < 0 or
                player:hasCompletedMission(nation, lastRequiredMission)
            )
``` 

Raising this issue for tracking.

### LINKED ISSUE #395: getRequiredRank has off by one error for mission ids >= 14
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

getRequiredRank currently has an off by one error for mission ids >= 14.  Fixed by #394 with the following code for the function:
```
local function getRequiredRank(missionId)
    local requiredRank = 0

    if
        missionId <= 2
    then
        requiredRank = math.floor(missionId / 3) + 1
    elseif missionId >= 10 and missionId <= 12 then
        requiredRank = 3
    elseif missionId == 13 then
        requiredRank = 4
    elseif missionId >= 14 then
        requiredRank = math.floor((missionId - 14) / 2) + 5
    else
        requiredRank = 2
    end

    return requiredRank
end
```
Raising this issue for tracking.

### PR DESCRIPTION
**Pull request by claywar**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

* Converts San d'Oria Rank 3 Missions (3-1 ~ 3-3) to Interaction Framework
* Converts All Rank 4 Missions to Interaction Framework
* Converts Mysteries of Beadeaux I and II, along with Crest of Davoi to Interaction Framework

TODO: Convert Rank 5 as well so that these changes are non-breaking

### CODE REVIEW

File: scripts/missions/sandoria/3_1_Infiltrate_Davoi.lua [hunk 1]
```diff
@@ -0,0 +1,312 @@
...
+
+                [2012] = function(player, csid, option, npc)
+                    mission:complete(player)
+                end,
+            },
+        },
+
+        [xi.zone.DAVOI] =
+        {
+            -- TODO: Rename this NPC to be a non-special character, also separate these duplicate NPCs
```
Comment (zach2good) [inline scripts/missions/sandoria/3_1_Infiltrate_Davoi.lua:258]: Good god yes please!

**Review by zach2good — APPROVED** [review]
You're doing god's work here. There is no way that a few things don't break along the way, but this is a huge step in the right direction :+1:
