### PR TITLE
[CPP] Fix map crash when counting trusts

### LINKED ISSUE #5844: 🐛 Map.exe crash when party member zones.
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base` (Unmodified)

## Steps to reproduce

1. Make 2 characters on 2 accounts (Or have a friend help test)
2. Have 2 characters make a party. Have one of them zone in or out of the zone the other is in.
3. See that the server crashes.

image
image

[xi_map.exe_29-5_6-0-35.dmp](https://github.com/LandSandBoat/server/files/15484689/xi_map.exe_29-5_6-0-35.dmp)

## Expected behavior

Server should not crash.

### PR DESCRIPTION
**Pull request by ampitere**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Fixes a map crash due to party leader being null when they are initially zoning. Resolves https://github.com/LandSandBoat/server/issues/5844

## Steps to test these changes

1. Make a group with 2 or more
2. Be in the same zone together and have the party leader zone out and in

### CODE REVIEW

File: src/map/party.cpp [hunk 1]
```diff
@@ -335,7 +335,17 @@ void CParty::RemoveMember(CBattleEntity* PEntity)
                     }
                 }
 
-                auto trustCount = static_cast<CCharEntity*>(m_PLeader)->PTrusts.size();
+                size_t trustCount = 0;
+                if (m_PLeader != nullptr)
+                {
+                    std::vector<CTrustEntity*> PTrusts = static_cast<CCharEntity*>(m_PLeader)->PTrusts;
```
Comment (zach2good) [inline src/map/party.cpp]: No need to make a copy of the trusts vector here, same for below.

trustCount is init'd as zero:
```
size_t trustCount = 0;
```

The size of a vector is zero when it's empty.

So you can simplify this block (and below) with something like:

```cpp
trustCount = static_cast<CCharEntity*>(m_PLeader)->PTrusts.size();
```

Comment (ampitere) [reply src/map/party.cpp]: Simplified both this line and 867.

**Review by zach2good — APPROVED** [review]
