### PR TITLE
[core] Add nullptr check and error message to CLuaZone

### LINKED ISSUE #2577: 🐛 Mother Globe's LUA crashes the server when zoning into The Shrine of Ru'Avitau
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## Branch affected by issue 

`base`

## Steps to reproduce

1. Pull the LSB base branch from the repository.
2. Compile the server.
3. Load the server.
4. Enable debugging in Visual Studios and attach it to xi_map.exe.
5. Type `!zone 178`.
6. Observe xi_map.exe crashing on zone in.

## Expected behavior

Players zoning to The Shrine of Ru'Avitau should not be crashing the server.
Mother Globe attempting to set positions for the Slave Globes should not be crashing the server.

Visual Studio generated the following debugging information:
devenv_5ggDQRA2lW

Mob information was obtained from the `DoRoamTick` function.

The CNavMesh `validPosition` function is causing an exception due to a read access violation.
devenv_LfEpHTKx1h

Commenting out the `calculateValidSlaveGlobePositions` function in scripts\zones\The_Shrine_of_RuAvitau\mobs\Mother_Globe.lua caused errors in the LUA but did not cause the server to crash when a player zoned into The Shrine of Ru'Avitau.
https://github.com/LandSandBoat/server/blob/a1de81fca66f71e525a36eba58eed4c46ce5654e/scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua#L48-L69

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

Adds some nullptr check for navmesh to prevent crashes
Fixes #2577

## Steps to test these changes

Remove your navmeshes, follow instructions at #2577

### CODE REVIEW

File: src/map/lua/lua_zone.cpp [hunk 1]
```diff
@@ -200,7 +200,15 @@ bool CLuaZone::isNavigablePoint(const sol::table& point)
...
     // clang-format on
 
-    return m_pLuaZone->m_navMesh->validPosition(position);
+    if (m_pLuaZone->m_navMesh)
+    {
+        return m_pLuaZone->m_navMesh->validPosition(position);
+    }
+    else
+    {
+        ShowError("CLuaZone::isNavigablePoint(): m_pLuaZone->m_navMesh is nullptr! Is your navmesh git submodule up to date?");
```
Comment (TeoTwawki) [inline src/map/lua/lua_zone.cpp]: Those of us not using a navmesh don't want our logs spammed with this every time the function is called man.

**Review by TeoTwawki — APPROVED** [review]

File: src/map/lua/lua_zone.cpp (hunk 1 above)
Comment (WinterSolstice8) [reply src/map/lua/lua_zone.cpp]: It appears I did not understand it was supposed to be optional, my bad!

**Review by claywar — APPROVED** [review]

**Review by zach2good — APPROVED** [review]
