### PR TITLE
[lua] Port ASB JoL

### LINKED ISSUE #7039: JoL Spawning by trading items - Working but code is commeted out
Why is the mechanics to spawn Jailer of Love comment out? I tested the code and it works well. I didn't find a reason for this change in the comments. Did I miss something? Did anything went wrong when you took the code over from the previouse project?

Check this script:
https://github.com/LandSandBoat/server/blob/base/scripts/zones/AlTaieu/npcs/qm_jailer_of_love.lua

I removed line 12 and 25, and it works flawless.

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Backports a more functional JoL from ASB
Closes #7039
## Steps to test these changes

Fight JoL, see eveything is normal

### CODE REVIEW

**Comment by WinterSolstice8** [comment]
Drafting for CI

**Review by zach2good — APPROVED** [review]
Slap an experimental flag on here and make it drop no loot 👍

File: scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua [hunk 1]
```diff
@@ -20,76 +22,283 @@ local minionGroup =
...
+local spellLists =
+{
+    [1] = 5025, -- Fire List
+    [2] = 5026, -- Ice List
+    [3] = 5027, -- Wind List
+    [4] = 5028, -- Earth List
+    [5] = 5029, -- Ltng List
+    [6] = 5030, -- Water List
+    [7] = 5024, -- Light List
+    [8] = 5031, -- Dark List
```
Comment (Xaver-DaRed) [inline scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua]: This indexes are xi.element.NAME

We will need to make sure this IDs are defined in the DB aswell

File: scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua [hunk 2]
```diff
@@ -20,76 +22,283 @@ local minionGroup =
...
+}
+
+-- Animations, action IDs and elemental absorb mods are directly mapped to eachother per retail caps
+-- in the "standard" order, Fire Ice Wind Earth Thunder Water Holy Dark
+local eleAbsorbModID      = { 459, 460, 461, 462, 463, 464, 465, 466 }
```
Comment (Xaver-DaRed) [inline scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua]: This concrete line is unnecesary, I think. We have the element table inside combat folder for them, following the same elemental order

File: scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua [hunk 3]
```diff
@@ -20,76 +22,283 @@ local minionGroup =
...
+    mob:setLocalVar('elementAbsorb', os.time() + 120)
+    mob:setLocalVar('pop_pets', os.time() + 150) -- wait 2.5 minutes until spawning initial mobs
+    mob:setLocalVar('currentAbsorb', math.random(#eleAbsorbModID)) -- pick a random element to absorb after engaging
+    mob:setSpellList(spellLists[mob:getLocalVar('currentAbsorb')])
+    mob:setMod(eleAbsorbModID[mob:getLocalVar('currentAbsorb')], 100)
 end
 
 entity.onMobFight = function(mob, target)
-    -- reduce regen after nine Xzomits and Hpemdes are killed
+    mob:setAnimationSub(2)
```
Comment (Xaver-DaRed) [inline scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua]: This seems weird. This would mean we are constantly setting its animationSub. We are already doing that onMobEngaged and I dont see it being changed anywhere else

**Comment by WinterSolstice8** [comment]
> Slap an experimental flag on here and make it drop no loot 👍

This thing is fully featured and complete (I've fought it several times on Horizon and the final changes to make it retail accurate for the skill swaps/animations (packet stuff) were from me)
EXCEPT -- all Yovras don't have Flourescence and Torrential Torment as of now. There's really no reason to make it experimental.

There's also one bug that I intend to fix (standback doesn't work correctly for JoL, but that will come in a later commit)

File: scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua (hunk 1 above)
Comment (WinterSolstice8) [reply scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua]: updated to use real spell lists

File: scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua (hunk 2 above)
Comment (WinterSolstice8) [reply scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua]: removed and replaced wit the combat definition

File: scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua (hunk 3 above)
Comment (WinterSolstice8) [reply scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua]: Commented for now, but leaving in as a note for myself when I test

File: scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua [hunk 4]
```diff
@@ -20,76 +23,287 @@ local minionGroup =
...
+local eleAbsorbActionID   = { 603, 604, 624, 404, 625, 626, 627, 307 }
+local eleAbsorbAnimations = { 432, 433, 434, 435, 436, 437, 438, 439 }
+
+local astralFlowPets = function()
+    for i = ID.mob.JAILER_OF_LOVE + 1, ID.mob.JAILER_OF_LOVE + 27 do
+        local pet = GetMobByID(i)
+        if pet and pet:isAlive() then
+            pet:timer(1500, function(petArg)
+                if petArg:getFamily() == 269 then -- xzomit
+                    petArg:useMobAbility(786) -- lateral slash
```
Comment (zach2good) [inline scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua]: We have enums for these now, can you at these there please?

**Review by zach2good — APPROVED** [review]

File: scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua (hunk 4 above)
Comment (WinterSolstice8) [reply scripts/zones/AlTaieu/mobs/Jailer_of_Love.lua]: done (this made me look into the fact that Xzomits were told to use a tonberry move. it looks like this section is guessed -- as far as I know, nobody has gotten a capture with  JoL using Astral Flow with an xzomit up)

**Comment by WinterSolstice8** [comment]
Undrafted -- added in the standback fixes and some other stuff relating to pets not having drops or giving exp. This is probably as good as it's gonna get without an extra super deep dive into specifics not covered by previous captures

**Review by Xaver-DaRed — APPROVED** [review]

**Comment by zach2good** [comment]
> This is probably as good as it's gonna get without an extra super deep dive into specifics not covered by previous captures

If you know the niche things that might be missing you can just leave them as comments - this is already a big step up for accuracy

**Comment by WinterSolstice8** [comment]
Exact (not guessed) 

- draw in distance
- standback distance

other weird shit like
how much does bio 3 DoT do to players, does it have refresh, can anything but sharks be used on astral flow and if so what TP moves do they use

**Comment by WinterSolstice8** [comment]
comments added to JoL's lua
