### PR TITLE
Interaction - Quest: Lure of the Wildcat (Jeuno)

### LINKED ISSUE #1177: Lure of the Wildcat (Jeuno) - Bluffnix not replying
I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
I have checked the commit log to see if the issue has been resolved since my server was last updated
I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
I have specified what branch this happens on branch: 202102_1 (stable)

Additional Information (Steps to reproduce/Expected behavior) :

I am experiencing an issue with the "Lure of the Wildcat (Jeuno)" quest in which Bluffnix does not "flash his badge." All other characters involved in this quest seem to work properly. The LUA code for Bluffnix seems to imply he should work, but I also see that Gobbiebag logic was removed entirely to its own script, making me unsure how well I really understand the NPC-interaction process.

I experience this on whasf's "Oldschool" server. While the version reports as 202102_1 (stable), whasf does update it regularly (though in what capacity, I do not know), and it was just updated on 2022/01/04. If it helps: there are other players on the server that previously/successfully completed the aforementioned quest.

This is the first issue I'm reporting; I've tried to do as much due diligence as I can. (Unfortunately, without an active IRC channel, I see no way to vet/test possible issues with others before reporting.) I hope my efforts/report will be well-received. Thank you.

### LINKED ISSUE #4119: 🐛 Quest - Jeuno: Bluffnix Gobbiebag blocks Lure of the Wildcat Jeuno progress
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 10

## Branch affected by issue 

`base`

## Steps to reproduce

- Speak with Ajithaam - Upper Jeuno (G-5) to start Lure of the Wildcat Jeuno quest
- Speak with Bluffnix - Lower Jeuno (H-9) repeatedly. Bluffnix will only mention Gobbiebags ( /scripts/quests/jeuno/helpers.lua ) and will not progress Lure of the Wildcat ( /scripts/zones/Lower_Jeuno/npcs/Bluffnix.lua )

## Expected behavior

- Should flash Wildcat badge at Bluffnix and progress bitmask accordingly:
/scripts/zones/Upper_Jeuno/npcs/Ajithaam.lua
01000    (H-9) Bluffnix (Gobbiebag quest NPC, in Muckvix's Junk Shop)

### PR DESCRIPTION
**Pull request by claywar**
Add missing position documentation

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Fixes #1177 
Fixes #4119

* Converts the TOAU Quest, "Lure of the Wildcat (Jeuno)" to Interaction Framework
* Adds Default Actions for NPCs impacted

## Steps to test these changes
* Follow guides for this quest

### CODE REVIEW

File: scripts/quests/jeuno/Lure_of_the_Wildcat_Jeuno.lua [hunk 1]
```diff
@@ -0,0 +1,184 @@
...
+local quest = Quest:new(xi.quest.log_id.JEUNO, xi.quest.id.jeuno.LURE_OF_THE_WILDCAT)
+
+quest.reward =
+{
+    fame     = 150,
+    fameArea = xi.quest.fame_area.JEUNO,
+    keyItem  = xi.ki.WHITE_INVITATION_CARD,
+}
+
+local wildcatNpcData =
```
Comment (zach2good) [inline scripts/quests/jeuno/Lure_of_the_Wildcat_Jeuno.lua:25]: Nice pattern!

**Review by zach2good — APPROVED** [review]
