### PR TITLE
[lua] Make JP for automaton hp/mp apply to deus ex automata

### LINKED ISSUE #8004: 🐛 Possible oversight on JP bonus with Deus Ex Automata
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

I don't know for certain, but it seems like an oversight that Deus Ex doesn't give the automaton the bonus max HP/MP from the player's job points before setting the lower starting HP/MP

## Expected behavior

It seems likely that it should, but I have not come across anything that definitively says it does.

### PR DESCRIPTION
**Pull request by MowFord**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Closed https://github.com/LandSandBoat/server/issues/8004

Small cleanup to [deus ex automata](https://www.bg-wiki.com/ffxi/Deus_Ex_Automata)
- add JP bonus HP/MP
- make % consider new max hp/mp since adding the mod doesn't give the hp to cap

Also made activate JA run `:updateHealth` so the UI immediately reflects updated values

confirmation from retail that activate and Deus Ex both provide JP bonus:
image
image

## Steps to test these changes

- `!changejob pup 99`
- `!addkeyitem JOB_BREAKER`
- `!setjobpoints <playername> 100`
- go to mog house and spend points in automaton hp/mp
- see activate and deus ex have same max hp/mp

### CODE REVIEW

File: scripts/globals/job_utils/puppetmaster.lua [hunk 1]
```diff
@@ -85,11 +85,16 @@ xi.job_utils.puppetmaster.onAbilityUseActivate = function(player, target, abilit
         local jpValue = player:getJobPointLevel(xi.jp.AUTOMATON_HP_MP_BONUS)
         pet:addMod(xi.mod.HP, jpValue * 10)
         pet:addMod(xi.mod.MP, jpValue * 5)
+        pet:updateHealth()
```
Comment (Xaver-DaRed) [inline scripts/globals/job_utils/puppetmaster.lua:88]: Shouldnt the health update come after the hp/mp additions?

Comment (MowFord) [reply scripts/globals/job_utils/puppetmaster.lua:88]: It's a poorly named binding, it updates the max HP/mp after mod changes

**Review by Xaver-DaRed — APPROVED** [review]
