### PR TITLE
Remove errant logic in Check Kill Credit binding

### LINKED ISSUE #3621: 🐛 Eschan Il'aern are not counting for multiple kill RoE Objectives
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Linux

## Branch affected by issue 

`base`, noticed on xiweb

## Steps to reproduce

Register the multiple kill Records of Eminence Objectives (ie: daily 20 or 30 kills, the repeatable 200 kill objective)
Go to Escha Ru'aun and start taking out mobs there.  Notice that the Zdei, Gargouilles, and Phuabo all register their kills towards the objectives, but the Il'aern do not.

## Expected behavior

All experience point weilding mobs in the zone register kills towards the mulitple kill objectives.

### PR DESCRIPTION
**Pull request by claywar**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Fixes #3621

Removes errant check in CLuaBaseEntity::checkKillCredit() which would fail if the player was more than 15 levels below the mob's level.

## Steps to test these changes
* Add RoE objectives for vanquish multiple enemies
* Set level to 99
* Kill Escha Il'Aern (level 116)
* Kill bunny in West Ronfaure

Aern will count for credit, bunny will not

### CODE REVIEW

File: src/map/lua/lua_baseentity.cpp [hunk 1]
```diff
@@ -10420,23 +10420,20 @@ uint8 CLuaBaseEntity::checkSoloPartyAlliance()
...
         ShowWarning("CLuaBaseEntity::checkKillCredit() - Non-PC type calling function, or PLuaBaseEntity is not a MOB.");
         return false;
     }
 
-    CCharEntity* PChar = static_cast<CCharEntity*>(m_PBaseEntity);
-    CMobEntity*  PMob  = static_cast<CMobEntity*>(PLuaBaseEntity->GetBaseEntity());
-
-    bool  credit  = false;
-    int   lvlDiff = (int)(PMob->GetMLevel()) - (int)(PChar->GetMLevel());
-    int   maxDiff = (arg1 != sol::lua_nil) ? arg1.as<int>() : 15;
```
Comment (TeoTwawki) [inline src/map/lua/lua_baseentity.cpp:10436]: if we're no longer baking in a default value, FoV/GoV global scripts will need a small update to the calling line to have same 15 level check they use now.

Comment (claywar) [reply src/map/lua/lua_baseentity.cpp:10436]: Is that confirmed that there is a 15 level hard cap of being over the mob?

Comment (TeoTwawki) [reply src/map/lua/lua_baseentity.cpp:10436]: I honestly can't say if thats "the line". its been there since forever and retained all the way to present day. I'd need to go dig in previous project iterations issues and pr's t see the exact argument for why it was added, or go load up retail and test. There def is some limit beyond simply "did you get exp" though, and removing that results in exploitable behaviors. I'd rather err on getting it imperfect than getting it exploitable.

**Review by TeoTwawki — APPROVED** [review]
