### PR TITLE
[lua, sql] Mother Globe behavior and pathing adjustments, Olla Trio adjustments

### LINKED ISSUE #811: Sky T1 NM's missing a lot of mechanics.
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
https://ffxiclopedia.fandom.com/wiki/Category:Sky_Notorious_Monsters
Olla Grande trio has wrong spells.
Detectors/Defenders don't have summoning animations.
Mother globe doesn't summon animation and doesn't summon slaves while roaming. Shock spikes should be 1 hour duration and dispellable(but immediately reapplied). 
Faust doesn't turn in place properly, or have his typhoon spam mechanic, and only spams panzerfaust.
Despot only spams typhoon(Mustve mixed up skilllist with faust).
Brigandish blade is missing: Must be hit by a Buccaneer's Knife (which can be stolen from it) to remove its damage immunity effect.
Ullikimi doesn't have proper spells, no regain, and his heavy strike doesn't ignore shadows.

### PR DESCRIPTION
**Pull request by CriticalXI**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

- As usual, adds missing immunities. 
- Reworks Mother Globe to utilize the callPets mob util. Slave Gloves also do not aggro or link with each other.
   - [Capture](https://www.youtube.com/watch?v=jf1SenJcA_I&feature=youtu.be)
- Adds pathing to Mother Globe. She appears to have 9 sub sections of the room that she randomly chooses between that she then will path within that section 1-4 times before moving to a new section.
  - [Capture](https://www.youtube.com/watch?v=wHHu-4rsGiI)
- MG now has stealable shock spikes that immediately reapply upon wearing. Also added innate enthunder.
- All Olla pots now have increasing regain per pot size.

Closes https://github.com/LandSandBoat/server/issues/811

## Steps to test these changes

- Observe Mother Globe path with slaves in a train. 
- You can pull the middle slave globe, the end of the chain will follow it but not engage. They return to the train once it dies.

### CODE REVIEW

File: scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua [hunk 1]
```diff
@@ -19,117 +19,193 @@ local slaveGlobes =
...
+        return
+    end
 
-    if shouldSummonSlaveGlobe and (not inCombat or combatHasNotRecentlyStarted) then
-        local slaveGlobe = notSpawnedSlaves[1]
-        local slaveSlot = #spawnedSlaves + 1
-        local slaveGlobePos = validSlavePositions[slaveSlot]
+    if xi.mob.callPets(mob, slaveGlobes, callPetParams) then
+        -- Set up train following after pet spawns (with delay for spawn animation)
+        mob:timer(6000, function(mobArg)
```
Comment (MowFord) [inline scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua]: probably better to use `1000 + callPetParams.inactiveTime`

File: scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua [hunk 2]
```diff
@@ -19,117 +19,193 @@ local slaveGlobes =
...
-                local action = currentSlave:getCurrentAction()
-                if action ~= xi.act.NONE and action ~= xi.act.DEATH then
-                    currentSlave:follow(followTarget, xi.followType.ROAM)
-                    followTarget = currentSlave
-                end
+local setupTrainFollowing = function(mob)
+    local followTarget = mob
+    for _, slaveGlobeID in ipairs(slaveGlobes) do
+        local currentSlave = GetMobByID(slaveGlobeID)
+        if currentSlave and currentSlave:isSpawned() then
```
Comment (MowFord) [inline scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua]: `isAlive()` probably is more accurate to use

File: scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua [hunk 3]
```diff
@@ -141,21 +217,43 @@ entity.onMobFight = function(mob, target)
...
+
+    -- Try to spawn slaves while roaming
+    trySpawnSlaveGlobe(mob)
 
-    trySpawnSlaveGlobe(mob, GetSystemTime(), spawnedSlaves, notSpawnedSlaves, validSlavePositions)
+    -- Restore train formation periodically (every 10 seconds) and only if slaves exist
+    local lastTrainSetup = mob:getLocalVar('lastTrainSetup')
+    if nowTime >= lastTrainSetup + 10 and countSpawnedSlaves() > 0 then
+        setupTrainFollowing(mob)
+        mob:setLocalVar('lastTrainSetup', nowTime)
```
Comment (MowFord) [inline scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua]: Keeping a localvar of the "current living slave globes" and setting up the train when that value changes should allow you to have the setup only here in MG's `onMobRoam` and remove the timer after xi.mob.callPets

File: scripts/zones/The_Shrine_of_RuAvitau/mobs/Slave_Globe.lua
Comment (MowFord) [inline scripts/zones/The_Shrine_of_RuAvitau/mobs/Slave_Globe.lua:1]: Should probably remove the death listener on slave globes if you just update the follow chain anytime the pet count changes

**Review by MowFord — COMMENTED** [review]
setupTrainFollowing is a really slick solution

File: scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua (hunk 2 above)
Comment (Xaver-DaRed) [reply scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua]: I agree. It can be dead but not despawned yet.

File: scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua (hunk 3 above)
Comment (Xaver-DaRed) [reply scripts/zones/The_Shrine_of_RuAvitau/mobs/Mother_Globe.lua]: Its worth a shot, tbh

File: scripts/zones/The_Shrine_of_RuAvitau/mobs/Slave_Globe.lua
Comment (Xaver-DaRed) [reply scripts/zones/The_Shrine_of_RuAvitau/mobs/Slave_Globe.lua:1]: ^

**Comment by Xaver-DaRed** [comment]
Rebase, please. Also, address the comments within reason

**Comment by CriticalXI** [comment]
Got the requested changes put in and rebased.

**Review by Xaver-DaRed — APPROVED** [review]
