### PR TITLE
Fix/8859 prishe benediction promathia

### LINKED ISSUE #8859: 🐛 CoP mission Dawn: Prishe's Benediction also heals Promathia
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows

## Branch affected by issue 

`base`

## Steps to reproduce

Fight Promathia during CoP mission 8-4 (Dawn), see Prishe use Benediction, see Promathia get healed alongside party members.

## Expected behavior

Benediction should only heal friendly targets.

### PR DESCRIPTION
**Pull request by Alphiez**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Closes #8859.

Fixes Dawn (CoP 8-4) behavior where Prishe’s Benediction could incorrectly heal Promathia. While validating the fix, I found two related Dawn issues (Raise targeting on NPC allies and Prishe reusing Daedalus Wing) and addressed them as well.

#### 1) Prishe Benediction incorrectly healing Promathia (Issue #8859)
- Root cause: Benediction’s healing logic path could select Promathia under certain conditions (enemy being treated as a valid recipient / missing ally-only restriction).
- Fix: Restrict Benediction to apply only to valid friendly targets (party/allies) in this battlefield context, preventing Promathia from being eligible for the heal.

#### 2) Raise spells failing on Prishe (NPC ally) [extra fix]
- Root cause: Raise spell scripts used `target:hasRaiseTractorMenu()` as a universal block. In the image below, if you look at "RAISE CHECK", we can see that the menu is set to TRUE - That check is only meaningful for PCs (playable characters) (Raise/Tractor menu state), but it caused NPC allies to fail the casting check even when dead.
```
printf("RAISE CHECK: name=%s hp=%d dead=%s alive=%s menu=%s pool=%d obj=%d",
        name, hp, tostring(dead), tostring(alive), tostring(menu), pool, obj)
```
image
- Fix: Only apply `hasRaiseTractorMenu()` gating to PCs. For non-PC targets, require that the target is explicitly raisable via the behavior bit (`BEHAVIOR_RAISABLE`) before allowing the cast.
- Result: Players remain unchanged (normal Raise menu rules), while raisable NPC allies can be targeted by Raise I/II/III.

#### 3) Prishe repeatedly using Daedalus Wing [extra fix]
- Root cause: `useMobAbility(1487)` was triggered on engage every time she re-engaged (including after being raised / phase transitions).
- Fix: Track a local var (`used_item_1`) and only allow the ability once. Initialize it at battlefield spawn and set it so Phase II / resets don’t allow re-use.
- Result: Prishe uses Daedalus Wing once at the start of combat, and never again during the battlefield session.

## Steps to test these changes

1. Grant the Dawn mission: !addmission 6 840
2. Zone into Empyreal Paradox: !zone 36
3. Walk forward and enter the Dawn battlefield.
4. Verify Benediction does not heal Promathia: by using !hp <low_hp#> to force benediction or just wait
5. Verify Raise I/II/III on Prishe: with !hp 0 the try to raise her with a Raise spell
- If there is an issue here, it could be due to the db of prishe not having the correct behavior. I don't remember updating the data base to reflect the correct behavior - I think it exists as it should but here are steps to check
- Execute mariadb.exe (for me its located in C:\Program Files\MariaDB 10.6\bin>)  .\mariadb.exe -u root -p
- USE xidb;
- Use the following Query: ```SELECT poolid,name,behavior,(behavior & 4) AS raisable FROM mob_pools WHERE poolid=3199;```
- You should see Prishe behavior is 5 thus her raisable value is 4 making her a raisable target.
```
MariaDB [xidb]> SELECT poolid,name,behavior,(behavior & 4) AS raisable FROM mob_pools WHERE poolid=3199;
+--------+--------+----------+----------+
| poolid | name   | behavior | raisable |
+--------+--------+----------+----------+
|   3199 | Prishe |        5 |        4 |
+--------+--------+----------+----------+
1 row in set (0.000 sec)
```
6. Verify Daedalus Wing is one-time only:
- On initial engage, confirm Prishe uses Daedalus Wing once.
- Let her die and raise her again.
- Confirm she does NOT use Daedalus Wing again (including in Phase II engage).

### CODE REVIEW

File: scripts/actions/mobskills/benediction.lua [hunk 1]
```diff
@@ -9,6 +9,11 @@ mobskillObject.onMobSkillCheck = function(target, mob, skill)
 end
 
 mobskillObject.onMobWeaponSkill = function(target, mob, skill)
+
+    if target:getAllegiance() ~= mob:getAllegiance() then
+        return 0
+    end
```
Comment (Xaver-DaRed) [inline scripts/actions/mobskills/benediction.lua]: This kind of behavior/logic belongs to core, target-finding, not here.

File: scripts/actions/mobskills/benediction.lua [hunk 2]
```diff
@@ -21,4 +26,4 @@ mobskillObject.onMobWeaponSkill = function(target, mob, skill)
     return maxHeal
 end
 
-return mobskillObject
+return mobskillObject
```
Comment (Xaver-DaRed) [inline scripts/actions/mobskills/benediction.lua]: Newline t the end of file is needed.

File: scripts/actions/spells/white/raise.lua [hunk 3]
```diff
@@ -3,33 +3,41 @@
 -----------------------------------
 ---@type TSpell
 local spellObject = {}
+local BEHAVIOR_RAISABLE = 0x004
```
Comment (Xaver-DaRed) [inline scripts/actions/spells/white/raise.lua]: This is unneeded. We already have a global, predefined enum for this
`xi.behavior.RAISABLE`

File: scripts/actions/spells/white/raise_ii.lua [hunk 4]
```diff
@@ -1,35 +1,43 @@
 -----------------------------------
--- Spell: Raise
+-- Spell: Raise II
 -----------------------------------
 ---@type TSpell
 local spellObject = {}
+local BEHAVIOR_RAISABLE = 0x004
```
Comment (Xaver-DaRed) [inline scripts/actions/spells/white/raise_ii.lua]: This is unneeded. We already have a global, predefined enum for this
`xi.behavior.RAISABLE`

File: scripts/actions/spells/white/raise_iii.lua [hunk 5]
```diff
@@ -1,35 +1,43 @@
 -----------------------------------
--- Spell: Raise
+-- Spell: Raise III
 -----------------------------------
 ---@type TSpell
 local spellObject = {}
+local BEHAVIOR_RAISABLE = 0x004
```
Comment (Xaver-DaRed) [inline scripts/actions/spells/white/raise_iii.lua]: This is unneeded. We already have a global, predefined enum for this
`xi.behavior.RAISABLE`

File: scripts/battlefields/Empyreal_Paradox/dawn.lua [hunk 6]
```diff
@@ -66,8 +68,13 @@ function content:onEventFinishBattlefield(player, csid, option, npc)
     for _, ally in pairs(bcnmAllies) do
         ally:resetLocalVars()
         local spawn = ally:getSpawnPos()
+        -- Logic to refrain Prishe from using Daedalus Wing again
+        if ally:getName() == 'Prishe' then
+            ally:setLocalVar('used_item_1', 1)
+        end
         ally:setPos(spawn.x, spawn.y, spawn.z, spawn.rot)
     end
+
```
Comment (Xaver-DaRed) [inline scripts/battlefields/Empyreal_Paradox/dawn.lua]: None of this is needed, I'm pretty sure. You are already gating its usage to once per battlefiled by checking the variable

File: scripts/zones/Empyreal_Paradox/mobs/Prishe.lua [hunk 7]
```diff
@@ -45,7 +45,12 @@ entity.onMobRoam = function(mob)
 end
 
 entity.onMobEngage = function(mob, target)
-    mob:useMobAbility(1487)
+    -- Logic to only allow Daedalus Wing to be cast once
+    if mob:getLocalVar('used_item_1') == 0 then
+        mob:setLocalVar('used_item_1', 1)
```
Comment (Xaver-DaRed) [inline scripts/zones/Empyreal_Paradox/mobs/Prishe.lua]: 'used_item_1' -> 'usedWing'

File: scripts/actions/spells/white/raise_iii.lua [hunk 8]
```diff
@@ -1,35 +1,43 @@
...
+        return xi.msg.basic.MAGIC_CANNOT_BE_CAST
+    end
+
+    -- Non-PC targets must be explicitly raisable (behavior bit)
+    if not target:isPC() then
+        local behavior = target:getBehavior()
+        if bit.band(behavior, BEHAVIOR_RAISABLE) == 0 then
+            return xi.msg.basic.MAGIC_CANNOT_BE_CAST
+        end
+    end
```
Comment (Xaver-DaRed) [inline scripts/actions/spells/white/raise_iii.lua:24]:
```lua
-- Non-PC targets must be explicitly raisable (behavior bit)
if not target:isPC() and bit.band(target:getBehavior(), xi.behavior.RAISABLE) == 0 then
    return xi.msg.basic.MAGIC_CANNOT_BE_CAST
end
```

**Comment by Xaver-DaRed** [comment]
Welcome to the project

File: scripts/battlefields/Empyreal_Paradox/dawn.lua (hunk 6 above)
Comment (Alphiez) [reply scripts/battlefields/Empyreal_Paradox/dawn.lua]: Thank you, I made the changes and improved Prishe.lua logic to handle the one time use.

File: scripts/zones/Empyreal_Paradox/mobs/Prishe.lua (hunk 7 above)
Comment (Alphiez) [reply scripts/zones/Empyreal_Paradox/mobs/Prishe.lua]: changed to usedWing, thanks.

**Comment by Alphiez** [comment]
Apologies for the extra commits, I was getting familiar with the sanity check workflow and figured how to run it from the terminal so I could verify everything passed before pushing.

**Summary of changes:**
- Applied logic to the core (targetfind.cpp) AoE target selection so self-centered abilities (like Prishe’s Benediction) respect allegiance and no longer include enemy entities such as Promathia.
- Removed the Lua-level Benediction workaround since the behavior is now correctly enforced in core targeting logic.
- Updated Raise / Raise II / Raise III to consistently require the `xi.behavior.RAISABLE` behavior flag for non-PC targets.
- Cleaned up Prishe and Dawn Lua scripts (Daedalus Wing usage and formatting).
- Cleaned up white spaces, missing newlines at end, etc.

All changes now pass sanity checks

File: scripts/zones/Empyreal_Paradox/mobs/Prishe.lua [hunk 9]
```diff
@@ -45,7 +45,17 @@ entity.onMobRoam = function(mob)
...
-    mob:useMobAbility(1487)
+    -- Logic to only allow Daedalus Wing to be cast once
+    local battlefield = mob:getBattlefield()
+    if not battlefield then
+        return
+    end
+
+    if battlefield:getLocalVar('usedWing') ~= 1 then
+        battlefield:setLocalVar('usedWing', 1)
+        mob:useMobAbility(1487)
```
Comment (Skold177) [inline scripts/zones/Empyreal_Paradox/mobs/Prishe.lua]: Whenever you're working on something and notice hard coded IDs like this you can (and should) clean them up with a enum entry for improved readability.

Check out mob_skill.lua and add the entry there. something like 1487 = PRISHE_DAEDALUS_WING, then you can clean up that line to mob:useMobAbility(xi.mobSkill.PRISHE_DAEDALUS_WING)

Comment (Xaver-DaRed) [reply scripts/zones/Empyreal_Paradox/mobs/Prishe.lua]: The naming convention for mobskills is
`MOBSKILL_NAME_USE_CASE`
In this case it would be
`DAEDALUS_WING_COP_PRISHE`

Comment (Alphiez) [reply scripts/zones/Empyreal_Paradox/mobs/Prishe.lua]: Thank you for the feedback, I agree. I'll take a look tonight and make this change. Appreciate the mentorship and patience.

**Comment by sruon** [comment]
Thanks for the PR. 

I pulled it and ran Dawn but unfortunately while it resolved Prishe issue, it made almost all of Promathia moves fail with "No target in area of effect".

Can I ask that you remove the targetfind.cpp changes and I'll submit a separate bugfix sometime soon?

**Comment by Alphiez** [comment]
> Thanks for the PR.
> 
> I pulled it and ran Dawn but unfortunately while it resolved Prishe issue, it made almost all of Promathia moves fail with "No target in area of effect".
> 
> Can I ask that you remove the targetfind.cpp changes and I'll submit a separate bugfix sometime soon?

Ah man, sorry I didn't catch that. I'll quickly make the changes for this next push. I want to still take a stab at the fix ; ; I feel like I come so far haha. 

I'll submit here shortly with the asked fixes

**Review by Xaver-DaRed — APPROVED** [review]
