### PR TITLE
[c++] Add distance and mp validation before mob spell cast

### LINKED ISSUE #306: Mobs with active Manafont or Chainspell and are able to cast will not move or draw players in
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Players can exploit this by simply running out of casting range from mobs with those effects active, even if the mob has no self-targeting spell such as Blaze Spikes (if they have self-targeting spells, ie. like a generic RDM spell list, they will spam buffs on themselves). If the mob is unable to cast spells (ie. is silenced), it will move and/or draw players in as expected.

### PR DESCRIPTION
**Pull request by CriticalXI**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

- Mobs had an issue where they would get stuck in attempting to cast a spell. This was immediately obvious with Chainspell, where the mob can be bound essentially if all targets run out of range. This also occurs when mobs run out of MP, they will bind themselves attempting to cast a spell they don't have enough MP to.
- I added a new check in TryCastSpell for mobs to validate they are in range and have MP before committing to a spell
- Created a new battleutil `CanAffordSpell` for checking if the entity has MP for the spell

Closes https://github.com/LandSandBoat/server/issues/306

## Steps to test these changes

- Ensure MP checks are properly blocking spell casts for mobs
- Fight a mob with chainspell active, see that it closes the distance if target is out of range

### CODE REVIEW

File: src/map/ai/controllers/mob_controller.cpp [hunk 1]
```diff
@@ -504,6 +504,38 @@ auto CMobController::TryCastSpell() -> bool
 
     if (chosenSpellId.has_value())
     {
+        // Check if we can actually cast this spell before committing to it
```
Comment (MowFord) [inline src/map/ai/controllers/mob_controller.cpp:507]: This all seems reasonable, but shouldn't the checks go within `CastSpell` and make that return bool

Comment (WinterSolstice8) [reply src/map/ai/controllers/mob_controller.cpp:507]: Logic needs to be higher up (in here) if we want the AI to be smart and pick a different spell, though honestly a lot of the AI could use a rewrite

Comment (MowFord) [reply src/map/ai/controllers/mob_controller.cpp:507]: Yea unfortunately that reminds me that most spell selections are dumb and the mob just loses the tick if the spell it chooses cannot be cast

Comment (WinterSolstice8) [reply src/map/ai/controllers/mob_controller.cpp:507]: yeah. it's bad. the stink of 10 year old technical debt...

**Review by WinterSolstice8 — APPROVED** [review]
LGTM
