### PR TITLE
[core] Remove destructor on CInstance, as the parent performs cleanup.

### LINKED ISSUE #5263: 🐛 Instace cleanup crashes server
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
It appears that if mobs remain in an instance, a cleanup of the instance crashes the server due to this deconstructor:

image

image

We've seen it for instance id 6300 as well. Here's a crashdump

https://cdn.discordapp.com/attachments/1152236166817521785/1217858332748939284/toau.zip?ex=66058df5&is=65f318f5&hm=3057548938a7edf2f81505808831f3d9488bc6b3325ed711c289b4565b65492f&

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

As it says on the tin, the CInstance destructor is obsoleted by the parent class, preventing a double free.

Fixes #5263 
## Steps to test these changes

see #5263

### CODE REVIEW

**Comment by MowFord** [comment]
Confirmed this resolved the linked issue

File: src/map/instance.cpp [hunk 1]
```diff
@@ -41,25 +41,7 @@ CInstance::CInstance(CZone* zone, uint16 instanceid)
...
-    for (auto entity : m_petList)
-    {
-        destroy(entity.second);
-    }
-    for (auto entity : m_trustList)
-    {
-        destroy(entity.second);
-    }
-}
+CInstance::~CInstance() = default;
```
Comment (zach2good) [inline src/map/instance.cpp]: Instead of default, can you slap a Tracy Zone in here, and in the constructor? Then it's good to go 👍

**Review by zach2good — APPROVED** [review]

File: src/map/instance.cpp (hunk 1 above)
Comment (WinterSolstice8) [reply src/map/instance.cpp]: Updated, this -- with `TracyZoneScoped;` ?

Comment (zach2good) [reply src/map/instance.cpp]: Yessir, looks good 👍
