### PR TITLE
[Conquest] Fix zone checked , so city zones are also included

### LINKED ISSUE #3137: 🐛 Traveling Merchants (Regional NPC's) not appearring in 1st place nation if 2nd/3rd place nations are allied?
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Linux

## Branch affected by issue 

`base`, noticed on xiweb, rebuilt late on 11/3/2022

## Steps to reproduce

One nation wins conquest, the two losing nations are allied.  Seek out the Traveling Merchants (Nokkhi Jinjahl, Ominous Cloud, and Valeriano) in the appropriate zone of the 1st place nation, and they are not there. (more details and screen shots to follow in additional comment)

## Expected behavior

These merchants appear when there is a clear winning 1st place ranked nation in conquest... no alliance or tie with that 1st place nation.

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
Co-authored-by: zach2good <zach2good@users.noreply.github.com>

**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Fixes an issue with conquest zone checks. City zones were not being included. Thiswould affect conquest-dependant npcs, like the traveling merchant troupe not spawning.

## Steps to test these changes

Add a print in city zones dependant on conquest and check if cities are called now.

### CODE REVIEW

File: src/map/conquest_system.cpp [hunk 1]
```diff
@@ -51,10 +51,13 @@ namespace conquest
         zoneutils::ForEachZone([](CZone* PZone)
         {
             // only find chars for zones that have had conquest updated
-            if (PZone->GetRegionID() <= REGION_TYPE::TAVNAZIA)
+            if (PZone->GetRegionID() <= REGION_TYPE::DYNAMIS)
```
Comment (claywar) [inline src/map/conquest_system.cpp:54]: Should this be < and not <=?

Comment (zach2good) [reply src/map/conquest_system.cpp:54]: Dynamis should be included (I think, because all of those zone scripts have onConquestUpdate bindings)

**Comment by LoxleyX** [comment]
While this allows the conquest updates in lua to be called, I believe this doesn't fix #3137, as the tied conquest issue would still remain.

**Review by zach2good — APPROVED** [review]
This will probably act as part 1 of the fix for https://github.com/LandSandBoat/server/issues/3137, but will require a little work (which I'm gonna start now)
