### PR TITLE
[lua] Refactor PDIF clamping and simplify code

### LINKED ISSUE #38: Level Correction (Cratio) is incorrect
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Line 585 in physical_utilities.lua says
`        levelDifFactor = (actor:getMainLvl() - target:getMainLvl()) * 3 / 64 -- 3/64 from JP model which fits better`
This is wrong, it's 0.05 per level, and 0.025 for ranged starting from 2 levels higher than you. This is even shown on line 651
https://www.ffxiah.com/forum/topic/57989/post-2016-level-correction-testing/

Pretty sure in era it started the first level above you, not the 2nd but either way it should be 0.05 for melee and 0.025 for ranged

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

After talking to Jimmayus and other math nerds in the math nerds group chat..

adjusts ranged pdif to be half of melee pdif

Corrects pdif caps for corrected areas/non corrected areas for mobs via a note in https://forum.square-enix.com/ffxi/threads/31310-March-27-2013-(JST)-Version-Update

mobs in a corrected zone should be able to reach 3.0 pdif after crit and then another 1.0 pdif from correction

cratio cap: 2
pre randomizer cap: 4

but when in a non-corrected zone, the caps are the same. 
Refactors usage of caps (there was some clamps that were not necessary based off of _player optimizations_ on the wiki and not reality)

Closes https://github.com/phoenixffxi/Phoenix/issues/38

## Steps to test these changes
get meleed by stuff

### CODE REVIEW

File: scripts/globals/combat/physical_utilities.lua [hunk 1]
```diff
@@ -625,7 +627,16 @@ xi.combat.physical.calculateMeleePDIF = function(actor, target, weaponType, wsAt
...
-    else -- Mobs and pets, unconfirmed if pets use this same formula
+    else
+        -- Mobs and pets, unconfirmed if pets use this same formula
+        -- corrected mobs have 2.0 pdif + 1.0 for crits
+        -- non-corrected mobs have 4.0 pdif cap period
+        if applyLevelCorrection then
+            pDifFinalCap = (2.0 + damageLimitPlus) * damageLimitPercent + (isCritical and 1 or 0)
+        else
+            pDifFinalCap = (4.0 + damageLimitPlus) * damageLimitPercent
+        end
```
Comment (Xaver-DaRed) [inline scripts/globals/combat/physical_utilities.lua]: Proposal
```lua
    else
        -- Mobs and pets, unconfirmed if pets use this same formula
        -- corrected mobs have 2.0 pdif + 1.0 for crits
        -- non-corrected mobs have 4.0 pdif cap period
        local basePDIF  = applyLevelCorrection and 2 or 4
        local critBonus = (applyLevelCorrection and isCritical) and 1 or 0
        pDifFinalCap    = (basePDIF + damageLimitPlus) * damageLimitPercent + critBonus
```

File: scripts/globals/combat/physical_utilities.lua [hunk 2]
```diff
@@ -763,15 +768,30 @@ xi.combat.physical.calculateRangedPDIF = function(actor, target, weaponType, wsA
...
+
+    if actor:isPC() then
+        pDifFinalCap = (xi.combat.physical.pDifWeaponCapTable[weaponType] + damageLimitPlus) * damageLimitPercent -- Added damage limit bonuses
+    else
+        if applyLevelCorrection then
+            pDifFinalCap = (3.0 + damageLimitPlus) * damageLimitPercent
+        else
+            pDifFinalCap = (4.0 + damageLimitPlus) * damageLimitPercent -- 4.0 is guessed
+        end
+    end
```
Comment (Xaver-DaRed) [inline scripts/globals/combat/physical_utilities.lua:789]: Proposal
```lua
    if actor:isPC() then
        pDifFinalCap = (xi.combat.physical.pDifWeaponCapTable[weaponType] + damageLimitPlus) * damageLimitPercent -- Added damage limit bonuses
    else
        local basePDIF = applyLevelCorrection and 3 or 4 -- 4.0 is guessed
        pDifFinalCap   = (basePDIF + damageLimitPlus) * damageLimitPercent
    end
```

**Review by Xaver-DaRed — APPROVED** [review]
Looks sane
