### PR TITLE
Correct messaging, allow for multiple currency exchange with Awaheen

### LINKED ISSUE #8717: NPC Awaheen only accepts 1 currency at a time
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Win11

## Branch affected by issue 

`base`

## Steps to reproduce

Add any of the currency needed (Imp Gold, Mythril, or Silver) x2
Trade 2x to Awaheen (no interaction) 
Messaging shows individual lines for currency received (eg Trade Mythril Piece and it will say "You obtain Imperial Silver Piece" twice.

## Expected behavior

Trading multiple should result in receiving multiple. 
Messaging should only show 1 line of all currency recevied (eg Trade Mythril Piece and it will say "You obtain 2 Imperial Silver Pieces!"

Caps:
https://youtu.be/FB52Gnmp-PI
https://1drv.ms/u/c/87e665e10555c452/EcqjhiJsg6RBg7_2Akce5O8BuhBd3H7ulOxAtXlr0L1H1w?e=Cm88Zg

### PR DESCRIPTION
**Pull request by claywar**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
Fixes #8717 

Allows Awaheen to receive multiple of the same currency and corrects messaging to align with retail

## Steps to test these changes
Trade Gold, Mythril, or Silver coins in various quantities to Awaheen

### CODE REVIEW

File: scripts/zones/Nashmau/npcs/Awaheen.lua [hunk 1]
```diff
@@ -2,40 +2,24 @@
...
+    [xi.item.IMPERIAL_SILVER_PIECE ] = 5,
+}
 
-    if reward > 0 then
-        if player:getFreeSlotsCount() >= 1 then
+entity.onTrade = function(player, npc, trade)
+    for currencyType, exchangeMultiplier in pairs(currencyExchangeData) do
+        if
+            npcUtil.tradeHasOnly(trade, currencyType) and
+            npcUtil.giveItem(player, { { currencyType - 1, trade:getItemCount() * exchangeMultiplier } })
```
Comment (WinterSolstice8) [inline scripts/zones/Nashmau/npcs/Awaheen.lua:19]: Shouldn't this be 


```suggestion
            npcUtil.giveItem(player, { { currencyType - 1, trade:getItemQty(currencyType) * exchangeMultiplier } })
```

?

Comment (Xaver-DaRed) [reply scripts/zones/Nashmau/npcs/Awaheen.lua:19]: tradeHasOnly() should ensure that theres just a single currency type, no?

Comment (claywar) [reply scripts/zones/Nashmau/npcs/Awaheen.lua:19]: Correct.  It's a wrapper which checks that there's only one item.

```
function npcUtil.tradeHasOnly(trade, itemID)
    return npcUtil.tradeHasExactly(trade, { { itemID, trade:getItemCount() } })
end
```

**Review by Xaver-DaRed — APPROVED** [review]
