### PR TITLE
[connect] Additional checks for character name creation (exising entity names, bad words)

### LINKED ISSUE #3030: 🐛 Can't delete character
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

## OS / platform the server is running (if known)

Server 2016

## Branch affected by issue 

`base`

## Steps to reproduce

When someone goes to delete a character, the lobby server complains it is unable to find the setting:
[10/23/22 20:23:06:431][login][error] Settings: Failed to look up key: map.CHARACTER_DELETION, using default value: "false" (settings::get:157)

but that is the wrong namespace. According to settings/default/login.lua it is:
xi.settings.login.CHARACTER_DELETION

## Expected behavior

I expect players to be able to delete characters when the setting is set to TRUE (as it is in the default setting file)

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?

image

Also has commit to:
Fixes https://github.com/LandSandBoat/server/issues/3030

### CODE REVIEW

File: src/login/lobby.cpp [hunk 1]
```diff
@@ -779,42 +781,78 @@ int32 lobbyview_parse(int32 fd)
...
-                        return -1;
+                        invalidNameReason = "Internal entity name query failed.";
+                    }
+                    else if (sql->NumRows() != 0)
+                    {
+                        invalidNameReason = "Name already in use.";
                     }
 
-                    if (sql->NumRows() != 0 || invalidName)
+                    // (optional) Check if the name is in use by NPC or Mob entities
```
Comment (TeoTwawki) [inline src/login/lobby.cpp:819]: Retail allows this. I have met many players with names identical to a monster or NPC. I see you made it a setting, just making sure everyone realizes that's a thing.

Comment (TeoTwawki) [reply src/login/lobby.cpp:811]: I see you made it a setting, just making sure everyone realizes that's a thing.

File: settings/default/login.lua [hunk 2]
```diff
@@ -36,4 +36,25 @@ xi.settings.login =
...
+    -- Character names with any of these words in, in any position, will be rejected
+    --
+    -- Examples that will be rejected (using "badword"):
+    -- "badword"
+    -- "imbadword"
+    -- "badwordisme"
+    -- "lolbadwordlol"
+    --
+    -- WARNING:
+    -- Be aware of the "Scunthorpe problem"!
```
Comment (Flam9) [inline settings/default/login.lua:52]: For this reason, you may want to have two lists:
- wildcard banned names
- full word banned names

Some banned words are tricky to wildcard, especially the shorter ones. Banning the exact word as a name (as you do with NPCs) could be an alternative.

File: src/login/lobby.cpp [hunk 3]
```diff
@@ -779,42 +781,78 @@ int32 lobbyview_parse(int32 fd)
                     std::memset(CharName, 0, sizeof(CharName));
                     std::memcpy(CharName, sessions[fd]->rdata.data() + 32, sizeof(CharName));
 
-                    // find assigns
-                    const char* fmtQuery = "SELECT charname FROM chars WHERE charname LIKE '%s'";
+                    // Sanitize name
+                    char escapedCharName[16 * 2 + 1];
```
Comment (Flam9) [inline src/login/lobby.cpp:785]: I may have missed it, but I'm not seeing any place where we check charName length for validation.

File: src/login/lobby.cpp [hunk 4]
```diff
@@ -779,42 +781,78 @@ int32 lobbyview_parse(int32 fd)
...
+                        invalidNameReason = "Name already in use.";
                     }
 
-                    if (sql->NumRows() != 0 || invalidName)
+                    // (optional) Check if the name is in use by NPC or Mob entities
+                    if (settings::get<bool>("login.DISABLE_MOB_NPC_CHAR_NAMES"))
                     {
-                        if (invalidName)
+                        auto query =
+                            "WITH results AS "
```
Comment (Flam9) [inline src/login/lobby.cpp:823]: praise: as a newbie to sql, very cool

**Comment by Flam9** [comment]
Aside/scope-creep: does anyone know why the last query doesn't have the `ON UPDATE`? 
https://github.com/LandSandBoat/server/pull/3010/files#diff-17bfabb24cd9490f5d423fde8ae92d3000452237d584b23041f3ebcfafbe2dc1R1032

File: src/login/lobby.cpp (hunk 3 above)
Comment (zach2good) [reply src/login/lobby.cpp:785]: Its handled in the client, but I added some checks for it in case people get sneaky

File: settings/default/login.lua (hunk 2 above)
Comment (zach2good) [reply settings/default/login.lua:52]: I'm going to leave it as it is, since wildcard and whole-word are handled by the list. I think in terms of `the Scunthorpe problem`, you can have the offending word in many offensive configurations, but many less legitimate ones. Especially in terms of player names. I think it's totally OK to get some false positives if it means all bad words are blocked

**Comment by zach2good** [comment]
Ready for re-review

**Review by TeoTwawki — APPROVED** [review]
lgtm
