### PR TITLE
[core] Implement CSynthSuggestionListPacket

### LINKED ISSUE #2639: 🐛 Anillah NPC(cloth craft guild)
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)

NPC Anillah

`base`

## Steps to reproduce
Talked to this NPC to get recipe, after I clicked amateur, my character froze cant move or open menu. So I tried again, same result.

## Expected behavior

Tell me the recipe!
Amateur
cloth craft npc bug Anillah
information synthesis

### PR DESCRIPTION
**Pull request by claywar**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I've _**tested my code and the things my code has changed**_ since the last commit in the PR, and will test after any later commits

## What does this pull request do?
Closes #2639 

* Implements `CSynthSuggestionListPacket` as one of the possible formats for 0x31 packet which provides an potential list of items to populate menu.
* Adds additional logic to 0x058 SmallPacket handling to determine which Synth Suggestion to send (List, Recipe)

## Steps to test these changes
Talk to Crafting Support NPC and see possible crafts.

NOTE: The data displayed may need to be refined further, as it does not take into account subcrafts (if they are required to be at cap to display in the menu-based lists).

### CODE REVIEW

File: scripts/globals/crafting.lua [hunk 1]
```diff
@@ -204,6 +204,10 @@ xi.crafting.getCraftSkillCap = function(player, craftID)
     return (rank + 1) * 10
 end
 
+xi.crafting.getRealSkill = function(player, craftID)
+    return math.floor(player:getCharSkillLevel(xi.skill.CLOTHCRAFT) / 10)
```
Comment (Xaver-DaRed) [inline scripts/globals/crafting.lua]: Shouldn't `player:getCharSkillLevel(xi.skill.CLOTHCRAFT)` be `player:getCharSkillLevel(craftID)`?

Comment (claywar) [reply scripts/globals/crafting.lua]: Bad copy-pasta, fixing.

**Review by Xaver-DaRed — APPROVED** [review]
