### PR TITLE
[core] Fix conquest logs / latent effects not applying when zoning into non conquest areas 

### LINKED ISSUE #4486: 🐛 [xi_map] logging error "Invalid conquest region passed to function"
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Ubuntu 

## Branch affected by issue 

`base`

## Steps to reproduce

unknown how to reproduce. Tried opening the conquest reqion map to see if will crash, but no issues. 
Nobody in the server has reported an issue yet.

```
[09/11/23 01:18:43:974][map][debug] CZone:: Bastok_Markets IncreaseZoneCounter <1> Raist (InsertPC:103)
[09/11/23 01:18:43:975][map][error] Invalid conquest region passed to function (20) (getRegionOwner:96)
[09/11/23 01:18:57:594][map][error] Invalid conquest region passed to function (20) (getRegionOwner:96)
[09/11/23 01:19:13:544][map][debug] Message: Received message MSG_WORLD2MAP_REGIONAL_EVENT (20) from message server (parse:89)
[09/11/23 01:19:38:070][map][error] Invalid conquest region passed to function (20) (getRegionOwner:96)
[09/11/23 01:19:48:401][map][error] Invalid conquest region passed to function (20) (getRegionOwner:96)
[09/11/23 01:19:48:794][map][error] Invalid conquest region passed to function (20) (getRegionOwner:96)
[09/11/23 01:21:12:794][map][error] Invalid conquest region passed to function (20) (getRegionOwner:96)
```

## Expected behavior

No errors in log

### PR DESCRIPTION
**Pull request by xkoredev**
**_I affirm:_**

- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/AirSkyBoat/AirSkyBoat/blob/staging/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/AirSkyBoat/AirSkyBoat/blob/staging/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## Please enter a player-facing description

Fix latent effects from conquest related items not triggering when zoning into new areas.
Fix latent effects from conquest related items not triggering in zones that are not part of conquest, but should otherwise trigger these effects (I,e sky / sea)

## What does this pull request do? (Please be technical)

- Checks for destination region when zoning, to avoid issues with latent effects not triggering
- Fixes log spam for players in these non conquest but still latent applying regions (Fixes https://github.com/LandSandBoat/server/issues/4486)

## Steps to test these changes

Zone into a sea with items such as master caster bracelets. Check that latent applies and there are no errors logged about "Invalid conquest region passed to function"

## Special Deployment Considerations

I (@xkoredev) have smoke tested this. I am cherry picking from ASB, but **_I affirm:_**

- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/AirSkyBoat/AirSkyBoat/blob/staging/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/AirSkyBoat/AirSkyBoat/blob/staging/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## Please enter a player-facing description

Fix latent effects from conquest related items not triggering when zoning into new areas.
Fix latent effects from conquest related items not triggering in zones that are not part of conquest, but should otherwise trigger these effects (I,e sky / sea)

## What does this pull request do? (Please be technical)

- Checks for destination region when zoning, to avoid issues with latent effects not triggering
- Fixes log spam for players in these non conquest but still latent applying regions (Fixes https://github.com/LandSandBoat/server/issues/4486)

## Steps to test these changes

Zone into a sea with items such as master caster bracelets. Check that latent applies and there are no errors logged about "Invalid conquest region passed to function"

## Special Deployment Considerations

I (@xkoredev) have smoke tested this. I am cherry picking from ASB, but @Radegast-FFXIV will properly test this and answer any questions.

### CODE REVIEW

File: src/map/latent_effect_container.cpp [hunk 1]
```diff
@@ -1040,52 +1047,59 @@ bool CLatentEffectContainer::ProcessLatentEffect(CLatentEffect& latentEffect)
...
             break;
         }
         case LATENT::ZONE_HOME_NATION:
         {
+
             // player is logging in/zoning
-            if (m_POwner->loc.zone == nullptr)
+            // checking the state of the user's current zone and
+            // the destination zone in tandem seems to work.
+            if (m_POwner->loc.zone == nullptr && static_cast<uint16_t>(m_POwner->loc.destination) == 0)
```
Comment (zach2good) [inline src/map/latent_effect_container.cpp]: If we're still inside `CLatentEffectContainer::ProcessLatentEffect(CLatentEffect& latentEffect)`didnt you already check zone validity at the top? `(m_POwner->loc.zone == nullptr &`

File: src/map/latent_effect_container.cpp [hunk 2]
```diff
@@ -1040,52 +1047,59 @@ bool CLatentEffectContainer::ProcessLatentEffect(CLatentEffect& latentEffect)
...
 
-            auto region      = m_POwner->loc.zone->GetRegionID();
+            // Grab the user's destination if they're zoning.
+            // Otherwise, grab their current zone.
+            auto region      = m_POwner->loc.zone == nullptr ? zoneutils::GetCurrentRegion(m_POwner->loc.destination) : zoneutils::GetCurrentRegion(playerZoneID);
             auto hasSignet   = m_POwner->StatusEffectContainer->HasStatusEffect(EFFECT_SIGNET);
             auto hasSanction = m_POwner->StatusEffectContainer->HasStatusEffect(EFFECT_SANCTION);
             auto hasSigil    = m_POwner->StatusEffectContainer->HasStatusEffect(EFFECT_SIGIL);
-
+            auto regionAlwaysOutOfControl = zoneutils::IsAlwaysOutOfNationControl(region);
```
Comment (zach2good) [inline src/map/latent_effect_container.cpp:1060]: Formatting

File: src/map/latent_effect_container.cpp [hunk 3]
```diff
@@ -1040,52 +1047,59 @@ bool CLatentEffectContainer::ProcessLatentEffect(CLatentEffect& latentEffect)
...
+            // the destination zone in tandem seems to work.
+            if (m_POwner->loc.zone == nullptr && static_cast<uint16_t>(m_POwner->loc.destination) == 0)
             {
                 break;
             }
 
-            auto* PZone  = m_POwner->loc.zone;
-            auto  region = static_cast<REGION_TYPE>(latentEffect.GetConditionsValue());
+            auto  nationRegion = static_cast<REGION_TYPE>(latentEffect.GetConditionsValue());
+            auto  region = m_POwner->loc.zone == nullptr ? zoneutils::GetCurrentRegion(m_POwner->loc.destination) : zoneutils::GetCurrentRegion(playerZoneID);
```
Comment (zach2good) [inline src/map/latent_effect_container.cpp]: Extraneous spaces

**Review by zach2good — COMMENTED** [review]
Logically seems fine, just needs some styling

**Comment by zach2good** [comment]
I'm surprised clang-format passed some of these bits 🤔

**Review by zach2good — APPROVED** [review]

**Comment by zach2good** [comment]
Testing our new CI check: where I can do an approval, but it's pending requested changes (and then me removing the label I've put on)

File: src/map/latent_effect_container.cpp (hunk 1 above)
Comment (zach2good) [reply src/map/latent_effect_container.cpp]:
```
uint16 CBaseEntity::getZone() const
{
    return loc.zone != nullptr ? (uint16)loc.zone->GetID() : (uint16)loc.destination;
}
```

**Comment by xkoredev** [comment]
> Testing our new CI check: where I can do an approval, but it's pending requested changes (and then me removing the label I've put on)

I was planning on Radegast-FFXIV to make these changes since he is the author, but since this is on my fork, I may as well do them. Thanks Zach.

File: src/map/latent_effect_container.cpp (hunk 2 above)
Comment (xkoredev) [reply src/map/latent_effect_container.cpp:1060]: Fixed it. Odd my linter did not auto-fix this.

File: src/map/latent_effect_container.cpp (hunk 1 above)
Comment (xkoredev) [reply src/map/latent_effect_container.cpp]: I removed all redundant checks

File: src/map/latent_effect_container.cpp (hunk 3 above)
Comment (xkoredev) [reply src/map/latent_effect_container.cpp]: Fixed

**Comment by xkoredev** [comment]
Tested on my local LSB seems to all work as intended. Zoning into a zone without conquest, zoning into sea, etc.
