### PR TITLE
[core, lua] Revamp exdata handling

### LINKED ISSUE #9257: 🐛 CPP item setExData - not persistent thru zoning or visual updates on item
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce
Using this script to apply exData, I can see that it applies the exData however when i zone the exData does not carry over and zeros back out. nor does this update the item visually with the exData applied.  Referencing retail Dynamis - Divergence, the exData gets updated after each kill when the item is equipped. The RP value and or rank and augments are adjusted and is visually updated when examining the item. 
          exdata =
            {
                [0] = 3,
                [1] = 131,
                [2] = 00,
                [3] = 00,
                [4] = 00, -- every 4 is 1 rp ( 10 rp = 40 etc, when this reaches 255 bit 5 increases by 1 and the remainder is carried to bit 4) when a rank is acheived, bit 4 /5 reset back to zero and bit 6 increases by 4
                [5] = 00,
                [6] = 100, -- (132 is odyssea rank 30 gear / 248 is 30/30 field 7 = 0)( Every rank up this bit increases by 4 till it hits max 248)(Oboro 4-100 is rank 25/25 field 7 = 1)( 128 -208 is rank 20/20 field 7 = 2)
                [7] = 1, -- 0 Rank 30 / 1 Rank 25 / 2 Rank 15
                [8] = 139, -- disply augments
                [9] = 01, -- disply augments
                [10] = 00,
                [11] = 00,
                [12] = 00, -- signature
                [13] = 00, -- signature
                [14] = 00, -- augment 1
                [15] = 00, -- augment 1
                [16] = 00, -- augment 2
                [17] = 00, -- augment 2
                [18] = 00, -- augment 3
                [19] = 00, -- augment 3
                [20] = 00, -- augment 4
                [21] = 00, -- augment 4
                [22] = 00,
                [23] = 00,
            }
            local headpiece = player:getEquippedItem(xi.slot.HEAD)
                if headpiece ~= nil and headpiece:getID() == 12448 then
                    print(headpiece:getExData())
                     headpiece:setExData(exdata)
                end

Gave myself an item using script  below and this works for the NPCs that require a trade to update the exData however the augments would not apply until you zoned - 
       player:addItem({ id = 21526,
            exdata =
            {
                [0] = 3,
                [1] = 131,
                [2] = 00,
                [3] = 00,
                [4] = 00, -- every 4 is 1 rp ( 10 rp = 40 etc, when this reaches 255 bit 5 increases by 1 and the remainder is carried to bit 4) when a rank is acheived, bit 4 /5 reset back to zero and bit 6 increases by 4
                [5] = 00,
                [6] = 100, -- (132 is odyssea rank 30 gear / 248 is 30/30 field 7 = 0)( Every rank up this bit increases by 4 till it hits max 248)(Oboro 4-100 is rank 25/25 field 7 = 1)( 128 -208 is rank 20/20 field 7 = 2)
                [7] = 1, -- 0 Rank 30 / 1 Rank 25 / 2 Rank 15 / 20
                [8] = 18, -- display augments
                [9] = 00, -- display augments
                [10] = 00,
                [11] = 00,
                [12] = 00, -- signature
                [13] = 00, -- signature
                [14] = 00, -- augment 1
                [15] = 00, -- augment 1
                [16] = 00, -- augment 2
                [17] = 00, -- augment 2
                [18] = 00, -- augment 3
                [19] = 00, -- augment 3
                [20] = 00, -- augment 4
                [21] = 00, -- augment 4
                [22] = 00,
                [23] = 00,
            }
        })

I have packet captures of Dynamis D exData, ambuscade capes exData, different upgrades for Oboro exData,  if you need them. 

## Expected behavior

Retail behavior  - 
Image

Image

### PR DESCRIPTION
**Pull request by sruon**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

#### TL;DR
Reworks the way exdata is handled both in core and lua to get rid of fairly unreadable snippets

**Before**
```cpp
void CItem::setSoulPlateData(const std::string& name, uint32 interestData, uint8 zeni, uint16 skillIndex, uint8 fp)
{
    PackSoultrapperName(name, m_extra);

    // interestData is zone ID (high) + mob family ID (low)
    m_extra[15] = (interestData >> 24) & 0xFF;
    m_extra[16] = (interestData >> 16) & 0xFF;
    m_extra[17] = (interestData >> 8) & 0xFF;
    m_extra[18] = interestData & 0xFF;

    m_extra[19] = zeni;

    m_extra[20] = skillIndex << 7;
    m_extra[21] = skillIndex >> 1;
    m_extra[22] = skillIndex >> 9;

    m_extra[22] = fp << 3;
    m_extra[23] = (0x03 << 4) & fp;
}
```

```lua
player:addItem({
        id = xi.item.GLOWING_LAMP,
        exdata =
        {
            [ 0] = 0x1D + chamberId,
            [ 2] = 0x01,
            [ 8] = bit.band(endTime, 0xFF),
            [ 9] = bit.band(bit.rshift(endTime, 8), 0xFF),
            [10] = bit.band(bit.rshift(endTime, 16), 0xFF),
            [11] = bit.band(bit.rshift(endTime, 24), 0xFF),
            [12] = bit.band(startTime, 0xFF),
            [13] = bit.band(bit.rshift(startTime, 8), 0xFF),
            [14] = bit.band(bit.rshift(startTime, 16), 0xFF),
            [15] = bit.band(bit.rshift(startTime, 24), 0xFF),
        },
    })
```

**After**
```cpp
void CItem::setSoulPlateData(const std::string& name, uint32 interestData, uint8 zeni, uint16 skillIndex, uint8 fp)
{
    auto plate = exdata<Exdata::SoulPlate>();

    plate.PoolId      = interestData;
    plate.Quality     = zeni;
    plate.FeralSkill  = skillIndex;
    plate.FeralPoints = fp;
    PackSoultrapperName(name, plate.Signature);
}
```

```lua
local item = player:addItem({ id = xi.item.GLOWING_LAMP })
    if item then
        item:setExdata(
         {
            chamberId = chamberId,
            flags           = 0x01,
            endTime    = endTime,
            startTime   = startTime,
        })
    end
```

#### Changes
- Introduces structures for each exdata type - I got them all done but starting with just Legion Pass and Hourglass as they are presently unused
- `exdata<T>` getter on CItem enforcing 24 bytes struct - overlays the struct on top of the uint8 array as we've done with packets etc.
- Routes lua `get/setExdata` through a dispatch system deducing the appropriate structure based on item specifications
  - This more or less follows the flow the client uses - as documented in @atom0s [itemdata.lua](https://github.com/AshitaXI/Ashita-v4beta/blob/main/addons/libs/ffxi/itemdata.lua)
- Each structure defines `to/fromTable` to handle interfacing with lua the exdata
- LLS is set to strongly enforce the definition of the table when passed to either `addItem or setExData`
- A fallback mechanism remains available for _odd items_ like Tredecim Scythe
- Item exdata is saved on tick end and streamed to the client through an ITEM_ATTR packet
  - No longer need to drop items and create new ones when just modifying exdata.
  - *This will have the side effect of streaming normally hidden exdata (WS unlock points) to the client*. I will address that separately.
  - Closes #9257

This is what the dispatch looks like with the entirety of the code that's not in this PR

```cpp
auto getType(const CItem* item) -> Type
{
    if (!item)
    {
        return Type::None;
    }

    const auto itemId = item->getID();

    // Linkshell
    if (item->isType(ITEM_LINKSHELL))
    {
        return Type::Linkshell;
    }

    // Furnishing types - check specific IDs first
    if (item->isType(ITEM_FURNISHING))
    {
        if (item->isMannequin())
        {
            return Type::Mannequin;
        }

        if (isFlowerpot(itemId))
        {
            return Type::FlowerPot;
        }

        return Type::Furniture;
    }

    // Fish items
    if (fishingutils::IsFish(item))
    {
        return Type::Fish;
    }

    if (itemId == COPY_OF_THE_WYVERN_CODEX || itemId == COPY_OF_THE_GRIFFON_CODEX ||
        (itemId >= COPY_OF_THE_BALLISTA_REDBOOK && itemId <= PAGE_OF_THE_BALLISTA_WHITEBOOK) ||
        (itemId >= BRENNER_BLUEBOOK && itemId <= BRENNER_BLACKBOOK_PAGE))
    {
        return Type::BrennerBook;
    }

    if (itemId == CHOCOBET_TICKET)
    {
        return Type::BettingSlip;
    }

    if (itemId == RACE_COMPLETION_CERTIFICATE)
    {
        return Type::RaceCertificate;
    }

    if (itemId == VCS_HONEYMOON_TICKET)
    {
        return Type::HoneymoonTicket;
    }

    if (itemId >= DILIGENCE_GRIMOIRE && itemId <= SANCTITY_GRIMOIRE)
    {
        return Type::MeebleGrimoire;
    }

    if (itemId == SOUL_PLATE || itemId == GAUGER_PLATE || itemId == FIEND_PLATE)
    {
        return Type::SoulPlate;
    }

    if (itemId == SOUL_REFLECTOR || itemId == OFFICIAL_SOUL_REFLECTOR)
    {
        return Type::SoulReflector;
    }

    if (itemId >= LEUJAOAM_OBSERVATION_LOG && itemId <= ILRUSI_TRAVEL_LEDGER)
    {
        return Type::AssaultLog;
    }

    if (itemId == BONANZA_PEARL || itemId == MOG_BONANZA_MARBLE)
    {
        return Type::LotteryTicket;
    }

    if ((itemId >= MAZE_TABULA_M01 && itemId <= MAZE_TABULA_M03) ||
        (itemId >= MAZE_TABULA_R01 && itemId <= MAZE_TABULA_R03))
    {
        return Type::Tabula;
    }

    if (itemId == EVOLITH)
    {
        return Type::Evolith;
    }

    if (itemId >= WOODWORKING_SET_25 && itemId <= COOKING_SET_95)
    {
        return Type::CraftingSet;
    }

    // Crafting shields: Aspis(+0), Ecu(+1), Scutum(+2), Shield(+3) per guild.
    // Escutcheon(+4) is the finished item and has no crafting exdata.
    if (itemId >= JOINERS_ASPIS && itemId <= CHEFS_SHIELD &&
        (itemId - JOINERS_ASPIS) % 5 != 4)
    {
        return Type::CraftingShield;
    }

    if (itemId == PERPETUAL_HOURGLASS)
    {
        return Type::PerpetualHourglass;
    }

    if (itemId == GLOWING_LAMP)
    {
        return Type::GlowingLamp;
    }

    if (itemId == LEGION_PASS)
    {
        return Type::LegionPass;
    }

    if (itemId == LU_SHANGS_FISHING_ROD_P1 || itemId == EBISU_FISHING_ROD_P1)
    {
        return Type::Serialized;
    }

    if (itemId == CHOCOBO_EGG_FAINTLY || itemId == CHOCOBO_EGG_SLIGHTLY ||
        (itemId >= CHOCOBO_EGG_A_BIT && itemId <= CHOCOBO_EGG_SOMEWHAT))
    {
        return Type::ChocoboEgg;
    }

    if (itemId == VCS_REGISTRATION_FORM || itemId == CHOCOCARD_M ||
        itemId == CHOCOCARD_F || itemId == CRA_RACING_FORM)
    {
        return Type::ChocoboCard;
    }

    // Charged items (equipment or usable) use timer exdata
    if (item->isSubType(ITEM_CHARGED))
    {
        return Type::Usable;
    }

    // Weapons with WS unlock points use their own exdata layout
    if (item->isType(ITEM_WEAPON))
    {
        auto* PWeapon = static_cast<const CItemWeapon*>(item);
        if (PWeapon->isUnlockable())
        {
            return Type::WeaponUnlock;
        }
    }

    // Equipment with augments
    if (item->isType(ITEM_EQUIPMENT))
    {
        return Type::Augment;
    }

    // Storage slips use a raw 192-bit bitmask with no typed handler
    if (item->isStorageSlip())
    {
        return Type::None;
    }

    // Usable items (non-charged, like scrolls)
    if (item->isType(ITEM_USABLE))
    {
        return Type::Usable;
    }

    return Type::None;
}
```

## Steps to test these changes
xi_test shows usage. Retested Tredecim Scythe, Magian etc.

### CODE REVIEW

File: src/map/lua/lua_item.cpp [hunk 1]
```diff
@@ -365,31 +370,60 @@ auto CLuaItem::getSoulPlateData() -> sol::table
...
 
-auto CLuaItem::getExData() -> sol::table
+/************************************************************************
+ *  Function: getExData()
+ *  Purpose : Returns the item's extra data as a typed table, or raw bytes.
+ *  Example : item:getExData()     -- typed table (e.g. ExdataLegionPass)
+ *          : item:getExData(true) -- raw 0-indexed byte table
+ *  Notes   : When raw is set, returns all 24 bytes keyed 0..23.
+ ************************************************************************/
+auto CLuaItem::getExData(sol::optional<bool> raw) const -> sol::table
```
Comment (zach2good) [inline src/map/lua/lua_item.cpp]: Can we replace this with an enum, or have two bindings: getExData and getExDataRaw, etc. - it's hard to infer at the callsite wha this bool is for

**Review by zach2good — APPROVED** [review]

File: src/map/lua/lua_item.cpp (hunk 1 above)
Comment (sruon) [reply src/map/lua/lua_item.cpp]: I separated the bindings.
