### PR TITLE
[Fix] ToAU mission 1 CS getting hanged and re-define CS trigger region

### LINKED ISSUE #553: TOAU Mission 1 Cutscene messed up
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x ] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x ] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [ x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [ ] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
When approaching the trigger for Mission 1, character freezes, but cutscene doesn't start. First time, the client crashed. Logging back in, character froze after a few seconds. After a few minutes, received key item Supplies Package without any cutscene, and character moved again.

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

As title suggests. closes #553

Reminder: The last parameter needs to be set to 0. Aht uhrgan whitegate events seemingly need them to not hang.

The CS doesnt trigger as fast as desired, wich should be in the middle of the ramp, but it will not trigger outside the building anymore, at least.

### CODE REVIEW

File: scripts/missions/toau/01_Land_of_Sacred_Serpents.lua [hunk 1]
```diff
@@ -32,13 +32,10 @@ mission.sections =
...
         [xi.zone.AHT_URHGAN_WHITEGATE] =
         {
-
-            -- TODO: Edit region defined in Aht Urghan Whitegate, becouse as of now, it is incorrect.
-            -- CS should trigger in the ramp inside Naja Salaheem building.
             onRegionEnter =
             {
                 [3] = function (player, csid, option, npc)
-                    return mission:progressEvent(3000)
+                    return mission:progressEvent(3000, 0, 0, 0, 0, 0, 0, 0, 0, 0)
```
Comment (KnowOne134) [inline scripts/missions/toau/01_Land_of_Sacred_Serpents.lua:40]: Did you guys take in the csid changes from eden?
(Csid, {[8] = 0})

Comment (Xaver-DaRed) [reply scripts/missions/toau/01_Land_of_Sacred_Serpents.lua:40]: We seemingly didnt.

Comment (zach2good) [reply scripts/missions/toau/01_Land_of_Sacred_Serpents.lua:40]: We can go ahead with these changes and I'll PR an equivalent for sol in the next couple of days. Would appreciate a comment saying that Naja's interactions all need the text Table set to zero (8th Cs arg)

Comment (Xaver-DaRed) [reply scripts/missions/toau/01_Land_of_Sacred_Serpents.lua:40]: Added some comments to mission and Naja's Scripts

**Review by claywar — APPROVED** [review]
