### PR TITLE
[core] Allow targetfind to reject matching allegiances for ENEMY search

### LINKED ISSUE #5618: 🐛 [CRASH] Server crashes when a player gets charmed while a mob is readying Sweep
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)
Windows 11

## Branch affected by issue 

`base`

## Steps to reproduce
I have not found any other skill or combination this works with. We have been getting occasional silent crashes in Dynamis for some time now and its due to a player getting charmed during a readying sweep skill. The best way to reproduce this is this:

You can either go into Dynamis Windurst or Castle O.
Aggro a bunch of yagudo
For a guaranteed crash you need to turn off all the other mobskills other than sweep.
`!setmod regain 3000` on all the mobs that are attacking you except one
Use `!exec target:useMobAbility(710)` on the mob that does not have 3k regain. This will replicate a charmed 2hr from a beastmaster that happens in Dynamis Windurst.
See crash.

image

## Expected behavior
Not crash

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

This fixes an issue where due to some odd conditions Yagudo could sweep themselves, stun themselves, and break their states causing a crash.
Fixes #5618 

## Steps to test these changes

See #5618
Also test bomb toss suicide `!exec target:useMobAbility(592)` and see it works
Test moonlight, curaga, firaga, see them all work.

### CODE REVIEW

**Review by Xaver-DaRed — DISMISSED** [review]

**Comment by WinterSolstice8** [comment]
This touches a lot of stuff, gotta make sure it doesn't break anything, added hold label

**Review by zach2good — DISMISSED** [review]

**Comment by WinterSolstice8** [comment]
Yup looks like some stuff broke because targetflags != findflags. it fixed my exact bug but some AoEs stopped working. Time to add targetflags into targetfind

We already do some jank conversions from targetflags -> findflags, so makes me wonder if it just should have been this way to begin with...

**Comment by WinterSolstice8** [comment]
Alright, go ahead and re-review. had to touch more stuff

File: src/map/ai/helpers/targetfind.cpp [hunk 1]
```diff
@@ -70,22 +70,23 @@ void CTargetFind::reset()
     m_PMasterTarget = nullptr;
 }
 
-void CTargetFind::findSingleTarget(CBattleEntity* PTarget, uint8 flags)
```
Comment (TeoTwawki) [inline src/map/ai/helpers/targetfind.cpp:73]: 👍 
HATE it when old code doesn't say what _WHAT_ flags are being passed along

**Review by TeoTwawki — APPROVED** [review]

File: src/map/ai/controllers/mob_controller.cpp [hunk 2]
```diff
@@ -531,7 +531,7 @@ void CMobController::CastSpell(SpellID spellid)
                 {
                     // chance to target party
                     PMob->PAI->TargetFind->reset();
-                    PMob->PAI->TargetFind->findWithinArea(PMob, AOE_RADIUS::ATTACKER, PSpell->getRange());
+                    PMob->PAI->TargetFind->findWithinArea(PMob, AOE_RADIUS::ATTACKER, PSpell->getRange(), 0, 0);
```
Comment (zach2good) [inline src/map/ai/controllers/mob_controller.cpp]: Can we use the enum values here instead of 0s please?

FINDFLAGS_NONE etc

**Review by zach2good — APPROVED** [review]

File: src/map/ai/controllers/mob_controller.cpp (hunk 2 above)
Comment (WinterSolstice8) [reply src/map/ai/controllers/mob_controller.cpp]: there isnt an enum for targettype value 0

Comment (WinterSolstice8) [reply src/map/ai/controllers/mob_controller.cpp]:
```
enum TARGETTYPE
{
    TARGET_SELF                    = 0x01,
    TARGET_PLAYER_PARTY            = 0x02,
    TARGET_ENEMY                   = 0x04,
    TARGET_PLAYER_ALLIANCE         = 0x08,
    TARGET_PLAYER                  = 0x10,
    TARGET_PLAYER_DEAD             = 0x20,
    TARGET_NPC                     = 0x40, // an npc is a mob that looks like an npc and fights on the side of the character
    TARGET_PLAYER_PARTY_PIANISSIMO = 0x80,
    TARGET_PET                     = 0x100,
    TARGET_PLAYER_PARTY_ENTRUST    = 0x200,
    TARGET_IGNORE_BATTLEID         = 0x400, // Can hit targets that do not have the same battle ID
};
```

Comment (zach2good) [reply src/map/ai/controllers/mob_controller.cpp]: No reason you can't add `FINDFLAGS_NONE`, rather than piping in a raw number that means the same thing

Comment (zach2good) [reply src/map/ai/controllers/mob_controller.cpp]: or `TARGET_NONE`, whatever

Comment (zach2good) [reply src/map/ai/controllers/mob_controller.cpp]: Then the storage and the argument types become the enum:

```
    FIND_TYPE m_findType;
    FINDFLAGS    m_findFlags;   // what to search for
    TARGETTYPE    m_targetFlags; // targetflags to reject potentially bad targets
```

Comment (WinterSolstice8) [reply src/map/ai/controllers/mob_controller.cpp]: > Then the storage and the argument types become the enum:
> 
> ```
>     FIND_TYPE m_findType;
>     FINDFLAGS    m_findFlags;   // what to search for
>     TARGETTYPE    m_targetFlags; // targetflags to reject potentially bad targets
> ```
Apparently implementing this is editing a _ton_ of stuff and I don't really have time to test every single permutation of spell/ability/mobskill/petskill right now

I've made the other changes asked of, though.

Comment (zach2good) [reply src/map/ai/controllers/mob_controller.cpp]: Yeah, that one was a "we should probably do this at some point" thing, currently looks good 👍
