### PR TITLE
[core, sql] Status effect wear off messages, ON_ZONE flags

### LINKED ISSUE #8898: Certain Effects should be lost when Zoning
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Win11

## Branch affected by issue 

`base`

## Steps to reproduce

1) Cast Spell\Use JA for effect that should normally be lost on zoning (Example: Temper, Enfire, Phalanx, Divine Caress, etc) then zone. See that the effect persists when it should wear off.

## Expected behavior

Certain Effects should be lost upon zoning.

**Note:** I have made a spreadsheet testing every effect on retail we currently list in status_effects.sql and recorded results here: https://docs.google.com/spreadsheets/d/1-bVC03O9w8V7kRDWPN8qxQbaqqd2af9uvwF-XiBMbS4/edit?usp=sharing - columns are labeled to indicate correct behavior, if column G is 0 it means retail and LSB match, otherwise it's incorrect.

However, a giant caveat is that some effects may be both. Example: Stat Boosts gained from absorb-stat, Ecliptic Growl (Fenrir), and Glittering Ruby (Carbuncle) do not wear on zone, however Gain/Boost-Stat(WHM/RDM) does wear on zone. Which most likely means that we need to handle when something should wear off on individual effects at the spell\ability level rather than globally in status_effects.sql

### PR DESCRIPTION
**Pull request by sruon**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
- Adds a new column to override the wear off message for status effects
  - After going through the motions I'm not even sure it was required to begin with because everything is either message 204 or 206 but might be useful later on...
- Adds the correct message ID for certain status effects wearing off
  - Tested what I could myself, used Youtube videos for a few and made some assumptions about a limited number. Likely not ENTIRELY accurate.
- Defines the flags explicitly in the SQL file
- Adds ON_ZONE flag to a lot of status effects 
  - [As captured by](https://docs.google.com/spreadsheets/d/1-bVC03O9w8V7kRDWPN8qxQbaqqd2af9uvwF-XiBMbS4/edit?gid=381076942#gid=381076942) @siknoz 
  - Skipped everything that said "N/A" in the retail column for the time being
- Sets the correct "caster" entity in the wear off message, as observed on retail 
  - Makes no visual difference but I don't think filters can work correctly otherwise.

Maybe closes #8898 - need another pass

### CODE REVIEW

File: sql/status_effects.sql [hunk 1]
```diff
@@ -38,641 +71,641 @@ CREATE TABLE `status_effects` (
...
+INSERT INTO `status_effects` VALUES (148,'evasion_down',@FLAG_ERASABLE | @FLAG_DEATH | @FLAG_ON_ZONE | @FLAG_WALTZABLE | @FLAG_NO_CANCEL,0,0,0,0,92,2,0,0,NULL);
+INSERT INTO `status_effects` VALUES (149,'defense_down',@FLAG_ERASABLE | @FLAG_DEATH | @FLAG_ON_ZONE | @FLAG_WALTZABLE | @FLAG_NO_CANCEL,0,0,0,0,93,3,0,0,NULL);
+INSERT INTO `status_effects` VALUES (150,'physical_shield',@FLAG_DISPELABLE | @FLAG_EMPATHY | @FLAG_DEATH,0,0,0,0,0,0,0,0,NULL);
+INSERT INTO `status_effects` VALUES (151,'arrow_shield',@FLAG_DISPELABLE | @FLAG_DEATH,0,0,0,0,0,0,0,0,NULL);
+INSERT INTO `status_effects` VALUES (152,'magic_shield',@FLAG_DISPELABLE | @FLAG_EMPATHY | @FLAG_DEATH,0,0,0,0,0,0,0,0,NULL);
+INSERT INTO `status_effects` VALUES (153,'damage_spikes',@FLAG_DISPELABLE | @FLAG_EMPATHY | @FLAG_DEATH,34,0,0,0,0,0,0,800,NULL);
+INSERT INTO `status_effects` VALUES (154,'shining_ruby',@FLAG_DISPELABLE | @FLAG_EMPATHY | @FLAG_DEATH | @FLAG_ON_ZONE,0,0,0,0,0,0,0,0,NULL);
+INSERT INTO `status_effects` VALUES (155,'medicine',0,0,0,0,0,0,0,0,0,204);
```
Comment (almuth150) [inline sql/status_effects.sql:225]: I just noticed that this status has no flags. I checked with a test server and couldn't manually remove the status with the client normally, so maybe this status should have the no cancel flag? I can't check on retail though. But surely the status that prevents you from using certain powerful meds repeatedly shouldn't be able to be removed by the player.

Edit: It looks like there are more statuses that lack that flag, so I'm going to open a separate issue. Ignore this for this PR.

**Review by WinterSolstice8 — APPROVED** [review]
