### PR TITLE
[Interaction] Fix some issues in all 3 Magicite missions.

### LINKED ISSUE #1115: [Missions] Nation Magicite mission reward gil duping
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

One of our players reported this:

"once you complete the mission magicite, you can check on the door of the ru'lude palace as many times as you want and keep getting 20k gil"

He is Sandorian fyi.

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

Fix CS at palace door being able to be repeated.
Fix being able to re-obtain magicite KIs.

Closes #1115

### CODE REVIEW

**Review by zach2good — APPROVED** [review]

File: scripts/missions/bastok/4_1_Magicite.lua [hunk 1]
```diff
@@ -131,6 +131,7 @@ mission.sections =
 
                     player:addTitle(xi.title.HAVE_WINGS_WILL_FLY)
                     player:setMissionStatus(mission.areaId, 6)
+                    mission:setVar(player, 'Stage', 0)
```
Comment (claywar) [inline scripts/missions/bastok/4_1_Magicite.lua]: Just for continuity's sake, I would suggest we set Stage to 4 here, even though it is unchecked

**Review by claywar — APPROVED** [review]

File: scripts/missions/bastok/4_1_Magicite.lua (hunk 1 above)
Comment (Xaver-DaRed) [reply scripts/missions/bastok/4_1_Magicite.lua]: This variable was removed entirely with the rewrite
