### PR TITLE
[lua] Adjust Extravaganza code to allow the non-existence of NPCs

### LINKED ISSUE #9133: 🐛 Conquest NPCs are unresponsive
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 11

## Branch affected by issue 

`base`

## Steps to reproduce

Tried talking to various Conquest/Signet NPCs in Windurst and Jeuno, none are responding to attempts to interact. As there was no issue yesterday, perhaps it's an issue with the version update?

## Expected behavior

NPCs should respond to interaction.

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Closes #9133 

## Steps to test these changes

Talk to conquest NPC and they respond

### CODE REVIEW

**Review by Xaver-DaRed — DISMISSED** [review]

File: scripts/globals/extravaganza.lua [hunk 1]
```diff
@@ -14,12 +14,14 @@ xi.extravaganza.campaign =
...
 }
 
+---@return number
 xi.extravaganza.campaignActive = function()
     -- Extravaganza NPCs are currently not present in the client.  This function is disabled until
     -- such a time that they are reintroduced, or confirmed to be permanently removed.  If this changes,
     -- return to using xi.settings.main.ENABLE_TRUST_ALTER_EGO_EXTRAVAGANZA
 
-    return false
+    -- Math is used on this in events, this must return a 0 or 1
```
Comment (zach2good) [inline scripts/globals/extravaganza.lua]: I'd argue that the bool typing is fine, and it should be up to the caller to use `xi.extravaganza.campaignActive() and 1 or 0` if they want to do maths on it.

If we lint this as returning a bool, LLS will do the rightful complaining

Comment (WinterSolstice8) [reply scripts/globals/extravaganza.lua]: Apparently, this was supposed to return an enum, i've adjusted this. The math performed was based on the setting

```lua
xi.extravaganza.campaign =
{
    NONE        =   0,
    SUMMER_NY   =   1,
    SPRING_FALL =   2,
    BOTH        =   3,
}
```

I've added the typing to enum and made the function also return that enum

**Comment by WinterSolstice8** [comment]
Need a re-review (I've changed a bit more)

**Review by Xaver-DaRed — APPROVED** [review]
