### PR TITLE
[core] Add CBattleEntity hasEnmity function

### LINKED ISSUE #6130: 🐛 Mount command does not respect gained enmity
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows 11
## Branch affected by issue 

`base`

```Hax : !build
----== SystemMessage ==----
base-be17f7f3c3
Merge pull request #6121 from TiberonKalkaz/youre_a_wzard_galkas
Mon Aug 19 03:12:19 2024

client version
version 30240806_0
```    

## Steps to reproduce

- Gain agro / enmity from a monster
- Use mount

Video
https://cdn.discordapp.com/attachments/1095358627520458832/1275201865424048290/2024-08-19_15-52-37.mkv?ex=66c507c8&is=66c3b648&hm=20a9270f0702272bdb6c0d7f862c49256d9756ced07dc4505be6d8463dd96c59&
## Expected behavior
Players should not be able to use mounts with gained enmity.
> You are unable to mount while on a monster’s enmity list.
https://www.bg-wiki.com/ffxi/Category:Mounts

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Fixes #6130

## Steps to test these changes
Aggro a mob, target yourself, see `!exec print(target:hasEnmity())` print true
Charm a mob, have your pet attack attack a mob and gain enmity, repeat !exec, see it return true
repeat for trusts

Normal pets, for some reason, don't get their notoriety container updated with things that don't like them. I don't know if that's intended or not, but it's out of scope. If a mob is directly attacking them the new function returns true. I think this is an acceptable edge case for now.

Aggro a mob, try to use /mount or summon a trust, see it fail

### CODE REVIEW

File: src/map/entities/battleentity.cpp [hunk 1]
```diff
@@ -2691,3 +2691,32 @@ uint16 CBattleEntity::GetBattleTargetID() const
 {
     return m_battleTarget;
 }
+
+bool CBattleEntity::hasEnmity() const
```
Comment (zach2good) [inline src/map/entities/battleentity.cpp]: I know this is going to be very ugly, but to sell how expensive this is (iterating possibly every mob in the zone if you aren't targetted) - can you call this `hasEnmityEXPENSIVE()` to make sure nobody uses it somewhere hot by accident?

File: src/map/entities/battleentity.cpp [hunk 2]
```diff
@@ -2691,3 +2691,32 @@ uint16 CBattleEntity::GetBattleTargetID() const
...
+        return true;
+    }
+
+    bool isTargeted = false;
+
+    // TODO: this is bad but because of how super tanking is implemented there's not much we can do without a larger refactor
+    if (loc.zone)
+    {
+        // clang-format off
+        loc.zone->ForEachMob([&](CMobEntity* PMob)
```
Comment (zach2good) [inline src/map/entities/battleentity.cpp:2709]: When we eventually have spatial partitioning, we can do that sort of iteration here

Comment (WinterSolstice8) [reply src/map/entities/battleentity.cpp:2709]: I don't think that will work here, because theoretically you could sleep a mob and Flee 100' away and it would STILL be mad at you

File: src/map/entities/battleentity.cpp (hunk 1 above)
Comment (WinterSolstice8) [reply src/map/entities/battleentity.cpp]: sure, that works for me. I think the better longer-term fix here is to make a clone of the Notoriety Container but it only contains mobs that have aggroed you through PAI->Engage

Comment (zach2good) [reply src/map/entities/battleentity.cpp]: Yeah, thats the right answer ^

Comment (WinterSolstice8) [reply src/map/entities/battleentity.cpp]: The good news is this hasEnmity is sparsely used and only on-demand (trying to mount chocobo, call trust, use a chocobo whistle). All of these are rate limited by the client and/or other systems, so there's little risk of this being overused every tick

Comment (WinterSolstice8) [reply src/map/entities/battleentity.cpp]: Updated function name

**Review by zach2good — APPROVED** [review]
