### PR TITLE
[quest] Beadeaux Smog rewrite

### LINKED ISSUE #784: When you talk to the NPC "High Bear" in Metalworks, it may not respond.
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: EDITME

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

In onTrigger, there seems to be a case where none of the following conditional statements are satisfied.
```
    if (BeaSmog == QUEST_AVAILABLE and player:getFameLevel(BASTOK) >= 4) then
        player:startEvent(731)
    elseif (BeaSmog == QUEST_ACCEPTED and keyitem == false or BeaSmog == QUEST_COMPLETED) then
        player:startEvent(730)
    elseif (BeaSmog == QUEST_ACCEPTED and keyitem == true) then
        player:startEvent(732)
    end
```

Maybe you can write cs 730 for the default dialog in "DefaultActions.lua".

### PR DESCRIPTION
**Pull request by zach2good**
Fixes https://github.com/LandSandBoat/server/issues/784

WIP: Started on stream, but needs caps for the qm and maybe checking the cs's and texts etc.

**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by zach2good** [comment]
It appears as though the npc entries for Beadeaux are messed up, with Shiny Orcs appearing where qm's should be. 
From my caps, the qm was qm1, but it was originally programmed for qm2. There is a chance that these qm's rotate which one appears when it rains...
Also added `FOUL_SMELLING_SOIL_IS_SPILLING_OUT` text ID, all seems OK

File: sql/npc_list.sql [hunk 1]
```diff
@@ -18201,11 +18201,11 @@ INSERT INTO `npc_list` VALUES (17379858,'Moogle','Moogle',0,0.000,0.000,0.000,0,
 INSERT INTO `npc_list` VALUES (17379859,'Moogle','Moogle',0,0.000,0.000,0.000,0,40,40,0,0,0,6,2051,0x0000520000000000000000000000000000000000,0,NULL,0);
 INSERT INTO `npc_list` VALUES (17379860,'GeFhu_Yagudoeye','Ge\'Fhu Yagudoeye',236,-91.354,-3.251,-127.831,25,40,40,0,0,0,0,27,0x00008A0200000000000000000000000000000000,0,NULL,1);
 INSERT INTO `npc_list` VALUES (17379861,'Zeelozok','Zeelozok',165,-58.092,0.788,-182.088,0,40,40,0,0,0,6,27,0x0000D70300000000000000000000000000000000,0,NULL,1);
-INSERT INTO `npc_list` VALUES (17379862,'qm3','???',163,-49.783,1.750,-190.385,0,40,40,0,0,0,6,27,0x00008A0200000000000000000000000000000000,0,NULL,0);
-INSERT INTO `npc_list` VALUES (17379863,'qm4','???',150,-54.635,0.879,-185.403,0,40,40,0,0,0,6,27,0x00008A0200000000000000000000000000000000,0,NULL,0);
```
Comment (TeoTwawki) [inline sql/npc_list.sql:18205]: Guessing an ID shift in the distant past, or a copy paste error hit these once upon a time..coz 8A02 (`!costume 650`) is a generic Quadav model.

**Review by claywar — APPROVED** [review]
