### PR TITLE
[lua, sql] Align SMN BP range, add base enmity on BP usage

### LINKED ISSUE #7738: 🐛 Smn BP:Rage doesn't add smn to enmity table
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

In retail, if you assault with your pet, then release it, the mob will chase you. LSB has this behavior

In retail, if you bp:rage a target, then release it, the mob will behave the same way.

In LSB, the mob just goes back to roaming:

Image

## Expected behavior

Whatever places the smn on the enmity table from assault should happen from bp:rage as well.

It's not CE/VE:

Image

Unsure what it is, but something makes the mob turn to the owner from assault, but that isn't triggering from bp:rage

### PR DESCRIPTION
**Pull request by sruon**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?
- Add base enmity to the summoner (0 CE / 0 VE but on aggro list) when using a blood pact targeting a mob. Closes #7738 
  - I have verified this only applies to the main target. AoE targets will ignore the summoner.
- Align Blood Pact abilities in abilities and pet_skills table (to the lowest values, which were in pet_skills)
  - While testing above change, I noticed retail is much more strict on letting a BP start, based on pet<>target distance. 
  - Discovered the code is actually checking both of those tables at different times (abilities when the summoner issues the command/pet_skills when the pet fires it), leading to "Too far away" messages.

Query for reference

```
SELECT a.abilityId, a.name, a.range, ps.pet_skill_distance
FROM abilities a
         JOIN pet_skills ps ON a.abilityId = ps.pet_skill_id
WHERE (a.range != ps.pet_skill_distance)
  AND (ps.pet_skill_flag & 194) != 0;
```

## Steps to test these changes
- Use BP on a mob (without Assault)
- Release avatar
- Mob is now chasing you

### CODE REVIEW

File: scripts/globals/job_utils/summoner.lua [hunk 1]
```diff
@@ -232,6 +232,11 @@ xi.job_utils.summoner.onUseBloodPact = function(target, petskill, summoner, acti
     if target:getID() == action:getPrimaryTargetID() then
         -- MP and Cooldown is only consumed if the ability goes off
         summoner:delMP(mpCost)
+
```
Comment (MowFord) [inline scripts/globals/job_utils/summoner.lua:235]: Is this how retail works? Being on the enmity list means using other abilities now generates enmity 

I wonder if the notoriety list is more appropriate

Comment (sruon) [reply scripts/globals/job_utils/summoner.lua:235]: base enmity is just terribly named, it's the same state as if you had aggrod the mob, ie supertanking. Subsequent actions do not build enmity

Comment (MowFord) [reply scripts/globals/job_utils/summoner.lua:235]: Very cool, thanks for clarification

**Review by Xaver-DaRed — APPROVED** [review]
