### PR TITLE
Fix item enchantments, add Haste Belt and Regen Collar

### LINKED ISSUE #5768: 🐛 Regen collar should stack with REGEN spell
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

Here is a capture of using a regen collar while having the regen spell effect on:

casting regen:
image

Using Regen Collar:
image

Updated effects:
image

### PR DESCRIPTION
**Pull request by overefined**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Fixes a path variable and condition in CStatusEffectContainer::SetEffectParams that prevented item enchantments from working.

Haste Belt now gives enchantment haste instead spell haste. This effect will stack with the spell haste. Effect is removed when belt is unequipped.

Regen Collar now gives enchantment regen instead spell regen. This effect will stack with the spell regen. Effect is removed when collar is unequipped.

Closes: https://github.com/LandSandBoat/server/issues/5768
## Steps to test these changes

!additem 15526
!getmod 370

!additem 15290
!getmod 384

### CODE REVIEW

**Comment by overefined** [comment]
Is this is the wrong path?
Untitled

Screenshot 2025-04-13 185625

File: scripts/items/haste_belt.lua [hunk 1]
```diff
@@ -6,18 +6,26 @@
 ---@type TItem
 local itemObject = {}
 
-itemObject.onItemCheck = function(target, item, param, caster)
+itemObject.onItemCheck = function(target)
+    if target:getStatusEffectBySource(xi.effect.ENCHANTMENT, xi.effectSourceType.EQUIPPED_ITEM, xi.item.HASTE_BELT) ~= nil then
+        target:delStatusEffect(xi.effect.ENCHANTMENT, nil, xi.effectSourceType.EQUIPPED_ITEM, xi.item.HASTE_BELT)
+    end
+
```
Comment (Xaver-DaRed) [inline scripts/items/haste_belt.lua:12]: The effect shouldnt be removed here, it should be removed in onItemUse

File: scripts/items/haste_belt.lua [hunk 2]
```diff
@@ -6,18 +6,26 @@
...
 end
 
 itemObject.onItemUse = function(target)
     if target:hasEquipped(xi.item.HASTE_BELT) then
-        if not target:hasStatusEffect(xi.effect.HASTE) then
-            target:addStatusEffect(xi.effect.HASTE, 1000, 0, 180, 0, 0, 0, xi.effectSourceType.EQUIPPED_ITEM, xi.item.HASTE_BELT)
-        else
-            target:messageBasic(xi.msg.basic.NO_EFFECT)
-        end
+        target:addStatusEffect(xi.effect.ENCHANTMENT, 0, 0, 180, 0, 0, 0, xi.effectSourceType.EQUIPPED_ITEM, xi.item.HASTE_BELT)
```
Comment (Xaver-DaRed) [inline scripts/items/haste_belt.lua:19]: Right before this line

File: scripts/items/regen_collar.lua [hunk 3]
```diff
@@ -6,18 +6,31 @@
 ---@type TItem
 local itemObject = {}
 
-itemObject.onItemCheck = function(target, item, param, caster)
+itemObject.onItemCheck = function(target)
+    print('onItemCheck')
+    if target:getStatusEffectBySource(xi.effect.ENCHANTMENT, xi.effectSourceType.EQUIPPED_ITEM, xi.item.REGEN_COLLAR) ~= nil then
+        target:delStatusEffect(xi.effect.ENCHANTMENT, nil, xi.effectSourceType.EQUIPPED_ITEM, xi.item.REGEN_COLLAR)
+    end
+
```
Comment (Xaver-DaRed) [inline scripts/items/regen_collar.lua:12]: Same here. Also, remember to remove the prints once you are done

File: scripts/items/haste_belt.lua (hunk 1 above)
Comment (Xaver-DaRed) [reply scripts/items/haste_belt.lua:12]: You do need the `return 0`

Comment (Xaver-DaRed) [reply scripts/items/haste_belt.lua:12]: And please dont remove the function parameters, even if not used

**Review by zach2good — APPROVED** [review]

**Review by Xaver-DaRed — APPROVED** [review]
