### PR TITLE
[lua] Implement high/low pdif rolls for melee

### LINKED ISSUE #9783: 🐛 Physical Damage Overflow Issue
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## OS / platform the server is running (if known)

Windows11

## Branch affected by issue 

`base`

## Steps to reproduce

Engage a monster that's 11 levels or higher than your main job.  When you hit, notice that your attack will occasionally deal ~65535 damage.

## Expected behavior

Auto-attack damage for a low-level character in this sort of situation should be 0-10.  It seems the level difference adjustment is pushing pDIF down low enough to become negative, resulting in a kind of overflow effect.  It looks like a missing 0 damage floor assignment in physical_utilities.lua.

### PR DESCRIPTION
**Pull request by WinterSolstice8**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Implements the 50/50 high/low pdif selector for super low pdif values based on source cited in the code and word from Jimmayus (and other math nerds)

Fixes #9783

## Steps to test these changes
Have ultra low pdif (1 attack vs 20k+ def mob), sometimes hit for non-zero with at ( weapon damage minus fstr) * .5 *1.05 and half of the time for zero

22 base damage weapon:
image

### CODE REVIEW

File: scripts/globals/combat/physical_utilities.lua [hunk 1]
```diff
@@ -658,10 +658,28 @@ xi.combat.physical.calculateMeleePDIF = function(actor, target, weaponType, wsAt
...
+        -- Rolled low, select the low end that clamps UL/LL to 0 minimum
+        upperBound = math.max(pDifUpperCap + levelDifFactor, 0.0)
+        lowerbound = math.max(pDifLowerCap + levelDifFactor, 0.0)
+    end
+
+    if upperBound == 0 then
+        return 0.0
+    else
+        pDif = math.random(lowerbound * 1000, upperBound * 1000) / 1000
+    end
```
Comment (Xaver-DaRed) [inline scripts/globals/combat/physical_utilities.lua:683]: Proposal:
```lua
local upperMax   = math.random(0, 1) == 0 and 0.5 or 0
local upperBound = math.max(pDifUpperCap + levelDifFactor, upperMax)
local lowerbound = math.max(pDifLowerCap + levelDifFactor, 0)

if upperBound == 0 then
    return 0
end

pDif = math.random(lowerbound * 1000, upperBound * 1000) / 1000
```

Comment (WinterSolstice8) [reply scripts/globals/combat/physical_utilities.lua:683]: yeah, works for me

File: scripts/globals/combat/physical_utilities.lua [hunk 2]
```diff
@@ -518,6 +518,37 @@ xi.combat.physical.wRatioCapOthers = function(wRatio, pDifFinalCap)
...
+
+        if wRatio > 0.0 and wRatio < 0.75 then
+            sRatio = -5 / 9 + (10 / 9) * wRatio
+        elseif wRatio <= 1.3 then
+            sRatio = 0.3
+        else
+            sRatio = 5 / 3 - (270 / 256) * wRatio
+        end
+
+        return utils.clamp(sRatio, 0, 0.3)
```
Comment (Xaver-DaRed) [inline scripts/globals/combat/physical_utilities.lua:546]: 0.3? Not 1/3?

Comment (WinterSolstice8) [reply scripts/globals/combat/physical_utilities.lua:546]: Per jimmayus's post, yeah.

Image

**Review by Xaver-DaRed — APPROVED** [review]
