### PR TITLE
[Interaction] Convert Limit Break Quests to interaction system.

### LINKED ISSUE #508: Lvl 90 Limit Break (Dormant Powers Dislodged) has only asked for Sunsand.
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: Everything

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Canaria server. Everything branch.

Lvl 90 Limit Break (Dormant Powers Dislodged) has only asked for Sunsand. There should be 14 different items, and it should ask for one randomly.

https://ffxiclopedia.fandom.com/wiki/Dormant_Powers_Dislodged

https://www.bg-wiki.com/ffxi/Dormant_Powers_Dislodged

### LINKED ISSUE #640: Level Cap 90 - Dormant Powers Dislodged Broken
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened
- [x] I have checked the commit log to see if the issue has been resolved since my server was last updated
- [x] I have read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)
- [x] I have specified what branch this happens on branch: base

When trading the requested items an having the required number of merit points, the cutscene doesn't play through. Camera can be spun around, but movement isn't allowed and items are not consumed. I have to quit the client to move around again.

### PR DESCRIPTION
**Pull request by Xaver-DaRed**
**_I affirm:_**
- [x] I have paid attention to this example and will edit again if need be to not break the formatting, or I will be ignored
- [x] that I agree to LandSandBoat's [Limited Contributor License Agreement](https://github.com/LandSandBoat/server/blob/base/.github/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I have **read the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md)**
- [x] that I've _**tested my code and things my code changed**_ since the last commit in the PR, and will test after any later commits

DONE:
- Conversion of LB 1 to 10, "Beyond the Sun" and "Prelude to Puissance" current implementation.
- Moved Limit Breaker and Job Breaker logic to quest scripts. Made sure it worked for era servers correctly.
- Added Maat trust. (Steps to obtain. Not the actual trust logic)
- Added minigame in LB9.
- Added variation in item requested in LB9

Closes #640
Closes #508

### CODE REVIEW

**Comment by kaincenteno** [comment]
Awesome work! Looks so much cleaner

File: scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua [hunk 1]
```diff
@@ -0,0 +1,267 @@
...
+-- qm9 : !pos 92.272 -32 -64.676 195
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/items")
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require("scripts/globals/titles")
+require('scripts/globals/interaction/quest')
+local ID = require("scripts/zones/RuLude_Gardens/IDs")
```
Comment (claywar) [inline scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua]: Could you name the ID var by zone to follow other scripts please?  (example: ruludeID)

File: scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua [hunk 2]
```diff
@@ -0,0 +1,267 @@
...
+-----------------------------------
+local quest = Quest:new(xi.quest.log_id.JEUNO, xi.quest.id.jeuno.IN_DEFIANT_CHALLENGE)
+-----------------------------------
+
+local function handleExorayMold(player)
+    if player:hasKeyItem(xi.ki.EXORAY_MOLD_CRUMB1) and
+        player:hasKeyItem(xi.ki.EXORAY_MOLD_CRUMB2) and
+        player:hasKeyItem(xi.ki.EXORAY_MOLD_CRUMB3)
+    then
+        npcUtil.giveItem(player, xi.items.CLUMP_OF_EXORAY_MOLD)
```
Comment (claywar) [inline scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua:35]: npcUtil.giveItem should probably be at the end of the above condition, that way it doesn't nuke out the keyitems should the player's inventory be full.  Lua will short-circuit out if any of the hasKeyItem calls fail before giveItem is hit.

File: scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua [hunk 3]
```diff
@@ -0,0 +1,267 @@
...
+        player:delKeyItem(xi.ki.EXORAY_MOLD_CRUMB3)
+    end
+end
+
+local function handleBombCoal(player)
+    if player:hasKeyItem(xi.ki.BOMB_COAL_FRAGMENT1) and
+        player:hasKeyItem(xi.ki.BOMB_COAL_FRAGMENT2) and
+        player:hasKeyItem(xi.ki.BOMB_COAL_FRAGMENT3)
+    then
+        npcUtil.giveItem(player, xi.items.CHUNK_OF_BOMB_COAL)
```
Comment (claywar) [inline scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua:48]: Same as above

File: scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua [hunk 4]
```diff
@@ -0,0 +1,267 @@
...
+        player:delKeyItem(xi.ki.BOMB_COAL_FRAGMENT1)
+        player:delKeyItem(xi.ki.BOMB_COAL_FRAGMENT2)
+        player:delKeyItem(xi.ki.BOMB_COAL_FRAGMENT3)
+    end
+end
+
+local function handleAncientPapyrus(player)
+    if player:hasKeyItem(xi.ki.ANCIENT_PAPYRUS_SHRED1) and
```
Comment (claywar) [inline scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua]: Same as above

File: scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua [hunk 5]
```diff
@@ -0,0 +1,267 @@
...
+            {
+                onTrigger = function(player, npc)
+                    return quest:progressEvent(79)
+                end,
+            },
+
+            onEventFinish =
+            {
+                [79] = function(player, csid, option, npc)
+                    if option ==  1 then -- Accept quest option.
```
Comment (claywar) [inline scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua]: Formatting (there's two spaces after the ==)

File: scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua [hunk 6]
```diff
@@ -0,0 +1,267 @@
...
+                        return quest:progressEvent(81)
+                    end
+                end,
+            },
+
+            onEventFinish =
+            {
+                [81] = function(player, csid, option, npc)
+                    if quest:complete(player) then
+                        player:tradeComplete()
```
Comment (claywar) [inline scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua]: Probably better to use player:confirmTrade() here

File: scripts/quests/jeuno/LB02_Atop_the_Highest_Mountains.lua [hunk 7]
```diff
@@ -0,0 +1,135 @@
...
+-- qm3 : !pos 580 -9 290 112
+-- qm4 : !pos -21 -25 -490 112
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require("scripts/globals/titles")
+require('scripts/globals/interaction/quest')
+local ruludeID = require("scripts/zones/RuLude_Gardens/IDs")
```
Comment (claywar) [inline scripts/quests/jeuno/LB02_Atop_the_Highest_Mountains.lua]: This is just being picky, but could you align the formatting for this section with other scripts for consistency?  IDs broken out, but no need to put comment lines around the quest constructor.

File: scripts/quests/jeuno/LB02_Atop_the_Highest_Mountains.lua [hunk 8]
```diff
@@ -0,0 +1,135 @@
...
+            {
+                onTrigger = function(player, npc)
+                    return quest:progressEvent(82)
+                end,
+            },
+
+            onEventFinish =
+            {
+                [82] = function(player, csid, option, npc)
+                    if option ==  1 then -- Accept quest option.
```
Comment (claywar) [inline scripts/quests/jeuno/LB02_Atop_the_Highest_Mountains.lua]: Formatting after the ==

File: scripts/quests/jeuno/LB02_Atop_the_Highest_Mountains.lua [hunk 9]
```diff
@@ -0,0 +1,135 @@
...
+                end,
+            },
+        },
+
+        [xi.zone.XARCABARD] =
+        {
+            ['qm2'] =
+            {
+                onTrigger = function(player, npc)
+                    if not player:hasKeyItem(xi.ki.ROUND_FRIGICITE) and
```
Comment (claywar) [inline scripts/quests/jeuno/LB02_Atop_the_Highest_Mountains.lua]: Could you fix this conditional formatting to follow the style guide?
```
if
    not condition and
    condition
then
```

File: scripts/quests/jeuno/LB02_Atop_the_Highest_Mountains.lua [hunk 10]
```diff
@@ -0,0 +1,135 @@
...
+                    then
+                        return npcUtil.giveKeyItem(player, xi.ki.ROUND_FRIGICITE)
+                    end
+                end,
+            },
+
+            ['qm3'] =
+            {
+                onTrigger = function(player, npc)
+                    if not player:hasKeyItem(xi.ki.SQUARE_FRIGICITE) and
```
Comment (claywar) [inline scripts/quests/jeuno/LB02_Atop_the_Highest_Mountains.lua]: Same as above

File: scripts/quests/jeuno/LB02_Atop_the_Highest_Mountains.lua [hunk 11]
```diff
@@ -0,0 +1,135 @@
...
+                    then
+                        return npcUtil.giveKeyItem(player, xi.ki.SQUARE_FRIGICITE)
+                    end
+                end,
+            },
+
+            ['qm4'] =
+            {
+                onTrigger = function(player, npc)
+                    if not player:hasKeyItem(xi.ki.TRIANGULAR_FRIGICITE) and
```
Comment (claywar) [inline scripts/quests/jeuno/LB02_Atop_the_Highest_Mountains.lua]: Same as above

File: scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua [hunk 12]
```diff
@@ -0,0 +1,133 @@
...
+-- qm2 (Castle Oztroja)   : !pos -100 -63 58 151
+-- qm1 (Qulun Dome)       : !pos 261 39 79 148
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require("scripts/globals/titles")
+require('scripts/globals/interaction/quest')
+local ID = require("scripts/zones/RuLude_Gardens/IDs")
```
Comment (claywar) [inline scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua]: ID variable and formatting (similar to previous script comments)

File: scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua [hunk 13]
```diff
@@ -0,0 +1,133 @@
...
+            {
+                onTrigger = function(player, npc)
+                    return quest:progressEvent(85)
+                end,
+            },
+
+            onEventFinish =
+            {
+                [85] = function(player, csid, option, npc)
+                    if option ==  1 then -- Accept quest option.
```
Comment (claywar) [inline scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua]: Formatting after ==

File: scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua [hunk 14]
```diff
@@ -0,0 +1,133 @@
...
+        check = function(player, status)
+            return status == QUEST_ACCEPTED
+        end,
+
+        [xi.zone.RULUDE_GARDENS] =
+        {
+            ['Maat'] =
+            {
+                onTrigger = function(player, npc)
+                    if player:hasKeyItem(xi.ki.ORCISH_CREST) and
```
Comment (claywar) [inline scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua]: Conditional formatting for style guide

File: scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua [hunk 15]
```diff
@@ -0,0 +1,133 @@
...
+                end,
+            },
+        },
+
+        [xi.zone.CASTLE_OZTROJA] =
+        {
+            ['qm2'] =
+            {
+                onTrigger = function(player, npc)
+                    if not player:hasKeyItem(xi.ki.YAGUDO_CREST) then
```
Comment (claywar) [inline scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua:102]: Conditional formatting

File: scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua [hunk 16]
```diff
@@ -0,0 +1,133 @@
...
+                end,
+            },
+        },
+
+        [xi.zone.MONASTIC_CAVERN] =
+        {
+            ['qm1'] =
+            {
+                onTrigger = function(player, npc)
+                    if not player:hasKeyItem(xi.ki.ORCISH_CREST) then
```
Comment (claywar) [inline scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua:114]: Conditional formatting

File: scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua [hunk 17]
```diff
@@ -0,0 +1,133 @@
...
+                end,
+            },
+        },
+
+        [xi.zone.QULUN_DOME] =
+        {
+            ['qm1'] =
+            {
+                onTrigger = function(player, npc)
+                    if not player:hasKeyItem(xi.ki.QUADAV_CREST) then
```
Comment (claywar) [inline scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua:126]: Conditional formatting

File: scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua [hunk 18]
```diff
@@ -0,0 +1,453 @@
...
+-- Maat : !pos 8 3 118 243
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/items")
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require("scripts/globals/titles")
+require('scripts/globals/interaction/quest')
+local ID = require("scripts/zones/RuLude_Gardens/IDs")
```
Comment (claywar) [inline scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua]: Similar to other scripts for ID var name and formatting

File: scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua [hunk 19]
```diff
@@ -0,0 +1,453 @@
...
+-----------------------------------
+local quest = Quest:new(xi.quest.log_id.JEUNO, xi.quest.id.jeuno.RIDING_ON_THE_CLOUDS)
+-----------------------------------
+
+local function handleSandoriaTrade(player, npc, trade)
+    if npcUtil.tradeHasExactly(trade, {xi.items.KINDREDS_SEAL}) then
+        quest:setVar(player, 'npcSandoria', 9)
+        player:tradeComplete()
```
Comment (claywar) [inline scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua]: Probably a confirmTrade here

File: scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua [hunk 20]
```diff
@@ -0,0 +1,453 @@
...
+        npcUtil.giveKeyItem(player, xi.ki.SCOWLING_STONE)
+    end
+end
+
+local function handleBastokTrade(player, npc, trade)
+    if npcUtil.tradeHasExactly(trade, {xi.items.KINDREDS_SEAL}) then
+        quest:setVar(player, 'npcBastok', 9)
+        player:tradeComplete()
```
Comment (claywar) [inline scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua]: Same as above

File: scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua [hunk 21]
```diff
@@ -0,0 +1,453 @@
...
+local function handleSandoriaTrade(player, npc, trade)
+    if npcUtil.tradeHasExactly(trade, {xi.items.KINDREDS_SEAL}) then
+        quest:setVar(player, 'npcSandoria', 9)
+        player:tradeComplete()
+        npcUtil.giveKeyItem(player, xi.ki.SCOWLING_STONE)
+    end
+end
+
+local function handleBastokTrade(player, npc, trade)
+    if npcUtil.tradeHasExactly(trade, {xi.items.KINDREDS_SEAL}) then
```
Comment (claywar) [inline scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua]: Don't need to define the item in a table if its only a single

File: scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua [hunk 22]
```diff
@@ -0,0 +1,453 @@
...
+        quest:setVar(player, 'npcBastok', 9)
+        player:tradeComplete()
+        npcUtil.giveKeyItem(player, xi.ki.SMILING_STONE)
+    end
+end
+
+local function handleWindurstTrade(player, npc, trade)
+    if npcUtil.tradeHasExactly(trade, {xi.items.KINDREDS_SEAL}) then
```
Comment (claywar) [inline scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua]: Same as above

File: scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua [hunk 23]
```diff
@@ -0,0 +1,453 @@
...
+        quest:setVar(player, 'npcWindurst', 9)
+        player:tradeComplete()
+        npcUtil.giveKeyItem(player, xi.ki.SPIRITED_STONE)
+    end
+end
+
+local function handleOtherlandsTrade(player, npc, trade)
+    if npcUtil.tradeHasExactly(trade, {xi.items.KINDREDS_SEAL}) then
```
Comment (claywar) [inline scripts/quests/jeuno/LB04_Riding_on_the_clouds.lua]: Same as above

File: scripts/quests/jeuno/LB05_1_Shattering_Stars.lua [hunk 24]
```diff
@@ -0,0 +1,147 @@
...
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/items")
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require("scripts/globals/titles")
+require('scripts/globals/interaction/quest')
+local ID = require("scripts/zones/RuLude_Gardens/IDs")
+-----------------------------------
```
Comment (claywar) [inline scripts/quests/jeuno/LB05_1_Shattering_Stars.lua:14]: ID var and formatting, also, could you make the last require quotes consistent with the others?  Switching from ' to "

File: scripts/quests/jeuno/LB05_1_Shattering_Stars.lua [hunk 25]
```diff
@@ -0,0 +1,147 @@
...
+                    end
+                end,
+            },
+
+            onEventFinish =
+            {
+                [64] = function(player, csid, option, npc)
+                    if option == 1 then
+                        local mJob = player:getMainJob()
+                        if mJob == xi.job.MNK or mJob == xi.job.WHM or mJob == xi.job.SMN then
```
Comment (claywar) [inline scripts/quests/jeuno/LB05_1_Shattering_Stars.lua:94]: This is a bit of a beefy conditional.  Not sure if there's a more simple way to handle this

File: scripts/quests/jeuno/LB05_1_Shattering_Stars.lua [hunk 26]
```diff
@@ -0,0 +1,147 @@
...
+        {
+            ['Maat'] =
+            {
+                onTrigger = function(player, npc)
+                    if utils.mask.isFull(player:getCharVar("maatsCap"), 6) and -- Defeated maat on 6 jobs.
+                        not player:hasSpell(xi.magic.spell.MAAT)
+                    then
+                        return quest:progressEvent(10241) -- Trust Event.
+                    else
+                        return player:showText(npc, 10448)
```
Comment (claywar) [inline scripts/quests/jeuno/LB05_1_Shattering_Stars.lua]: This should be quest:messageText so that default action isn't hit

File: scripts/quests/jeuno/LB05_2_Beyond_the_Sun.lua [hunk 27]
```diff
@@ -0,0 +1,78 @@
...
+-----------------------------------
+-- Log ID: 3, Quest ID: 76
+-- Maat : !pos 8 3 118 243
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require("scripts/globals/titles")
+require('scripts/globals/interaction/quest')
+-----------------------------------
```
Comment (claywar) [inline scripts/quests/jeuno/LB05_2_Beyond_the_Sun.lua:12]: Quote alignment and formatting

File: scripts/quests/jeuno/LB05_2_Beyond_the_Sun.lua [hunk 28]
```diff
@@ -0,0 +1,78 @@
...
+local quest = Quest:new(xi.quest.log_id.JEUNO, xi.quest.id.jeuno.BEYOND_THE_SUN)
+-----------------------------------
+
+quest.reward =
+{
+    item  = {xi.items.MAATS_CAP},
```
Comment (claywar) [inline scripts/quests/jeuno/LB05_2_Beyond_the_Sun.lua]: This item reward doesn't need to be in a table

File: scripts/quests/jeuno/LB05_2_Beyond_the_Sun.lua [hunk 29]
```diff
@@ -0,0 +1,78 @@
...
+                    else
+                        return quest:event(78, player:getMainJob()) -- Rematch dialog. Job dependant.
+                    end
+                end,
+            },
+
+            onEventFinish =
+            {
+                [74] = function(player, csid, option, npc)
+                    if player:getFreeSlotsCount() > 0 then
```
Comment (claywar) [inline scripts/quests/jeuno/LB05_2_Beyond_the_Sun.lua]: Not needed.  `quest:complete()` will fail if the item can't be given

File: scripts/quests/jeuno/LB06_New_Worlds_Await.lua [hunk 30]
```diff
@@ -0,0 +1,145 @@
...
+-- Nomad Moogle : !pos 10.012 1.453 121.883 243
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/items")
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require('scripts/globals/interaction/quest')
+local ID = require("scripts/zones/RuLude_Gardens/IDs")
+-----------------------------------
```
Comment (claywar) [inline scripts/quests/jeuno/LB06_New_Worlds_Await.lua:13]: ID var name and formatting

File: scripts/quests/jeuno/LB06_New_Worlds_Await.lua [hunk 31]
```diff
@@ -0,0 +1,145 @@
...
+            {
+                onTrigger = function(player, npc)
+                    return quest:progressEvent(10045, 75, 2, 10, 7, 30, 302895, 4095)
+                end,
+            },
+
+            onEventFinish =
+            {
+                [10045] = function(player, csid, option, npc)
+                    if option ==  4 then
```
Comment (claywar) [inline scripts/quests/jeuno/LB06_New_Worlds_Await.lua]: Formatting after ==

File: scripts/quests/jeuno/LB06_New_Worlds_Await.lua [hunk 32]
```diff
@@ -0,0 +1,145 @@
...
+                player:hasKeyItem(xi.ki.LIMIT_BREAKER) == false and
+                xi.settings.MAX_LEVEL >= 75
+        end,
+
+        [xi.zone.RULUDE_GARDENS] =
+        {
+            ['Nomad_Moogle'] =
+            {
+                onTrigger = function(player, npc)
+                    return quest:progressEvent(10045, 75, 2, 10, 7, 30, 302895, 4095)
```
Comment (claywar) [inline scripts/quests/jeuno/LB06_New_Worlds_Await.lua:47]: Do we have any idea what these parameters do, or just from caps?

File: scripts/quests/jeuno/LB06_New_Worlds_Await.lua [hunk 33]
```diff
@@ -0,0 +1,145 @@
...
+                        npcUtil.giveKeyItem(player, xi.ki.LIMIT_BREAKER)
+                    end
+                end,
+            },
+        },
+    },
+
+    -- Section: Quest available. Got Limit Breaker KI. Era server section.
+    {
+        check = function(player, status)
```
Comment (claywar) [inline scripts/quests/jeuno/LB06_New_Worlds_Await.lua]: Just noticed this, but also occurs above.  Could you please use the full parameter list, even if vars isn't being used at the moment?
`check = function(player, status, vars)` for quests

File: scripts/quests/jeuno/LB06_New_Worlds_Await.lua [hunk 34]
```diff
@@ -0,0 +1,145 @@
...
+            {
+                onTrigger = function(player, npc)
+                    return quest:progressEvent(10045, 0, 1, 1, 0)
+                end,
+            },
+
+            onEventFinish =
+            {
+                [10045] = function(player, csid, option, npc)
+                    if option ==  5 then -- Accept quest option.
```
Comment (claywar) [inline scripts/quests/jeuno/LB06_New_Worlds_Await.lua]: Formatting after ==

File: scripts/quests/jeuno/LB07_Expanding_Horizons.lua [hunk 35]
```diff
@@ -0,0 +1,93 @@
...
+-- Nomad Moogle : !pos 10.012 1.453 121.883 243
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/items")
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require('scripts/globals/interaction/quest')
+local ID = require("scripts/zones/RuLude_Gardens/IDs")
+-----------------------------------
```
Comment (claywar) [inline scripts/quests/jeuno/LB07_Expanding_Horizons.lua:13]: ID var name and formatting

File: scripts/quests/jeuno/LB07_Expanding_Horizons.lua [hunk 36]
```diff
@@ -0,0 +1,93 @@
...
+            {
+                onTrigger = function(player, npc)
+                    return quest:progressEvent(10045, 0, 1, 2, 0)
+                end,
+            },
+
+            onEventFinish =
+            {
+                [10045] = function(player, csid, option, npc)
+                    if option ==  7 then -- Accept quest option.
```
Comment (claywar) [inline scripts/quests/jeuno/LB07_Expanding_Horizons.lua]: Formatting after ==

File: scripts/quests/jeuno/LB07_Expanding_Horizons.lua [hunk 37]
```diff
@@ -0,0 +1,93 @@
...
+                        return quest:progressEvent(10136)
+                    end
+                end,
+            },
+
+            onEventFinish =
+            {
+                [10136] = function(player, csid, option, npc)
+                    if quest:complete(player) then
+                        player:tradeComplete()
```
Comment (claywar) [inline scripts/quests/jeuno/LB07_Expanding_Horizons.lua]: confirmTrade as opposed to tradeComplete

File: scripts/quests/jeuno/LB08_Beyond_the_Stars.lua [hunk 38]
```diff
@@ -0,0 +1,111 @@
...
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require('scripts/globals/interaction/quest')
+local ID = require("scripts/zones/RuLude_Gardens/IDs")
+-----------------------------------
+local quest = Quest:new(xi.quest.log_id.JEUNO, xi.quest.id.jeuno.BEYOND_THE_STARS)
+-----------------------------------
+
+-- TODO: Properly code the rock, paper, scissors minigame. Awaiting for a capture.
```
Comment (claywar) [inline scripts/quests/jeuno/LB08_Beyond_the_Stars.lua:19]: 👍

File: scripts/quests/jeuno/LB08_Beyond_the_Stars.lua [hunk 39]
```diff
@@ -0,0 +1,111 @@
...
+-- Log ID: 3, Quest ID: 135
+-- Nomad Moogle : !pos 10.012 1.453 121.883 243
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/items")
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require('scripts/globals/interaction/quest')
+local ID = require("scripts/zones/RuLude_Gardens/IDs")
```
Comment (claywar) [inline scripts/quests/jeuno/LB08_Beyond_the_Stars.lua]: ID var name and formatting

File: scripts/quests/jeuno/LB09_1_Dormant_Powers_Dislodged.lua [hunk 40]
```diff
@@ -0,0 +1,151 @@
...
+-- Log ID: 3, Quest ID: 136
+-- Nomad Moogle : !pos 10.012 1.453 121.883 243
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/items")
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require('scripts/globals/interaction/quest')
+local ID = require("scripts/zones/RuLude_Gardens/IDs")
```
Comment (claywar) [inline scripts/quests/jeuno/LB09_1_Dormant_Powers_Dislodged.lua]: ID var name and formatting

File: scripts/quests/jeuno/LB09_1_Dormant_Powers_Dislodged.lua [hunk 41]
```diff
@@ -0,0 +1,151 @@
...
+                        return quest:progressEvent(10191)
+                    end
+                end,
+            },
+
+            onEventUpdate =
+            {
+                [10192] = function(player, csid, option, npc)
+                    -- Option: Push! The option is the number of frames. 1 sec = 60 frames. Probably.
+                    if option >= 901 then
```
Comment (claywar) [inline scripts/quests/jeuno/LB09_1_Dormant_Powers_Dislodged.lua:116]: These options smell like a bitmask, and might be able to be broken out

File: scripts/quests/jeuno/LB09_1_Dormant_Powers_Dislodged.lua [hunk 42]
```diff
@@ -0,0 +1,151 @@
...
+                    player:setMerits(player:getMeritCount() - 10)
+                    quest:setVar(player, 'Prog', 1)
+                end,
+
+                [10192] = function(player, csid, option, npc)
+                    if quest:getVar(player, 'Win') == 1 then
+                        if quest:complete(player) then
+                            player:setLevelCap(95)
+                            player:messageSpecial(ID.text.YOUR_LEVEL_LIMIT_IS_NOW_95)
+                            player:messageSpecial(ID.text.KEYITEM_OBTAINED, xi.ki.SOUL_GEM)
```
Comment (claywar) [inline scripts/quests/jeuno/LB09_1_Dormant_Powers_Dislodged.lua]: No need for this messageSpecial if keyItem is in the reward table

File: scripts/quests/jeuno/LB09_2_Prelude_to_Puissance.lua [hunk 43]
```diff
@@ -0,0 +1,109 @@
...
+-- Log ID: 3, Quest ID: 170
+-- Nomad Moogle : !pos 10.012 1.453 121.883 243
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/items")
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require('scripts/globals/interaction/quest')
+-----------------------------------
```
Comment (claywar) [inline scripts/quests/jeuno/LB09_2_Prelude_to_Puissance.lua:13]: Formatting and quote consistency

File: scripts/quests/jeuno/LB09_2_Prelude_to_Puissance.lua [hunk 44]
```diff
@@ -0,0 +1,109 @@
...
+local quest = Quest:new(xi.quest.log_id.JEUNO, xi.quest.id.jeuno.PRELUDE_TO_PUISSANCE)
+-----------------------------------
+
+-- TODO: Properly code timing minigame. Awaiting for a capture.
+-- Amount of visual qeues selected at random. Min: Probably 3. Max: 7. Camera angle keeps changing qithout hints.
+-- Always the same camera angle at victory.
+
+quest.reward =
+{
+    fame  = 50,
```
Comment (claywar) [inline scripts/quests/jeuno/LB09_2_Prelude_to_Puissance.lua]: Spacing before =

File: scripts/quests/jeuno/LB09_2_Prelude_to_Puissance.lua [hunk 45]
```diff
@@ -0,0 +1,109 @@
...
+                end,
+            },
+
+            onEventFinish =
+            {
+                [10045] = function(player, csid, option, npc)
+                    -- All this options complete the trade and complete the current quest.
+                    if option == 13 or option == 14 or option == 15 or option == 19 or option == 20 or option == 21 then
+                        if quest:complete(player) then
+                            player:tradeComplete()
```
Comment (claywar) [inline scripts/quests/jeuno/LB09_2_Prelude_to_Puissance.lua]: confirmTrade

File: scripts/quests/jeuno/LB09_2_Prelude_to_Puissance.lua [hunk 46]
```diff
@@ -0,0 +1,109 @@
...
+
+                            -- This options immediately start next quest. (All except 15).
+                            if option == 13 or option == 14 or option == 19 or option == 20 or option == 21 then
```
Comment (claywar) [inline scripts/quests/jeuno/LB09_2_Prelude_to_Puissance.lua]: This can be simplified to `if option ~= 15` since the other values are required before entering this block

File: scripts/quests/jeuno/LB10_Beyond_Infinity.lua [hunk 47]
```diff
@@ -0,0 +1,230 @@
...
+-- Nomad Moogle : !pos 10.012 1.453 121.883 243
+-----------------------------------
+require("scripts/settings/main")
+require("scripts/globals/items")
+require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
+require("scripts/globals/quests")
+require("scripts/globals/titles")
+require('scripts/globals/interaction/quest')
+local ID = require("scripts/zones/RuLude_Gardens/IDs")
```
Comment (claywar) [inline scripts/quests/jeuno/LB10_Beyond_Infinity.lua]: ID var name, formatting, quotes

File: scripts/quests/jeuno/LB10_Beyond_Infinity.lua [hunk 48]
```diff
@@ -0,0 +1,230 @@
...
+-----------------------------------
+local quest = Quest:new(xi.quest.log_id.JEUNO, xi.quest.id.jeuno.BEYOND_INFINITY)
+-----------------------------------
+
+quest.reward =
+{
+    fame  = 50,
```
Comment (claywar) [inline scripts/quests/jeuno/LB10_Beyond_Infinity.lua]: Spacing before =

**Review by claywar — CHANGES_REQUESTED** [review]
Great start for something that needed a ton of cleanup!  Left a few minor notes for things that could be changed, and some styling things.

File: scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua (hunk 2 above)
Comment (Xaver-DaRed) [reply scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua:35]: Just to make sure...

`if
    player:hasKeyItem(whatever) and
    npcUtil.giveItem(player, whatever)
then`

is the correct way?

File: scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua (hunk 1 above)
Comment (Xaver-DaRed) [reply scripts/quests/jeuno/LB01_In_Defiant_Challenge.lua]: Well, in this concrete case, I just noticed it isnt used. But I will in future ones.

File: scripts/quests/jeuno/LB06_New_Worlds_Await.lua (hunk 32 above)
Comment (Xaver-DaRed) [reply scripts/quests/jeuno/LB06_New_Worlds_Await.lua:47]: Somewhat. event 10045 is the global event used in all Limit break quest from 6 to 10.
First argument is mostly 0 in all except here, wich happens to be either player level or level cap.
Second or third argument goes up the higher the LB quest
The rest, i have no clue. I havent tried it without those, but im inclined to believe they are just unused garbage data.

Comment (claywar) [reply scripts/quests/jeuno/LB06_New_Worlds_Await.lua:47]: Seems reasonable.  Can you leave a TODO with similar info there, so that if we get additional data in the future it can be reduced to whats needed?

File: scripts/quests/jeuno/LB09_1_Dormant_Powers_Dislodged.lua (hunk 42 above)
Comment (Xaver-DaRed) [reply scripts/quests/jeuno/LB09_1_Dormant_Powers_Dislodged.lua]: For some reason, if it isnt there, the message wont show up after the event is finished.

Comment (claywar) [reply scripts/quests/jeuno/LB09_1_Dormant_Powers_Dislodged.lua]: Since there's no item reward, just out of curiosity could you try:
setLevelCap
Level limit 95 message
quest:complete(player)
?

File: scripts/quests/jeuno/LB09_1_Dormant_Powers_Dislodged.lua (hunk 41 above)
Comment (Xaver-DaRed) [reply scripts/quests/jeuno/LB09_1_Dormant_Powers_Dislodged.lua:116]: I dont really know, but it seemed like a progresive count.
The moment the option is selected in client, the option ID seems to be set to the time passed since the start. (Not the start of the event, the start of the counting.)

File: scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua [hunk 49]
```diff
@@ -0,0 +1,134 @@
...
+            },
+        },
+
+        [xi.zone.MONASTIC_CAVERN] =
+        {
+            ['qm1'] =
+            {
+                onTrigger = function(player, npc)
+                    if not player:hasKeyItem(xi.ki.ORCISH_CREST) then
+                        return npcUtil.giveKeyItem(player, xi.ki.ORCISH_CREST)
```
Comment (claywar) [inline scripts/quests/jeuno/LB03_Whence_Blows_the_wind.lua]: One additional note, for these onTrigger returns, it needs to be from the mission class to not trigger the default action if there is one.  Should be returning `mission:keyItem(xi.ki.ORCISH_CREST)` and similar for the others

File: scripts/quests/jeuno/LB06_New_Worlds_Await.lua [hunk 50]
```diff
@@ -0,0 +1,152 @@
...
+        },
+    },
+
+    -- Section: Quest available. Got Limit Breaker KI. Era server section.
+    {
+        check = function(player, status, vars)
+            return status == QUEST_AVAILABLE and
+                player:getMainLvl() >= 75 and
+                player:getLevelCap() == 75 and
+                player:hasKeyItem(xi.ki.LIMIT_BREAKER) == true and
```
Comment (claywar) [inline scripts/quests/jeuno/LB06_New_Worlds_Await.lua]: Don't need to have a == true here

File: scripts/quests/jeuno/LB06_New_Worlds_Await.lua [hunk 51]
```diff
@@ -0,0 +1,152 @@
...
+        },
+    },
+
+    -- Section: Quest available. Got Limit Breaker KI. Can actually raise level cap.
+    {
+        check = function(player, status, vars)
+            return status == QUEST_AVAILABLE and
+                player:getMainLvl() >= 75 and
+                player:getLevelCap() == 75 and
+                player:hasKeyItem(xi.ki.LIMIT_BREAKER) == true and
```
Comment (claywar) [inline scripts/quests/jeuno/LB06_New_Worlds_Await.lua]: Same as above

File: scripts/quests/jeuno/LB10_Beyond_Infinity.lua [hunk 52]
```diff
@@ -0,0 +1,232 @@
...
+                onTrigger = function(player, npc)
+                    return quest:progressEvent(10045, 0, 1, 5, 0, 1)
+                end,
+            },
+
+            onEventFinish =
+            {
+                [10045] = function(player, csid, option, npc)
+                    -- This options start quest.
+                    if option == 13 or option == 14 or option == 19 or option == 20 or option == 21 then
```
Comment (claywar) [inline scripts/quests/jeuno/LB10_Beyond_Infinity.lua:51]: Is there a warp option for 13?  Or does it just stay in Jeuno?

Comment (Xaver-DaRed) [reply scripts/quests/jeuno/LB10_Beyond_Infinity.lua:51]: you stay

**Review by claywar — APPROVED** [review]
