### PR TITLE
[core] Fix bug for out of range slot ids in UnequipItem

### LINKED ISSUE #7568: 🐛 CLuaBaseEntity::unequipItem crashes with invalid slot ID
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my issue will be ignored.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have searched existing [issues](https://github.com/LandSandBoat/server/issues) to see if the issue has already been opened, and I have checked the commit log to see if the issue has been resolved since my server was last updated.

## Branch affected by issue 

`base`

## Steps to reproduce

!exec player:unequipItem(15762)
Map server will crash

The documentation states this takes an item ID but it's actually a slot ID.

## Expected behavior

Slot ID is checked to be within bounds. An error is logged when out of bounds. 
Documentation is updated to reflect this expects a xi.slot enum.

### PR DESCRIPTION
**Pull request by Flibe-XI**
**_I affirm:_**
- [x] I understand that if I do not agree to the following points by completing the checkboxes my PR will be ignored.
- [x] I understand I should leave resolving conversations to the LandSandBoat team so that reviewers won't miss what was said.
- [x] I have read and understood the [Contributing Guide](https://github.com/LandSandBoat/server/blob/base/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/LandSandBoat/server/blob/base/CODE_OF_CONDUCT.md).
- [x] I have _**tested my code and the things my code has changed**_ since the last commit in the PR and will test after any later commits.

## What does this pull request do?

Fixes bug that crashes map-server when out of range value passed to charutils::UnequipItem.  Also update related function in lua_baseentity.cpp to better describe arg.

## Steps to test these changes

!exec player:unequipItem(#) for # 0 - 15 will work, for any other number, will show error in log.  Fixes #7568.

### CODE REVIEW

File: src/map/utils/charutils.cpp [hunk 1]
```diff
@@ -1678,6 +1678,18 @@ namespace charutils
 
     void UnequipItem(CCharEntity* PChar, uint8 equipSlotID, bool update)
     {
+        if (PChar == nullptr)
+        {
+            ShowWarning("PChar was null.");
+            return;
+        }
+
+        if (equipSlotID < 0 || equipSlotID > 15)
```
Comment (zach2good) [inline src/map/utils/charutils.cpp]: If equipSlotID is uint8 it is impossible for it to be less than zero (unsigned integer)

**Review by Xaver-DaRed — APPROVED** [review]
Note for self: We should make this function name more clear. Like "unequipFromSlot()".
A TODO for some1 in the future, not for this PR.

**Review by zach2good — APPROVED** [review]

File: src/map/lua/lua_baseentity.cpp [hunk 2]
```diff
@@ -4976,17 +4976,17 @@ void CLuaBaseEntity::equipItem(uint16 itemID, sol::object const& container)
...
- *  Purpose : Unequips an item from player
- *  Example : player:unequipItem(17845)
- *  Notes   :
+ *  Purpose : Unequips an item from player based on slot id
+ *  Example : player:unequipItem(4) -- Head
+ *  Notes   : Range 0 - 15
  ************************************************************************/
 
-void CLuaBaseEntity::unequipItem(uint8 itemID)
+void CLuaBaseEntity::unequipItem(uint8 slotID)
```
Comment (zach2good) [inline src/map/lua/lua_baseentity.cpp:4984]: The header doesn't reflect this change: `    void unequipItem(uint8 itemID);`
